== Chapter I.

I have had it on my mind for a considerable time,
to commit to writing some of the many occurrences that have befallen me;
and of the precious visitations,
and merciful dealings of the Almighty with me from my youth up.

I was born at Brigg, in Lincolnshire, on the 4th day of the ninth month, old style, 1715.
My father`'s name was John, son of John and Mary Oxley of Criggleston,
in the parish of Sandel, and county of York.
My mother`'s name was Ann, daughter of Joseph and Catherine Peckover, of Fakenham,
in the county of Norfolk.

Respecting my mother, my father left this short testimony:--"`Ann Oxley, of Brigg,
departed this life the 27th of the sixth month, 1720; and was interred at Castlethorp,
in Friends`' burial-ground, the 30th day following,
aged thirty-three years and three months.
She was a virtuous, zealous woman, sometimes publicly engaged in meetings,
and loved and entertained Friends heartily who came to visit us.
She was naturally a woman of a ready wit, charitable to the poor, a friendly neighbour,
and well beloved of all.
We had a good meeting at her interment,
wherein several testimonies were borne concerning her; also at the burial-ground,
all signifying her departure was in peace with the Lord.`"
About three years afterwards,
it pleased Divine Providence to visit my dear father with a sore fit of sickness,
of which he also died, the 29th of the twelfth month, 1723, aged forty years;
leaving three children, Joseph, Ann, and John,
thus rendered destitute not only of natural, but religious parents.
I was the eldest.

About the eighth year of my age,
we all came under the care of my grandfather and grandmother,
Joseph and Catherine Peckover;
myself more particularly under the guardianship
of my dear and honourable uncle Edmund Peckover.
My sister became the care of my grandmother, and my uncle Joseph Peckover, of Fakenham,
took the care of my brother John, who was the youngest.
I was boarded at Brigg, with Ann Bethell, widow, a valuable Friend,
until such time as my relations could settle my father`'s affairs.
I went to school in the town, but have no reason to think I was one of the best boys;
for though I was very young, I well remember that one night on going to bed,
curiosity led me to look into the maid`'s trunk, which was in the chamber, and unlocked:
on opening and searching the trunk,
I found a little screw box which I ventured to examine; its contents were chiefly silver.
I thought I might hazard to take sixpence, and not be found out; which I did, and no more.

My mistress, with whom I went to school, sold nuts, gingerbread, sweetmeats, etc.,
some of which I bought, and distributed amongst my school-fellows, and played truant;
on which I was suspected, and at night my pockets were examined,
and I was found to have spent about two-pence,
for which the next day I underwent the discipline of the rod,
which I have had reason to think was of service to me,
not remembering I have ever done the like since.
Soon after this I was sent to Gilbert Thompson`'s school, at Sankey, in Lancashire,
a very good school; but I was very unapt at learning my books,
though few exceeded me at play.
One time in particular I have reason to remember.
My master being from home, I had agreed with another boy to run a race,
and for each of us to carry another boy on our backs; and in running,
I fell down with my leg under me, by which means I broke my thigh,
which proved a source of long confinement, sorrow, and trouble.
The surgeon who set it, not being sufficiently mindful, set it wrong,
and in this state it remained several days,
when at length it had to be broken again and set afresh,
which indeed proved an unspeakable sorrow; but afterwards the parts united and did well.

About this time my dear grandfather Peckover, of Fakenham, departed this life,
and bequeathed something for my further education, etc.
After being at school more than five years, I was sent to Scarborough, in Yorkshire,
to be an apprentice to a clockmaker.
But when my master came to see me, he was afraid to take me,
because I was so very low of stature, and sent me to school again,
to a Friend who lived in the town, where I also underwent some profitable correction,
as well as acquired useful learning.

The following summer, my uncle, Edmund Peckover,
being on a religious visit in these parts, I was bound an apprentice to Robert Henderson,
of Scarborough, clock maker.
My uncle recommended to my master,
that he should let me attend week-day meetings as often as it was convenient.
His great care over me in that respect made lasting impressions on my mind,
even to this day; and I have been careful to be exemplary therein,
and in bringing up my family in that commendable practice.
My master and dame, for so I was ordered to call my mistress, were both sober,
valuable Friends, and orderly in their conversation;
but such of us as were under their care as apprentices, journeymen, etc.,
were unruly and disorderly, very unbecoming and reproachful, idle, loose, and profligate,
corrupting one another in many evils, frequenting ale-houses, and gaming;
practices destructive both to body and soul.
Let all beware lest they unhappily fall into these evils,
and bring the Lord`'s displeasure on them as I did.
I liked very well the business, but it was too hard and laborious for my strength.
I had also a pretty deal of other business, such as cleaning boots and shoes,
looking after my master`'s horses, etc., as occasion required,
which kept me very backward in my business.
Having served my master seven years, my time with him expired.
I am far from being able to give a good account of myself during these seven years.
I remained exceedingly raw and ignorant respecting religion,
negligent in attending meetings, for which my master and dame would often reprove me,
and on a first-day evening they would frequently
call us together to read in the Holy Scriptures.
My mind seemed at this time to be estranged from anything that was good,
and I turned a deaf ear to all advice and counsel that
had a tendency to settle the mind in the fear of God.

Being now in the twenty-second year of my age, I left Scarborough,
and by order of my uncles, Edmund and Joseph Peckover, went to Brigg, my native place,
and by their advice, disposed of an estate of my late father`'s: from there into Norfolk,
to see my relations there, which afforded me very great satisfaction,
and not the least to see my dear brother, who was then an apprentice to John Northern,
a Friend at Walsingham, in said county: I had not seen him for about thirteen years.
We were exceedingly rejoiced to see each other, and though we were so long parted,
I believe brotherly affection remained as strong
as if we had lived together all that time.
I spent some time in the country with my aged and honourable grandmother,
who was a mother in our Israel,
and would often be giving me such advice as I stood in need of,
but it had little effect at that time.
It now became time for me to think how I must live in the world,
for at present I was neither in circumstances, nor otherwise qualified,
to set up in my business, being altogether ignorant in the watch-making branch,
which I thought highly necessary to know; and, in order thereto, I went up to London,
where I met with my uncle Edmund, and by the interest he made, I got a place,
though not so suitable as could be desired.

My instructor was a good workman, and in many respects kind;
but he was very much lacking in religion,
seldom or never going to any place of religious worship.
He was by profession of the Church of England, so called.
I indented with this man for two years to learn to be a watch-maker,
which I liked very well.
My master was a good-natured man, and willingly agreed with my uncle`'s proposal,
in letting me go to a week-day meeting once a week.
Thus was my uncle`'s kindness and care continued
over me so long as I remained under his charge.
My master would often take me out with him, and make me as his companion:
I used to be frequently with him at his clubs and places of diversion,
and at these places I learned to sing what they called a good song,
and so became one with them.

But even at that time, I was under such strong inward convictions,
that my heart was filled with grief, and however joyous I might appear outwardly,
I was inwardly condemned.
My mistress was a Dutch woman, but not of that free disposition as was my master.
Once on a trifling occasion she was angry with me,
and her passion increased to such a degree, that she threatened my life,
and caught up a case-knife for that purpose,
and in her great fury and rage made an attempt, to give the fatal stroke;
but providentially, for I cannot call it anything less, the maid-servant interposed,
and took hold of her arm, by which means she was prevented doing the intended evil,
and gave me an opportunity of making my escape.
My master being from home was sent for, and was under great concern and sorrow;
he requested I would pass by the offence,
and promised he would do what lay in his power to make me easy,
and to prevent in the future any such insults, which he found difficult to do.
I believe the greatest dislike she had to me was, because I was one called a Quaker.
Though far from what I should be,
yet I could not compliment her in the way she required of me.
I had now lived with my master about one year and a half, and so far from growing better,
I grew worse,
and brought great sorrow and trouble on my relations and friends in the country,
whom I wanted to see, and an agreeable opportunity offering I ventured to go.
But I met with a very cool reception,
and while I stayed in the country rather lost than got reputation and favour.
I soon returned again to London, and my master received me very cordially.

About this time there came to town a young man, George Whitefield, educated a clergyman,
who preached sometimes in steeple-houses and at other times in fields, etc.;
and many were excited to go and hear him, amongst whom I was one, and as I thought,
he spoke as one that had authority and not as the scribes;
so I returned very well satisfied.

Soon after, I heard he was to preach at Kennington Common, a short distance from London,
to which place I resorted amongst a great many thousands of people.
The day was excessively hot, and I was in the throng of the people,
and being very low of stature, was overcome to such a degree with the crowd pressing me,
and continued so long,
that I thought verily I should have been smothered to death in a very little time.
Oh! the distress of mind I was now in!
The horror and confusion of my soul was beyond all description!
The terrors of the Lord were upon me;
the stings of a wounded conscience I felt to pierce
through and through for sin and transgression.
I thought I was in a few moments going to launch out of time into eternity,
nothing but everlasting woe and misery seemed to be my portion forever and ever!
My agony was so great, both in body and mind,
as to make it intolerable to bear without loud shrieks and cries,
which were heard far and near, by very many.
The press was so great, that they who had their arms down could not get them up,
till at length a gentlewoman in a coach noticed my condition,
extended herself as far out as she well could, and with her fan yielded me some relief,
which enabled me to stand it till the preacher had done.
Now was my heart made to rejoice, and my tongue broke forth into singing,
unto Him to whom I was so largely indebted, and by whose providence I was yet spared;
and even at this very time I cannot help saying, "`I thank you,
O my heavenly Father! in that you did not call me away in that unprepared hour,
to give an account of my stewardship;
very unfit I most assuredly was to appear before your great tribunal: I beg, I may ever,
while I live, reverently and gratefully remember and acknowledge this day,
wherein you were pleased so mercifully to spare, to reach,
and to visit so effectually my soul.
'`Now I know that my Redeemer lives,
and because he lives I live also.`'`" I returned
home filled as with the new wine of the kingdom:
when I got home, I stripped myself of my wet clothes;
for I was comparatively as if I had come out of a pond,
and I was stopped by several to know where I had been, I was in such a strange condition.
But oh! the draft of divine consolation,
the gracious aboundings of the love of God to my soul,
it was so ravishing to my heart that I never felt the like before:
I was almost fit to be swallowed up in an ecstasy of joy.

I now loved to attend meetings for religious worship,
on week-days as well as those on the first-day of the week,
from which I experienced great benefit and strength.
Soon after this, I got acquainted with one James Oldham,
of whom I inquired if he could inform me of a suitable place to live at,
as my time with my master was near expiring.
He replied, he did not know but I might have such accommodations where he himself lived,
and that if I liked he would make the necessary inquiry, and let me know;
of which I much approved, and indeed it was what I much desired,
for I knew the Friend with whom he lived.
When the time came, my master and I parted very good friends,
continuing a correspondence as occasion required.
It was not long after I left my master,
before I went to see him again about some business; and falling into conversation,
he signified to me,
that several young men who had been under his
care for improvement in like manner as myself,
had agreed to go with him to Islington and take a game at skittles, etc.,
and desired my company.
I would have excused myself by saying I was ignorant of the play,
but he said he would not be denied, but go I must.
I then agreed to make one of the company, and he thanked me.
Immediately, I did not like what I had promised, but I thought within myself,
I would keep from committing sin as much as it was possible.
There lived at this time a young man with my master, in the capacity of an apprentice,
who was nearly out of his time; he was sober and very religious in his way,
and showed great friendship for me.
He came to my new quarters,
to see me and speak to me about the engagement I
had come into with my master as above related,
which he thought was by no means consistent with the profession I made,
and would eagerly have me not to go.
But I replied, that as I had passed my word,
I could not depart from it without telling a lie.
James Oldham, of whom I shall have occasion to speak more largely by and by,
joined the young man, who was what is called a Methodist,
in giving me advice in this matter.

James Oldham, in whom was the Spirit of Truth and righteousness,
argued so clearly and powerfully, and so convincingly as to overcome me,
notwithstanding all my attempts to defeat him;
he set forth good and evil in such an excellent manner,
attended with that wisdom which is from above.
In this dispute, I was again overcome with the flowings forth of heavenly virtue,
and my heart was humbled as in the Divine presence, that I was even ready to say,
"`Lord make me what you would have me to be;`" and in
yielding myself cheerfully to the will of God,
it procured for me that peace which the world cannot give nor take away.

From this time I began to seek the Lord in the way of his requirings,
and forsook all my old companions and idle pastimes,
and led a life of circumspection and care.
This was the time of my espousals,
a time wherein nothing appeared to me so lovely as the Truth.
I was well pleased that I had got into this family,
as having my dear friend James Oldham for a companion.
He came from Warrington, in Lancashire, up to London when a young man,
and being by occupation a barber and perriwig-maker,
worked at his business in the capacity of a journeyman.
He told me, that he himself had been a very great libertine,
accustomed himself to frequent swearing, insomuch that he did not know when he did it.
I think he was brought up in the way of the Church of England, so called,
and was convinced of the Truth in London some few years before I had knowledge of him.
He was a very comely young man, unmarried,
endued with a large share of natural understanding,
which was under the government of best wisdom; and lived in abstinence,
that he might the better feed the hungry and clothe the naked.

His chief diet was bread and water, sometimes milk;
he was cheerful and pleasant in conversation, as also very instructive and edifying:
I never heard him speak evil of any,
but he made it a rule if he could not speak well of a person,
to be silent rather than speak to their prejudice.
He was of a meek and humble spirit,
a diligent attender of religious meetings for worship,
both as to the day and time appointed;
the becoming gravity and steadiness with which he sat in meetings,
from the beginning to the end, was profitable and instructive to behold;
was never heard speaking slightly of any testimony that was dropped in a meeting,
or the instrument of it, though never so mean or contemptible.
He was full of love and good works, and abounded in charity to people of all professions;
it seemed to me to be his meat and drink to do the will of his Maker.
He was the greatest pattern of Christian perfection of all I ever knew;
his work was cut short in righteousness;
he was taken ill of a fever which was very violent, and continued but a few days;
he lived and died in the Lord!

But to return,--the news of my being somewhat reformed, soon got into the country,
which was very pleasing to my relations;
but they also received an account that I had got
into a very singular and strange way of dress,
as a wig without any curls, undyed stockings, shoe-strings instead of buckles, etc.,
and some said, that I was the same as before,
only that I had made an alteration in dress to deceive:
but time manifested all this to be untrue.
My brother, who lived in the country,
and was before this under the like precious visitation,
and had made some profitable steps in the way of life and salvation
was not a little rejoiced at this religious turn in me,
and from him I often received letters, which were greatly to my edification and comfort.
We always loved one another very affectionately, but now far more than ever,
as children not only of the natural, but also of the heavenly Father:
after this manner we continued to love and live to the end.
I followed my watch-making business in the capacity of a journeyman,
and at best could make but poor earnings,
and in the time of the hard frost was forced to live very sparingly to make it do;
yet I was content and thankful in this respect, and being steady I became more known,
and grew in the esteem of Friends.
