== Chapter VI.

Being free from any religious constraint of travelling
abroad in the service and work of the Gospel,
I remained at home, continuing in my business,
and living peacefully and comfortably with my family and amongst my friends,
with great nearness and unity, harmony and love;
that I have not anything worthy of remark till entering into the year 1766.
In the first month of which year, my wife, with the approbation of her Monthly Meeting,
visited Friends in and about London, to good satisfaction,
and to the comfort and peace of her own mind, and returned home the 22nd of second month,
to the rejoicing of her family.

Having been exercised for some time past in a godly concern to visit Friends,
in a religious capacity, in the north of Yorkshire, Durham, Northumberland, and Scotland,
I got in readiness, and acquainted my friends with my concern,
requesting their approbation and certificate, which was granted me.
John Roper, a Friend of our city, who had been some years before convinced,
and come forth in public ministry,
also found it on his mind to accompany me in the said service, which I well approved.
My eldest son Joseph, by this time, was grown up; and being steady and sober,
I committed the management of my business to his care,
under the assistance of my brother John Oxley; and the time being come,
I took a solemn farewell of my family and friends,
and set forward on the 2nd of the eighth month, 1766.

+++[+++After passing through Lincolnshire, where at Wainfleet they lodged at William Reckitt's,
who had not long been returned from a religious visit to America, they went on to Hull,
where they]
had a meeting to which came abundance of other societies,
and we were made partakers of that Divine power and presence,
by which our hearts were renewedly comforted, and enabled to praise the Lord,
in deep reverence of soul, for his goodness to us,
which was beyond what our tongues could utter.

+++[+++They visited the north of Yorkshire and Durham,
which it is not necessary to particularize,
except that he mentions meeting with Philip Hasleton, at Moorsum, in Yorkshire,
a very ancient Friend and minister,
who had formerly travelled in the service of Truth with Luke Cock; also at Raby,
in DurJiarn, with Joshua Dickson,]
who has been a valiant in the cause of righteousness in our Israel,
having travelled through most parts of England, Ireland and America,
and his labours of love were very acceptable.
But, at this time, we found him very low in his mind, and sorely tossed and distressed,
and almost ready to distrust in the goodness and mercy of God.

The meetings at Sunderland were large,
and enlivened through the goodness of our great and good Master.
The 8th, we were at Newcastle, being their Monthly Meeting, which was large;
there were several ministering Friends, besides ourselves, who were strangers,
and much was said in the springings of Truth, to edification.
We passed on through the county of Northumberland:
there are but few Friends in these parts, and meeting-houses very few,
and much coolness and indifferency towards religion.
We went to Cornwood, and lodged at Cuthbert Wigham's, a worthy elder and minister,
who has four daughters in that religious capacity.
We were at this meeting on first-day the 14th, which was large;
abundance of the people called Methodists came in,
so that the house was pretty well filled, and though Truth did not seem to rise high,
yet it was a good, quiet meeting.
Had a meeting at our quarters in the evening,
wherein was experienced a flow of that Divine life and power,
by which we were made alive, and the Lord alone praised, who is worthy forever and ever!
On the 16th we went to Jedburgh, in Scotland, and next day lodged at Kelso,
at Charles Armstrong's, an ancient Friend and minister;
he was much weakened in his faculties through age, etc.;
his children married out of the Society, but,
through the precious visitation of the Almighty,
his daughter so offending has taken a sober religious turn,
and sometimes appears in a few words in meetings.

We had a meeting with them, to which came many of the town's people,
and heard with attention the preaching we had to declare,
and through Divine favour it was an opportunity to mutual comfort.
Here is a hopeful family in this town, James Anderson, his wife, son, and daughter,
with whom we were renewedly strengthened, and they with us: we rested a day here,
and then directed our course to Edinburgh, accompanied by James Anderson the younger.

We were at both their meetings on the first-day,
which were made large by the coming in of other societies;
I hope they were in a good degree to satisfaction, both to the visitors and visited.
We had also a meeting in the evening, among Friends only, which was a time of favour,
labour was extended for an increase of love,
and they were exhorted to cherish a disposition to receive it.
We were informed a matter of difference had got in amongst Friends in this place,
and we found our minds concerned to labour with them,
in hopes we might be helpful to reconcile them one unto another.
I think my companion was far the most useful in this undertaking,
which he handled with great wisdom and prudence;
by which the transgressors were brought to see they had greatly missed it,
and erred from that love and meekness which is in the Truth,
of which they made ample acknowledgment,
and even did all we requested of them towards bringing about a reconciliation.
My companion was rather desirous of having a meeting at Kirkaldy, to which we went,
and had a large gathering in a convenient house.
I had an opportunity pretty early in the meeting, and the people were orderly and still,
after which my companion stood up and preached well; but standing a long time,
the place being crowded and thronged, and the weather bad,
the people grew uneasy and tired, and wanted to be going,
and they began to create noise and disturbance,
so that the meeting did not conclude with so much satisfaction as I could have wished.
Yet many seemed to approve of the doctrine they heard,
and I doubt not it will have its service: they said,
there had not been a Friend's meeting there before in any of their memories.

Fifth-day, the 25th, we set forward for Dundee,
where was no meeting nor members of our Society.
Sixth-day went to Montrose, at which place is one family of Friends,
but they had not convenience to lodge us.
About a mile out of the town, there lived an old bachelor, Henry Napier,
who had formerly entertained Friends,
and had been a considerable professor in the same way,
and had appeared in a ministerial capacity, but through unwatchfulness was dwindled away.
We went to see him, but he received us very coolly,
said he had not accommodations for our lodging; but after being there some time,
and having much conversation with him, he said he would receive us on our return,
and with much ado promised he would grant us a meeting at his house,
but that he could not take in our horses; so we went back to our inn at Montrose,
and lodged there.

The next day we went to Ury, and dined with Robert Barclay.
R+++.+++ B. sent a boy with us to Aberdeen, which was on the seventh-day,
and first-day we were at both their meetings, which were very large,
though but few in profession with us; they were quiet and still,
their behaviour very becoming, and the Lord's power was great and mighty,
and Truth exalted, and his holy name praised, who is God over all blessed forever!
Second-day we rode to Old Meldrum, and the next day had a meeting there:
here is the largest body of Friends in Scotland.
I was silent at this meeting, but not my companion, who I trust had good service.

Fourth-day had a meeting at Kinmuck; the same evening went to Kingswells,
lodged at Gilbert Jaffray's, who had married a Presbyterian: had a very good meeting.
A few honest good Friends live here and hereaway, though they are poor as to this world,
yet rich in faith and good works.

+++[+++Under the date of the 30th of ninth month, at Old Meldrum, he thus addresses his wife:]


"`Your very precious epistle, I received at Edinburgh, much to my comfort and edification.
You are very acceptable to me in that which is most durable and lasting, wherein,
I trust, though far absent in body, we are made partakers.
This is what unites us, and herein stands our fellowship.
However lovely one to the other,
we are to consider ourselves servants to Him who has called us; unto whose service,
I desire we may be freely given up.
He is a rich and plenteous rewarder of all those
that cheerfully serve and faithfully obey him.
My cries are often to the Fountain of Goodness,
that I may be endued with patience to the end of the present engagement.`"

Being now on our return, on seventh-day came to Ury,
and had a meeting on first-day there, where the pure life was oppressed,
and in great bondage; same evening went down to Stonehaven,
where with a few Friends and many others we had a far more comfortable meeting.
Second-day went to Tyacke, where lives Henry Napier,
who promised to take us in at our return, and grant us a meeting at his house,
with that family at Montrose, and another of his own name at a small distance from him,
but not allow it to be more public: all which was complied with,
and we had a very choice good meeting in his house,
very suitable advice and counsel was given under the direction of the Great Master,
which, if properly attended to, would be greatly to their benefit and increasing good.
We parted with them in much love, and went on to Glasgow,
visiting two or three scattered families professing with us in our way.
At Glasgow we lodged at Provost Ayton's, no Friend of account living here;
and on first-day we went to meeting, and after some time sitting,
there came in pretty many, with some of Provost Ayton's family,
who conducted themselves soberly and well, and we had a good meeting.

In the afternoon the meeting was far more considerable,
and the people as quiet and still as we could expect.
I trust the good hand of the Lord was with us,
and supported us in that cause of which we were not ashamed.
We could not well help remarking, as we passed along to meeting,
both morning and afternoon,
the order and becoming behaviour of the people
in attending their places of religious worship;
the vast number of inhabitants who filled the streets from one end to the other,
and all so seemingly well disposed, that I could not but behold it with admiration.
I wish our people in England would follow their example,
which would be more to their reputation than spending
that day in so profane a manner as many of them do.
We returned by way of Edinburgh;
some of their members who were absent when we were there before,
and were principal in the matter before hinted, being now returned,
and dissatisfied with the terms of accommodation,
we had another public meeting for worship, in which the power of Truth became prevalent,
which so cemented us together, that we were as one heart and one mind.
In the evening, we had all the contending parties together,
and the good hand of the Lord was with us, to the healing of breaches,
and restoring into love and unity one with another;
and after all these disputes were ended and matters settled,
we were drawn into retirement: a favoured opportunity it proved,
wherein suitable instruction and counsel was given, which, if diligently attended to,
would keep them in the unity of the Spirit, which is the bond of peace.
We lodged at William Miller's, who has been remarkably kind to such poor travellers,
not only in entertaining them at his house,
but also in furnishing them with guides for many days together, chiefly at his own cost,
which we thought was too oppressive.
At the following Yearly Meeting it was agreed,
that in future such expense should be defrayed out of the general stock; for, before,
it was also very expensive to the travelling Friends themselves,
who in various places have neither guides, except what they themselves provide,
nor Friends' houses to accommodate them, but must be all at their own cost,
which for some was very hard to bear, but now is made easy, and to general satisfaction.
After a stay of two days we set forward to Kelso, and on seventh-day reached Carlisle.

Before I leave Scotland, I would just observe,
that I have had great satisfaction in paying this poor nation a Christian visit,
yet am sorry to see the Society at so low an ebb in this part of the world.
The great loss here, as in many other places,
has been a departure from the principles of our worthy predecessors,
and falling into the love of the world, with its various enticements,
delusive pleasures and delights.
Those who follow these gradually fall from the honest, simple, plain way of dress,
and from plainness of speech,
and also decline in their zeal to attend religious meetings,
which are set apart for the worship of Almighty God,
and at length become so darkened in their imaginations
as to mix in marriage with those of other societies,
and become disunited from the body.
These I apprehend to be the reasons why, in this and several parts of my native country,
we are so much decreased and degenerated.
Greatly therefore does it behoove us, who are parents of children,
to bring them up in the fear of the Lord,
and have a constant watch over them for their good,
endeavouring to draw the mind into an inward
search after those things which are heavenly,
durable, and fade not away!

At Carlisle we received several letters from our dear friends and relations,
and though they gave us the comfortable account of their welfare,
yet the sorrowful news of the mobs rising in our city, breaking windows,
unroofing houses, and setting them on fire,
destroying and throwing into the river flour and meal in very large quantities,
and a great deal more damage, affected us.
The accounts informed us of many of the inhabitants assembling together, who, by force,
got the mob under; that several of them were taken into custody,
who afterwards were tried, and many were condemned, and some hanged.

From Carlisle we went to Moorhouse, Scotby, and Sikeside,
where we were kindly received and entertained by our friend William Graham and wife.
We had a large meeting with them the next day:
I was opened on the recommendation of the apostle to the Philippians,
"`Whereunto we have already attained, let us walk by the same rule,
let us mind the same thing:`" Truth favoured, and we had a glorious meeting,
praised be His name who gives the increase.
Sixth-day, went to Carlisle Monthly Meeting, which was very large,
and I hope that such as feared and worshipped the Great Name were profited thereby.

Seventh-day, a small meeting at Kirkbride,
in which the ownings of Divine power were experienced to our consolation;
the same evening went forward to Wigton; and the next day, being first-day,
had two meetings with them: the state of their meeting seemed low, nevertheless,
I was favoured to have open service amongst them.
Second-day, at Bolton,
where we laboured honestly according to our measures for their good,
and the same evening had a meeting at Holme, which was large and well,
the truths of the Gospel being preached in the power of God.
Third-day, at Allonby, and the next day a meeting at Broughton, which was large,
but not so much to satisfaction as I could have desired.
Lodged at Isaac Hall's, whose wife had an acceptable gift in the ministry,
and was concerned to visit the churches in America, which, when she had nearly finished,
was taken very unwell, and though no outward helps were lacking to restore her,
yet in vain; she quietly and willingly resigned her life to Him who gave it,
and doubtless received the reward of her labours.
I saw several good accounts of her, all concurring in her acceptable service.

Fifth-day, had a meeting at Cockermouth.
Jonathan Wilkinson's wife being very ill and confined to her chamber,
we had a sitting by her bedside, and though my mind was much cast down,
yet was comforted with this opportunity: Hannah Harris was also with us.
These two good women found themselves concerned
to pay a religious visit to Friends in America,
in which undertaking they were most affectionately united, and preserved in the sweet,
heavenly, precious fellowship, in which they became true yoke-fellows and companions;
I heard much in commendation of them, and of their labours and services in those parts.

First-day was at Pardshaw, which I believe is by far the largest meeting in Cumberland.
It was a good meeting, though many things were spoken to in a very close manner.
Some matters of difference had got in, as we afterwards understood,
by which some have received hurt: may Truth so operate in their hearts,
as to bring about a reconciliation,
and restore the desirable blessings of love and peace,
is what I wish for them in great sincerity.

Next day we called on a poor widow and her daughter who live together; we asked,
while on horseback, if she could with conveniency take us in,
for we had been told her circumstances were narrow,
and could not tell what kind of a reception we might meet with.
But I do not remember where, in the course of all my travels,
I have been more kindly received than by this good woman, widow Wilson,
and her dutiful daughter, who cheerfully set before us the best she had in her house.
While we sat at meat,
my heart was so filled with the sweetness and
love of God as to break forth into supplication,
beseeching that the Divine blessing might attend the present occasion,
and that the handful of meal which was in the barrel should not waste,
nor the cruise of oil fail; so was my soul poured forth to the Lord,
that his blessing might be upon these,
who out of their little gave freely to the Lord's servants,
who in love were sent to visit them.

Fifth-day, had a meeting at Penrith, which was the last in Cumberland.
There are in this county, which we visited pretty thoroughly and to our satisfaction,
many meeting-houses and a great many Friends, who I hope rather increase than otherwise,
and who love and live in the principles of which they are making profession.
From there we proceeded to Strickland and Kendal, in Westmoreland,
and on third-day had a meeting at Settle, wherein Truth arose into great power,
and a heavenly time it was, the remembrance of which is sweet to my mind at this season!
Here were two Friends engaged in visiting families by order of their Monthly Meeting,
who requested our company, which we granted to their and our satisfaction.
Next day we went to Skipton, then by Bradford to Leeds,
and attended their meetings on first-day,
which the Lord in infinite goodness was graciously pleased to own, and filled our cups,
so that they ran over, and his heritage was watered,
to his praise and the consolation of his people, who, says my soul,
is worthy and blessed forever!

The weight of the concern which had long exercised my
mind on account of the visit I have already performed,
now wearing off, I found it my place to come pretty directly home,
taking meetings as they fell in my way, and was met by my dear wife and son-in-law Cook,
at Wymondham, where we had a large meeting, to edification.
The same evening returned home to my habitation at Norwich, the 27th of eleventh month,
1766, witnessing in my measure the verity of the saying of the royal Psalmist,
"`He that goes forth weeping, bearing precious seed,
shall doubtless come again with rejoicing, bringing his sheaves with him!`"

1767+++.+++ In this year, my dear uncle Edmund Peckover resigned his life to Him that gave it;
by whose removal the church has sustained no small loss,
though to him undoubtedly it is great gain.
The Monthly Meeting to which he belonged thought his memory worthy of some testimonial,
and as my esteem was very great for him, not only as a near relation,
but a father in Christian experience, I have thought fit to subjoin it.

A Testimony from Wells Monthly Meeting in Norfolk,
concerning our ancient and eminent friend, Edmund Peckover, deceased.

He was born at Fakenham in this county in the year 1695,
and was the son of Joseph and Catherine Peckover,
both persons of eminent worth and estimation in the Society.
It appears by a short manuscript under his own hand,
that he once had thoughts of leaving some
account of his Christian experiences behind him,
and made a beginning towards it; but whether he pursued his intention, or was prevented,
we cannot ascertain,
nothing further having been found amongst his papers in pursuance thereof.
The fragment he has left is after this manner.

"`The tender dealings of the Almighty with me in
my youth being often fresh in my remembrance,
brings a most grateful sense thereof over my mind,
under which I cannot but commemorate the same with reverence.
It was no small advantage to me that I was favoured with religious and godly parents,
whose concern and care,
to bring me up and the rest of their children in the nurture and admonition of the Lord,
was great.
And what I look upon as very remarkable is,
that before I arrived at an age capable to retain those good and wholesome admonitions,
which in the wisdom of God they often communicated to me,
I felt the good hand of the Lord at work in me,
in a manner suitable to my tender capacity,
impressing upon my heart a living sense of his greatness and goodness,
which often brought me under much awfulness and fear,
dreading to do anything that I knew was not well pleasing in his sight:
herein I could distinguish that I had peace and satisfaction,
and met with encouragement in myself beyond what I am able to express.
And when I have been drawn into anything which tended to
hinder my growth in that which I found to my soul's advantage,
sorrow and trouble took hold of me;
under a sense whereof I often made vows and promises
that I would never join with the like again,
which being my first fruits before the Lord, I believe he had a tender regard to,
and often assisted me to perform those covenants,
which through some good measure of Divine influence I then entered into.
In the time of this exercise, great and many were the conflicts I had to encounter; but,
to the praise of his great name I speak it, his compassionate, fatherly care was over me,
and always attended me with such a portion of his Divine and saving grace,
that I knew preservation thereby through things of the most trying and pinching nature:
in the experience whereof thankfulness would arise.`"

As he was thus early visited, so, through faithfulness to the Divine manifestations,
he was early anointed and sent forth to preach the Gospel, even in his minority,
either while under education at the school of that ancient and honourable Friend,
Gilbert Thompson, or very soon after he left it; as near as we can gather,
his mouth was opened in public testimony about the year 1711,
and in the fifteenth of his age.
Through Divine favour, as he abode in faithfulness,
he grew in the Truth and increased in his gift, which was very acceptable.

He entered upon his first journey in the service of Truth with Edward Upsher,
in the year 1714, being the eighteenth of his age,
and visited Friends in several adjacent counties.
In 1716, he accompanied George Gibson through Ireland:
he visited Friends in that kingdom again in 1726;
travelled most parts of this nation many times over, and twice into Scotland;
and in the year 1742,
a concern having long and weightily been upon him to
pay a religious visit to Friends in America,
he went over in company with our friends John Haslam and Michael Lightfoot,
who was then upon his return to Philadelphia.

Having discharged that duty to the edification
and great satisfaction of the churches there,
as appears by their certificates,
the Lord was pleased in 1744 to restore him again in safety to his native land,
with the rich reward of peace in his bosom.
In 1753, he made his third visit to Friends in Ireland, and continued afterwards,
as he found it his concern, to travel in various parts of this nation,
was a constant attender of the Yearly Meeting in London,
and at many other opportunities paid very acceptable visits to that city.

In the exercise of his gift, he was frequently opened and enlarged in Divine counsel,
in delivery was manly and distinct, his doctrine sound and flowing,
and his spirit lively and powerful.
He appeared at times as a cloud filled with celestial rain,
to the reviving and refreshment of the living heritage of God,
zealous for the prosperity of the church, and for the gathering of all.
He spared not to spend himself in the strength of his days,
and Almighty goodness was pleased to preserve him a strong man
and an able minister for a long course of years.
He usually delivered himself with great fervency;
and often in the flowing forth of Divine love upon his spirit,
he was raised to sing the song of Zion in a melodious manner.
While favoured with ability,
he was constant and particularly careful in giving due attendance to meetings,
and very serviceable on occasions of marriages and burials.

He was exemplary in life, unstained in character,
assiduous to preserve discipline and order in the church,
and that love and unity might be maintained and increased; painful in travail,
laborious in word and doctrine, an elder worthy of double honour,
to whom we cordially gave it.

The deep impressions that remain on many of our spirits
in the grateful remembrance of his labours of love,
which through Divine assistance he was enabled to bestow upon us,
we hope will be lasting engagements to us to preserve a
just and affectionate regard to his memory.
His doctrine was often wonderfully suited to the states of those to whom he ministered,
and the holy unction which accompanied it effectual,
melting the hearts both of Friends and others.

We have cause to believe that in many distant and different parts,
as well as in his own neighbourhood,
a number are still in being who are as seals to the truth and power of his ministry,
to whose convincement he was made instrumental, or to whose growth he was helpful.

It pleased the Lord,
that about three years before his decease he received a shock of a paralytic kind, which,
both in his own apprehensions and in that of his friends,
seemed to threaten him with a hasty dissolution.
Under this affecting visitation,
by the account of a relation who visited him the same evening,
he was graciously preserved in a broken, tender, living frame,
and expressed himself after this manner:--That
he had now the satisfaction of a good conscience,
and of having discharged himself in the duty required of him,
according to the ability afforded him,
declaring at the same time the great consolation he inwardly enjoyed.
The next morning, after a short sleep, and taking some little refreshment,
he was somewhat revived, and signified,
that he was well pleased his outward affairs were settled,
and was fully satisfied with the manner in which they were ordered,
and entirely resigned to the disposal of an all-wise Providence,
whether it might be to lengthen his days or to take him hence:
that he felt a blessed assurance, and found the Lord,
who had been his support in many trials from his youth to his advanced years,
still to be near him, and could experimentally say his Redeemer lived,
who had ever been the strength of his faithful people,
and had brought to pass many things in his pilgrimage,
which to outward appearance seemed very unlikely.
After this, he lay in a sweet quiet frame of mind,
and his pain lessening he appeared pretty cheerful,
and in time he became so far restored as to be able to appear abroad in a carriage,
but with considerable difficulty to himself.

And though in common conversation his apprehension and memory seemed much impaired,
yet his public appearances in meeting continued sound, consistent and savoury.
A few months before his death he was rendered totally unable to attend meetings,
and continued gradually to decline; and the gracious Lord,
who had been his strength and stay in the prime of his life,
supported him in his last moments.
He appeared to be favoured with a comfortable foretaste of
that glorious immortality which is prepared for the righteous.
For though he was deprived of bodily strength to speak so distinctly as usual,
yet he was sufficiently understood to intimate
the inexpressible joy and felicity he felt,
and seemed to pass away as with a heavenly song of Divine praise in his mouth.
He departed this life at Wells, the 19th of seventh month, 1767,
and his remains were buried at Fakenham the 22nd,
after a large and solemn meeting of relations, friends and neighbours.
He died in the seventy-second year of his age, and the fifty-seventh of his ministry.

Signed in and on behalf of our Monthly Meeting held at Wells, the 4th of fifth month,
1768, by many Friends.

