== Chapter VII.

In the seventh month, 1769, my wife and I took a journey to London,
principally to attend the marriage of my brother John Oxley, to Elizabeth Chorley.
The marriage was solemnized at Devonshire-house,
in a very large assembly of Friends and others,
who conducted themselves well on the occasion.
Thomas Whitehead concluded the meeting in supplication, which was to good satisfaction.

I continued my usual employment in business, keeping much at home,
except visiting neighbouring meetings as I found a concern so to do,
and going occasionally to London, but not with certificate.

Many years before my going into Scotland,
I was apprehensive that at some time it would be
required of me to take a much longer journey.
But nothing of that kind appeared to be very nigh at hand,
and I desired to wait in a state of resignedness, and not to be afraid,
and so terrify myself with apprehensions of what might be,
neither on the other hand to be forward in giving
credit to every appearance as a real concern.
To live in reverence and fear before the Lord, and walk circumspectly before men,
seemed the present requirement and way of duty.
Having a very pleasant habitation in a good city,
an affectionate wife and comfortable children, made my home very desirable,
also other near connections and beloved friends,
with whom I lived in great love and unity, as behooves children of our heavenly Father,
a blessing I desire to be preserved in,
and that the same may preside throughout the whole flock and family everywhere.
But in the year 1769, I found my mind so closely beset with the concern I was under,
as not to be able to keep altogether silent, and having some intelligence given me,
that it was thought Samuel Neale of Ireland, one whom I knew and had good unity with,
had somewhat on his mind of the like kind,
and finding my concern to increase and grow stronger, it was upon me to write him,
which I did as follows:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Norwich, 6th of Seventh month, 1769.

[.salutation]
Dear friend, Samuel Neale,

I hope you will excuse the freedom I am taking,
in communicating to you the religious concern and exercise of mind I have been under,
and which has long attended me, and yet is very weighty upon me;
in which I trust I am in part become will-less and passive in the Great Master`'s hand,
to be formed and fashioned as it seems best to his good pleasure;--a concern,
my dear Friend, to go over the great and mighty waters.
I have had some intimation as if you had something of a similar concern.
If it should be so, and my lot be cast with you, if only over the great deep,
I hope my mind would be reverently bowed in thankfulness to the Father of mercies,
in whose hands are our lives and preservation,
for affording so favourable an opportunity.
I would not be thought to force myself on you, or to oppress you in any respect,
by no means; only to express how much I love you,
and the unity I have with you in the Lord`'s service.

Now, my dear friend, although I have been so communicative,
I desire and expect you will keep it to yourself,
especially if it is not likely we should be companions.
I hope hitherto it has been my care not to move too hastily in these important matters,
wherein is much safety,
and here I desire to abide according to the present feeling of my mind.
If I live and am well, I should like to see another year or Yearly Meeting,
and shall hope and expect to receive a few lines from
you in the same freedom as I have written these,
or else shall conclude you have not unity with me in my concern; and if it should be so,
I should not much wonder at it, for verily, to write the truth,
I am far from liking it myself, and if I dared,
I would say I think my Master has made choice of a very poor, mean,
contemptible creature;--but I dare not say further, for he knows what is best,
to whom I recommend each of us for protection, and remain in unspeakable love,
your friend and brother in the unchangeable Truth,

[.signed-section-signature]
Joseph Oxley.

--

After having so done, my mind was made quite easy.
My wife having a journey before her in the west, during her absence,
I was as if no concern had ever been,
and it fared with me as though it would quite wear off.
Somewhat more than a month afterwards I received a letter in answer to mine, as follows:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Glanmire, 2nd of Eighth month, 1769.

[.salutation]
My dearly beloved and esteemed friend, Joseph Oxley,

I received your letter in course on the 6th of last month,
which was very unexpected both as to the subject and the letter;
and however some have circulated an intimation of my having any
drawings to visit the churches on the continent of America,
it has never of late years transpired from me,
except when I have been asked the question;
silence or perhaps an evasive answer may have formed suggestions in their minds,
which they have without my approbation privately circulated.
And this has been the cause of this report.
I consider myself, dear friend, as one of the weakest of the family.
I must acknowledge the sound of America has often
pierced my ear for twelve or thirteen years past.
It has often opened and shut, sometimes quite disappeared, and that for many months,
then again moved and stirred more feelingly in my mind,
and I cannot say but of late more than usual.
How it may be, I cannot say: I am ready to be commanded, I think,
though in my own apprehension one of the weakest and poorest
of the household to be appointed to an embassy so important,
so distant, and so weighty.
As to the requiring, time will ripen,
and may the fruit be never parted from the tree until ripe,
that it may have its proper flavour amongst those who have distinguishing palates.
As to you, dear friend, and your concern, I have no right to doubt.
I have always had unity with you in your religious labours,
and should think it a favour to have such company over the great waters,
if Heaven should order it so.
But the concern is of such a nature, so weighty, so important,
so interesting to ourselves and the church,
that trying the fleece wet and dry I trust will not be displeasing,
and anon we may hear from each other.
Thus much I may say.
My wife knows not, nor any other member of the church as much as I have written to you,
therefore I enjoin to secrecy; as I would not betray my concern,
or waste my strength by any unripe declarations, which perhaps may wither,
or be only a trial of faith and fidelity.

Farewell,
dear friend! may the Rock be our safe hiding-place and munition in all our stoppings,
that at home and abroad, our places may be filled up with propriety,
our unity increase with our years,
and we remain immovably bent to seek the city that has foundations,
which is the humble desire of your nearly united friend,

[.signed-section-signature]
Samuel Neale.

--

After passing these two letters,
we left the result for our further weighty consideration, believing, if it were right,
it would ripen in due order of time; but if not, that it would die and dwindle away.

In this year my dear wife was under much exercise and
religious necessity to visit Friends in the west of England,
and as I believed it was of the Truth, and proceeded from a right cause,
I freely gave her up to the Master`'s use; and she having the approbation of Friends,
and the Monthly Meeting`'s certificate,
signifying their concurrence and unity with her ministry and deportment,
set forward in the ninth month.
She was accompanied by Mary Mayo,
a young woman of an innocent life and who sometimes spoke in meetings,
which being to edification was satisfactory to Friends.
They returned by way of London on the like good errand,
and came home the 13th of twelfth month, the same year, with the recompense of peace,
which is the reward of the righteous for their obedience and faithful labours.

+++[+++The following encouraging extract from a letter to his wife while at Bristol,
evinces their union of labour and earnest desire
for the promotion of the cause of Truth.]

[.embedded-content-document.letter]
--

I cannot help adding before I conclude,
that my dear wife may well weigh her concern now she is out,
and not to return while there is any oil in the pot, but wait to know the proper time.
It is possible there may be yet many more empty vessels, yet when the oil stayed,
there was a sufficiency to pay what was demanded.
The Lord in infinite wisdom guide you, instruct and counsel you by his unerring Spirit,
bless and protect you in all the various encounters both within and without,
make his work prosperous through you,
and number you with the wise who shall shine as the brightness of his firmament,
and them that turn many to righteousness as the stars forever and ever!
Consider, my dear, you are advancing in years,
and probably may not have another opportunity of the like kind,
so I hope you will be careful to discharge yourself honestly in the sight of God,
and faithfully before his people, that your latter end may be crowned with eternal peace.
From your loving husband and fellow-labourer in the Gospel of our Lord Jesus Christ,

[.signed-section-signature]
Joseph Oxley,

--

Early in the following year I received a second letter from my friend Samuel Neale,
which I think worthy of inserting, and is as follows:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Glanmire, 13th of First month, 1770.

[.salutation]
Dearly beloved friend,

Since I wrote to you, many months have elapsed.
My answer to your letter was very much in the simplicity, and as I felt at that time;
since which, in the services I have passed through and been employed in,
I have felt no abatement in my concern.
But with an increase in the springing of light
into my mind it has been always most conspicuous,
which makes me hope it is of the Lord; for the greater degree of light we have,
the clearer every thing appears;
and you know sometimes there are withdrawings to prove our faith and fidelity,
when all prospects are shaded, and we feel an entire blank.
I thought I would therefore ask you how you fare, my brother,
and how you get forward with your feelings.
In my searchings, I have thought,
if this matter of great importance must be submitted to by me,
which has been so many years upon my mind, I should think myself much favoured,
if the Lord of mercy would unite us together in this labour,
and allow me to get under your skirt, because I think with your spirit,
and temper and concern, I have great unity; the more so, the more I look at it.
But even this favour I would endeavour to relinquish,
if not perfectly conformable to the Divine will,
that I know sustains all those employed in the Lord`'s service, as submission, dedication,
and awful fear are abode in.

I have been of late two months from home; in Dublin about one,
and visited many families in company with Friends deputed on that service;
afterwards joined Friends in that province, and visited the meetings for discipline.
By hearing the queries read and answered while men and women were together,
a full opportunity was given in the openings of Truth to make some useful remarks,
and much favour was mercifully experienced in the performance of this service:
and besides this, we have visited Limerick,
Clonmel and Youghal particular meetings in their families.
Thomas Whiley, William Fennell, Joseph Grubb,
and sometimes Robert Dudley and George Peet assisted, besides your poor friend.

It has been a renewed visitation, and I think some fruit already appears.
May the great Lord of the harvest raise up and
send those who may be living members of the body,
who by keeping on the spiritual harness may make war in righteousness,
and remain in that greenness that is always acceptable to the Lord and his church,
though in their own view their services may appear very
small and of little or no consequence.
I had a letter from dear John Elliott,
giving an account that dear Rachel Wilson was arrived safe in their port,
and that her labours of love were universally acceptable in America.
My wife joins me in the tender of true affection to you and yours;
she seems passive to the Divine will,
if her husband should be called from her in this service.

[.signed-section-closing]
I remain your nearly united friend,

[.signed-section-signature]
Samuel Neale.

--

It was no small comfort to my mind to find a Friend so concerned,
and one with whom I had such close unity and sweet fellowship.
And though the trial was great and hard to submit to,
yet made somewhat easier in having the prospect of such a choice Friend for a companion.
So we kept waiting in stillness and in patience
for further discoveries of Divine counsel,
and communicated to each other according to our
feelings and growth in Christian experience.
After receiving two letters from my dear friend in Ireland,
it was incumbent on me to send him somewhat, as under.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Norwich, 1st of Second month, 1770.

[.salutation]
Esteemed friend and brother,

I have before me both your kind favours of the 2nd of eighth month, last year,
and the 13th of last month.
By the former was enabled to fathom the state of your mind respecting
that great and important business I wrote to you concerning,
and as you desired I would make it a matter of secrecy, I conformed thereto.
But before long it will be prudent to make some discovery to my dear wife and brother,
as it will be to them matter of joy and comfort,
knowing them to have sweet and precious unity with you,
and I hope that good Hand which has hitherto preserved,
will preserve you all your life long, to his praise and the good of his church.
I much approve of your steady cautious movings in the present dispensation,
and wish for myself that I may follow your example, which I will endeavour to do.

Since I last wrote what was on my mind, I have been almost ready to repent,
as for a considerable length of time every appearance
of concern in that way seemed to be withdrawn,
and I was ready to apprehend I had been altogether mistaken;
and so I remained the greater part of the time my wife was absent at Bath, Bristol, etc.
But soon after her return, things appeared with a very different face,
and now the concern is more weighty and pressing than ever, though I have long reasoned,
and contended,
and strove against the discoveries and holy manifestations of the Divine Spirit,
in this great and awfully solemn act of duty.
I have found myself overcome by a far superior power,
that is stronger than the strong man armed with every artifice of united endeavour
to baffle and obstruct the carrying on of the work of God in the soul.
All these batteries are in a good degree put to silence, and thus it is,
that in the day of the Lord`'s power his people are made a willing people.
Yet notwithstanding I am brought into a good degree of resignation to his mind and will,
I am very far from thinking myself in any degree
proportionally qualified for such service:
so trust, he is graciously pleased in condescension to my weakness,
inabilities and frailties, to send another with me, more valiant and honourable.

I lack words to express my thankfulness for the present apparent prospect;
I wish I may not be too elevated therewith,
lest something or other should be allowed to disappoint
me of so desirable a friend and brother.
I shall be waiting in expectation of being informed, as early as you can,
whether you think you shall hold yourself in
readiness against next London Yearly Meeting,
which may be some rule for my government in settling my domestic affairs, etc.
That meeting I expect is to judge of the propriety or impropriety of my concern;
and if it should be given in the negative, I should not much wonder,
considering what a poor creature I am.

If so, I hope I should in a proper, becoming manner,
acquiesce in their wise determination, and not, think amiss of my friends,
but love them the better.
If this should be my lot, I trust my dear Samuel will not let in discouragement thereat,
whose services have many times been tried, proved, and approved.
I should like to go over in a particular vessel which I have in view,
the master of which I have some acquaintance with.
But that I must leave, and all things else.
I hope the Lord will be with us from the violence of
all storms and tempests both without and within,
and enable us to speak to the praise of his great and holy name,
who is worthy forever and ever!
I much approve of the visits you have paid with your friends to Dublin, your province,
Limerick, Clonmel and Youghal,
all which places I trust will reap the good of your labours,
and your end be crowned with peace.

I perceive you have been very poorly so as to keep your chamber and even your bed;
I do not much wonder at it.
I have been as bad, or worse, scarcely able to keep my understanding perfect.
You may now judge of my feelings, and of my unity with you.
My wife joins me in very dear love to you and your dear wife,
and expecting soon to hear from you again,

[.signed-section-closing]
I remain your brother in the unchangeable Truth,

[.signed-section-signature]
Joseph Oxley.

--

Some few weeks afterwards I received another letter from him,
of his intentions of being at the ensuing Yearly Meeting at London,
and expressing his approbation of my proceeding
according to the good order established amongst us;
which I did in great fear and weakness at our following Monthly Meeting;
and Friends having unity with me in my concern,
made suitable record of my declared intention,
and deputed some Friends to draw up a certificate and
bring to the next Monthly Meeting for approbation,
which was done and recommended to the Quarterly Meeting for their approbation also.

+++[+++Samuel Neale`'s letter is as follows.]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Glanmire, 21st Second month, 1770.

[.salutation]
Endeared friend, Joseph Oxley,

A few days ago I received your acceptable letter of the 1st inst.,
in which I had the intelligence that your way cleared in your own view,
and the reasoning of the creature was silenced
by the resurrection of fresh sight and strength;
so that doubting was abated,
which is certainly the experience of the faithful in proportion as the veil is rent,
and all offered up at the altar.
Dedication and devotedness are born and brought forth through a state of suffering,
nursed as at the breasts of resignation and perseverance in what is made known as a duty.
Many things interfere in order to retard and obstruct,
but if ever we arrive at a peaceful rest we must give up all when demanded,
in order to stand approved, and then we are promised multiplied favours in this life,
and in that which is to come life everlasting.

As for my own part, I acknowledge myself abundantly obligated for the favours dispensed;
I often look upon myself as a worm, and one of the lowest order,
but why should I dispute or say, "`Send by those more strong, more experienced,
more furnished or more fervent in the war?`"
Let this language forever be silenced,
and in proportion to what is made manifest may I stand faithful, whether to do or suffer,
for it is not of him that wills or of him that runs, but God that shows mercy.
Thus, my beloved friend, I am brought into a willingness to be a spectacle to the world,
to angels, and to men, to be employed or not to be employed,
believing in that Arm that is omnipotent, that still works in the little, low,
and despised ones whom He has called from the corruptions of this delusive world,
to follow Him in the straight and narrow way;
though opposite to the visible ease or interests of this life, carnally speaking,
yet infinitely interesting and glorious in the
end! which that we may keep constantly in view,
through every trial and dispensation, is the fervent desire of my soul!

I thought it needful to write you without delay, in order that you might be preparing,
as the time will quickly come about when it will be needful to consider our friends.
I have ventured to speak to a few, and am setting my affairs in order,
to be capable to leave home with as much ease to myself and reputation,
as the importance and nature of the journey, if prosecuted, demands: which I look upon,
as if going to be separated from all things here below.
It is usual for us in this land to lay our concern
before our Province and National Meetings:
the meeting I expect to consult will be in about nine weeks,
our National Meeting falls soon after,
and whether I shall be able to get to the Yearly Meeting at London, I cannot yet say,
but shall endeavour to be ready about that time or soon after,
if I am sustained with faith and strength.
The fellowship of your spirit and the prospect
of your company I look upon as a great favour,
as I shall look upon you as a father, a friend, and counsellor.
As to your submitting to the judgment of your friends,
though opposite to your own feelings, I know you so well I have no doubt of that;
but I believe you will not escape so,
it would be an easy method of laying down our burdens;
and really if my friends should be of a contrary judgment to my feelings,
I think I would acquiesce without a censure or the least murmur in my heart.
The unity of my brethren is the cordial of my life, next to Divine favour,
and I hope I shall never outlive the unity of the faithful,
as I should be a burden to myself and mankind.

Present my dear love to your dear partner, and brother John,
whose sympathy with you will be a strength I doubt not.
I remain your nearly united friend and brother,

[.signed-section-signature]
Samuel Neale.

--

In the third and fourth months of this year were removed from us by death,
John and Samuel Gurney, of this city, sons of our worthy and honourable deceased friends,
Joseph and Hannah Gurney.
These two sons were valuable members of our Society, great and good men,
adorned with many excellent qualifications, both natural and acquired.
They were considerable merchants, and obtained much wealth in an honourable traffic,
and their just and upright dealings gained them great reputation, love and esteem,
where they were connected.
As they were blessed with affluence,
so they took pleasure in communicating to those that stood in need.
Their hearts were opened to do good,
as also were their houses for the accommodation of their friends, etc.
Free and generous in their sentiments,
being filled with love and charity to all religious professions,
they were particularly serviceable in arbitrations and settling of differences,
on which account they had many solicitations, not only by those of our own,
but other societies.
They were well acquainted with the order and discipline of the church,
and on them fell a considerable share in the active part, especially the former;
the latter for many years being rendered incapable of attending,
through long weakness and many infirmities,
which he bore with great patience and Christian fortitude.
John was chosen sundry times clerk to the Yearly Meeting of London,
of which he was a diligent attender,
and discharged himself in that office to general satisfaction.
They were lovers of peace, and peace-makers, and such, said our blessed Lord,
shall be called the children of God.
They left behind them their loving affectionate widows, with beloved children,
who deservedly mourn their unspeakable loss.

I received another letter from my dear friend, Samuel Neale, dated 14th of fifth month,
the substance of which is as follows:

[.embedded-content-document.letter]
--

"`I for some time thought I should have met you at London,
and there have consulted with you how and when to proceed.
I was fully and freely given up to the Lord`'s disposing hand which way to turn,
but as the time drew near, I felt a stop and gloom between me and that movement,
and rather a draft of mind to go from my own country;
some yet unsealed reasons may be the cause of this change,
but from my own small experience, it is the sure way of moving,
in the freedom and liberty which Truth gives.`"

--

I now found myself under great difficulty how to proceed,
and sought with great earnestness,
that all-wise Providence would direct me the right way,
and that I might not show myself unstable and unsettled,
and that my trust might be in the Lord, and not in another.
The Yearly Meeting drawing on, I found it my duty to proceed in regular order,
as I had hitherto done,
and not to look back at anything that might seem to tend to discouragement.
The time being now come, in awful reverence and holy fear,
I laid my concern before the Yearly Meeting of ministers and elders in London.
After a weighty pause and deliberate consideration,
and reading over my certificates from Norwich, a minute was made,
and some Friends chosen to draw up a certificate for the meeting`'s approbation,
which was done and is as follows:

[.embedded-content-document.epistle]
--

[.blurb]
=== From our Yearly Meeting of ministers and elders, held in London, by adjournments from the 2nd of sixth month, to the 11th of the same inclusive, 1770. To Friends and brethren in America.

[.salutation]
Dear friends.

Our esteemed friend, Joseph Oxley,
having in a weighty manner signified unto us the concern which has
rested on his mind for several years to pay you a religious visit,
and produced certificates on that account from the Monthly Meeting of Norwich,
the place of his residence, and from the Quarterly Meeting of Norfolk,
which were read in this meeting to our satisfaction.
We think it needful to certify our concurrence therein,
having good unity with our said friend as a minister,
and also with his present engagement;
fervently desiring his preservation by sea and land,
to the accomplishment of his service amongst you, to your help, comfort, and edification,
and that he may be favoured to return in due time to his
family and friends here with the reward of solid peace,
we remain, with the salutation of brotherly love, your affectionate friends.

[.signed-section-signature]
Signed in and on behalf of our said meeting, by many Friends.

--

These testimonials from Monthly, Quarterly, and Yearly Meetings,
greatly increased my care and concern,
lest I should not be able to answer what they set forth.
It therefore behooved me to be particularly watchful over my conduct everywhere,
lest unguardedly I should fall into some hidden snare or other,
that might be laid to draw my feet from the paths of stability and prudence,
and so fall short of what was required of me.
I greatly admired, esteemed and loved the precious unity of my friends and brethren,
which I had mercifully witnessed in times past,
to my comfort and strength in my steppings along,
in the various dispensations of Divine Providence, in whose power, above all,
I had confidence, and in whom I put my trust.
May my trust and confidence be in Him, more and more,
in this warfare in which I am now about to engage, that I may have to say,
with the Psalmist, "`The Lord lives and blessed be my Rock,
and let the God of my salvation be exalted!`"

The next thing that came under consideration was the way of my going,
whether to Cork and so fall in with my dear friend Samuel Neale,
that we might accompany each other over the great waters, or go from the port of London.
This matter took up much of my attention, and I was afraid lest I should be misled.
There was at this time a good vessel lying in the river Thames, the owner a Friend,
and the captain educated in our profession, and a friendly, kind man;
the second mate was also a Friend.
She was bound for New York.
I was invited to go on board her with my brother John Oxley, and other Friends,
where we were kindly entertained.

The ship`'s name was the Duchess of Gordon, Isaac Lasels Winn, commander,
and an expert sailor; there seemed very good accommodation for passengers.
While I was on board, I felt myself every way easy and comfortable,
and so did my brother and others for me.
In this state of mind I continued peaceful and easy, and greater freedom to go this way,
than by the way of Cork, and ordered myself accordingly; and when I returned from London,
I wrote to my friend, Samuel Neale, as follows:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Norwich. 14th of Sixth month, 1770.

[.salutation]
Esteemed friend, Samuel Neale,

I have before me your kind favour of the 14th of last month,
which I have read over and over again,
and shall reply according to the feeling and freedom of my mind.
I perceive you have got the free liberty and consent,
both of your own Monthly and National Meeting, which as you were pleased to say of me,
I had not the least doubt you would obtain, and fresh strength be renewedly experienced.
I understood by Friends of your country,
it was a time of Divine favour remarkably extended,
to your mutual comfort and edification.
I placed great consolation in expectation of your coming to London,
and great has been my disappointment in not seeing you there.
But as we are freely and willingly given up to do as the Great Master would have us,
so he will order and direct us in best wisdom,
whose ways are far beyond our conception and past finding out.
I should esteemed it a favour to attend you, unto whom I own I have greatly leaned,
and whom I love with great affection, perhaps too much so.
Probably R. D., or some other good Friend from Ireland, will inform you,
with what feebleness and diffidence I laid my concern
before the meeting of ministers and elders in London,
yet without any altercation they appointed a certificate to be drawn up,
which is far beyond what I expected.
I have so far attended to the way that has been opened, and found peace therein;
and since, you have informed me of your resolution not to come to London,
but to go from Cork, I am concerned in like manner to seek for instruction and counsel,
which I have endeavoured to do according to the best of my understanding;
and as here is a fine large good ship, said to be the best in the river Thames,
expected to sail in a month from this time at the latest,
I feel my mind most easy to accept this opportunity, which my wife, brother,
and children, etc. well approve, and trust in the Lord for preservation and strength.
"`In all your ways,`" says the Psalmist, "`acknowledge him,
and he will direct your paths.`"

As I have no view to serve myself, nor interests of any kind whatsoever,
but purely to be found in the discharge of my duty to my Maker,
so I rely on the multitude of his mercies, that he will preserve me;
and though it may please him to take away my natural life by sea or otherwise, yet,
as it is in his cause, I trust I shall be saved with an everlasting salvation.
And in this faith I embark in this great work and weighty service.
I gratefully acknowledge your love and tender offers of kindness and respect,
if I had come to Cork, in furnishing me with the necessary accommodations for the voyage,
which I sensibly feel arises from a spring of natural and spiritual affection,
in true Gospel fellowship.
May Divine Wisdom direct us, and we submit ourselves to be directed by Him,
that the hearts of the people may be opened,
and the doctrines of the Gospel received to immutable joy,
and the praise of all given to Him who is worthy thereof forever and ever!

Finally, brother, farewell!--farewell in the precious unity of the saints`' travail,
and in that love which many waters cannot quench, nor distance erase.
Should we be favoured again to see one another, I trust this love will be with us,
and if not, that it may be said of us as was said of Saul and Jonathan,
that they were lovely and pleasant in their lives, and in their death were not divided.
My dear wife and brother join me in dear love to you and your dear wife,
and such as may inquire after your affectionate friend,

[.signed-section-signature]
Joseph Oxley.

--
