== Chapter VIII.

After making visits to my relations and friends in country and town,
and receiving many who through kindness came to see me, with whom I had good unity,
we parted in much love and contrition of soul;
and taking leave of my dear wife and affectionate children,
which at parting was very trying, on the 13th of seventh month, 1770,
I set forward to London.
On first-day morning, was at Gracechurch-street meeting,
and in the afternoon at Devonshire-house; at the latter I was silent,
but they were both good meetings to me.

I continued visiting meetings in and about London till the 28th,
when I was ordered down to Gravesend,
and was accompanied by many Friends whom I loved in that which changes not.
The next day the captain giving us to understand that the pilot did
not weigh anchor till two or three o'clock in the afternoon,
we held a meeting together before we parted, to our mutual comfort and edification,
and after dinner was over, a signal was given for the passengers to go on board;
so we embraced one another in much brokenness of spirit,
and in love unfeigned took our leave and parted,
but not without scattering tears plentifully on both sides.
On Fourth-day we anchored off Spithead, and going on shore at Portsmouth,
I made inquiry concerning Friends,
but could find only one small family that resided at Gosport,
who entertained me very kindly till seventh-day.
On first-day, I retired pretty much to my own apartment,
meditating on the mercy and goodness of the Lord;
for though he had separated me from my nearest and dearest connections,
yet I experienced his living presence to be with me on the wide ocean.

+++[+++The following is an extract from a letter he wrote to his wife while on the voyage.]

[.embedded-content-document.letter]
--

"`I received your letter of the 27th of seventh month, at Portsmouth,
but being called to go on board immediately, had not time to answer it,
nor scarcely to read it; since which, I have perused it with a good deal of attention,
as also your former one of the 18th, which I have before acknowledged the receipt of,
and which continues to be sweet in my remembrance,
being living testimonies of a tender and affectionate wife, mother and friend,
and seals of approbation, union and concord in the present dispensation and separation,
for which the love of God only could sufficiently compensate.

Oh! how is the mind at such times weaned and redeemed from all other delights,
though never so nearly connected: strange to the nominal professor,
and understood only by those whose dwellings are in the light!
My son Joseph's letter of the 26th of seventh month, and daughter Kitty's,
were as marrow to my bones, and bring them sweetly to my remembrance at this time,
causing thankfulness in my mind for the present visitation wherewith they are visited,
and am bound in prayer for them to the Fountain of inexhaustible goodness,
that they may so run as to endure to the end,
and at length be saved with an everlasting salvation.`"

--

Our cabin passengers were many, chiefly military officers,
who carried themselves very respectfully towards me, which I esteemed no small favour.
Third-day we made very little way, had a calm sea, and a calm mind,
except some concern I was under about having meetings on first and fifth-days,
and consulted with the captain, J. A., and T. B.,
who were professors and approved the same.
It fell to the captain to propose it to the company,
by way of requesting a favour for me and my friends to hold meetings,
and to have the privilege of the cabin at such times unmolested;
this was pretty cordially complied with on first-days, which I thought a favour,
and gaining a great point, as many of them were topping men and topping spirits,
and giving up the cabin for such services was depriving those
of the use of it who did not choose to meet with us.
We were in number, cabin and steerage passengers, twenty-six;
and we found it necessary to form ourselves into an assembly, and meet from time to time,
as occasion required.
We accordingly made rules,
and established orders amongst ourselves for future regulation;
and one of the first concerns which came before us,
was the due observance of the first-day of the week,
concerning which the assembly came to this result, namely.
That the first-day of every week shall be set apart,
as far as is consistent with the exigencies of our present situation,
for the performance of religious worship;
and whereas men differ in their opinions as to the modes of religious worship,
that every one may enjoy liberty of conscience,
and have an opportunity of performing his religious service according to the mode
and opinion of the particular church or people of which he or she is a member,
the state cabin shall be cleared of all encumbrances whatsoever by
ten o'clock in the forenoon of every first-day of the week,
commonly called sunday, for the conveniency of the people called Quakers,
and such others as shall choose to assemble with them for about the space of two hours;
and further, that on every fifth-day, from the hours of eleven to one,
be set apart for religious worship.
We continued our meetings on first and fifth-days without any material inconvenience,
except sometimes the weather being very boisterous so as to prevent.
There were six who made profession with us,
but several others of the passengers attended our meetings, and behaved orderly and well.
I endeavoured to walk before them prudently and conduct myself wisely,
avoiding as much as possible giving any just occasion of offence,
and in so doing I gained their esteem and respect, and the advice I had to give,
whether public or private, was generally well received.

There was also a German Lutheran preacher on board, a steady well-behaved man,
and others professing the Lutheran religion, they also had their meetings,
and ofttimes would attend ours.
There were, at the fore part of our passage, many disorders amongst us;
but by good management they were brought under proper decorum,
and considering we were so large a company,
differing so widely in our several professions and callings,
the time passed away more agreeably than I first expected.

Eighth month 21st, about half-seas over, met with a sail, which we spoke;
she was a French ship from Martinico, for Bordeaux, laden with sugars, etc.
Some of our passengers went on board her, and presented them with a pig,
of which we had many, a Cheshire cheese, two or three dozen of ale and porter,
and in return they sent us French claret and rum;
after these exchanges and passing marks of respect, we parted.

Some days before this, we saw two or three whales,
which afresh struck me with awful wonder of that great Power by which they were created.
I now looked on myself as having turned my back on Europe,
and weaned from that part of the world,
and found an increasing attraction to dear America,
for whose inhabitants my soul breathes peace;
and the Lord has commanded it to be preached to all nations,
in which service I am given up according to my small measure,
living in faith that he who was formerly all in
all to those who went on the like good cause,
will in mercy vouchsafe to preserve my mind,
and give proportionable strength to every service he may be pleased to call unto.

Johann Christopher Kunze, the German preacher,
had repeatedly requested that I would write something in his book,
and after deliberately considering thereon, I had freedom to write as follows:

[.embedded-content-document.letter]
--

[.salutation]
Esteemed friend.

As you desired I would write a few lines in your book,
I have freedom to insert the judgment of the apostle respecting religion, who says,
"`In Christ Jesus circumcision avails nothing, nor uncircumcision, but a new creature;
and as many as walk after this rule, peace be on them and mercy,
and upon the Israel of God.`"
Let us preach this Gospel with power, to the end that our hearers may believe,
and walk by the same rule, and mind the same thing.
I am much pleased with your and our friends' company,
Frederick Augustus and Henry Muhlenberg, brothers and professors with you in religion;
and am thankful in my measure that the Lord has been pleased
to be with us in our little gatherings on the wide ocean.
May his everlasting arm of Divine strength surround you,
and protect and bless you in every good word and work,
is the fervent prayer of your affectionate friend,

[.signed-section-signature]
Joseph Oxley.

--

On the 20th of ninth month we made soundings, supposed to be abreast Block Island,
the next day we saw Long Island, and the day following we came up to New York,
in good health, just eight weeks from London.
Besides having one of the best vessels to come over in,
we had also one of the kindest captains,
whose endeavours were to oblige to the utmost of his abilities.
When I landed at New York, there were many Friends waiting to receive me:
my mind was made humbly thankful to the Lord,
for his mercy in preserving me every way in the course of this passage;
may I never be forgetful of him.

On first-day I was at both their meetings, which were pretty large,
and mercifully favoured with the ownings of divine love.
New York River is as broad as the river Thames, very pleasant,
on one side is Long Island, and on the other side rising hills,
forming a beautiful landscape.
The city itself is large and has many stately buildings, decollations, etc.,
a considerable place of merchandise, and very improving.
Second-day set forward for Philadelphia, accompanied by my kind friend Samuel Bowne.
We crossed Hudson's River, about a mile and a half over, to Powles Hook, so to Newark,
Elizabethtown, and Rahway, at which place we lodged at Joseph Shotwell's,
who with his wife were gone to the Yearly Meeting at Philadelphia.
Third-day to Philadelphia, which is ninety miles from New York.
I was received in much kindness and affection by my much esteemed friend John Pemberton,
at whose house I quartered,
being one whom I had seen in Old England with our dear friend John Churchman,
who made us a very acceptable visit in a religious capacity.

It was now the time of the sitting of their
Yearly Meeting for Pennsylvania and the Jerseys,
which was a very large and solemn gathering, such as I had not seen before,
so consistent in appearance of dress, and uniformity throughout,
agreeably to our holy profession, as greatly affected my mind;
and my tongue was loosened to speak of the love I was made
comfortably to partake of in this the latter part of their feast,
which they acknowledged had been throughout to mutual comfort and edification.
The meeting continued two days after my coming,
and concluded in solemn prayer and thanksgiving and praise to
Him who opens wide his hand and had filled with his blessing,
who is ever worthy!

I stayed some few days in the city, visiting Friends in their families,
by whom I was kindly received, and amongst whom I had some comfortable sittings.
My companion, Samuel Neale, not being yet arrived, I went a little out into the country,
and on third-day, the 2nd of tenth month, had a meeting at Frankford.
The morning was very rainy, and my kind friend Israel Pemberton,
sent up his coach to carry me to the said meeting, but I had not freedom to accept of it,
for example sake.
Samuel Emlen and John Pemberton attended me: the meeting was small but comfortable;
after meeting dined at Abel James's,
whose wife is the daughter of that eminent worthy Thomas Chalkley;
she is a reputable Friend, and has a family of promising children:
returned the same evening to the city.

[.embedded-content-document.letter]
--

[.letter-heading]
Joseph Oxley to John Oxley.

[.signed-section-context-open]
Philadelphia, 8th of Tenth month, 1770.

[.salutation]
Dear and well-beloved brother,

I wrote my dear wife at my landing at New York,
on the 30th of last month, or thereabout, and from there passing to Philadelphia,
partook of the closing sittings of their Yearly Meeting,
which was much to my satisfaction, edification and comfort.
The meetings were very large, more so than any I have seen in England,
both for worship and discipline;
the affairs of the church carried on in much brotherly love and condescension,
a very great deal of becoming plainness and honest
simplicity being coupled together in the fear of God,
united me much nearer to them than I expected:
their meetings for discipline not less lively than those for worship.
I had the pleasure of seeing many worthies whom I had formerly seen in Old England,
which was not a little pleasing in many respects: Esther White, John Churchman,
William Brown, Mordecai Yarnall, Elizabeth Hudson, (now Morris,) Joseph White,
William Home, George Mason, Thomas Goodwin, and others.
I have been to all their meetings in the city, and a few in the country,
am setting forward tomorrow to take about two
weeks meetings in this province of Pennsylvania,
and then go off southerly to Carolina, which it is supposed will take up six months.
Samuel Neale is not yet arrived; I am attended by my worthy landlord John Pemberton,
whose kindness is manifest in many respects,
and to such a degree as I know not how to express: Samuel Emlen is also in our company.

Last fourth-day I was at a meeting at Frankford,
after which went to the house formerly dear Thomas Chalkley's, whose daughter,
the wife of Abel James now in London, is of good report,
and entertained us in a kind and affectionate manner.
The next day had a meeting at Germantown, and dined at John Hunt's;
his wife as well as himself kind and loving.
My last gave information of a religious visit by
our friends Sarah Morris and Elizabeth Smith.
I suppose they will scarcely embark till spring.
Robert Willis also goes over on the same account, in this vessel, Captain Falkner.
She is a new vessel, on her first voyage,
and I think not inferior to Captain Winn's. I have not heard him in testimony,
so cannot speak to that.

William Hunt, another Friend in the ministry, intends to pay you a visit, I think,
from Carolina; I have not seen him, but understand he will embark shortly.
I am, through the favour of kind Providence, in good health and spirits,
my hope and confidence in the Lord, who sustains all those that put their trust in him.
Friends here are diligent to advise against and admonish all such as
appear inclinable to enter into associations or combinations,
not agreeable to our peaceable principles.
I hope this climate will agree with my constitution.
It is a fine open, clear air, and rivers and springs, hills and dales, woods and groves,
wherein are all manner of fine forest-trees, from the lowest shrub to the tallest cedar,
and fruit trees of almost every kind;
on the highways and hedges grow apricots and peaches, vines, walnuts, locust-trees,
with much more abundance than in England.
If my dear wife is yet in the land of the living, let her know,
after first giving my dear love to her in the most affectionate manner,
that her Joseph is yet alive, in health of body and peace of mind,
preaching and recommending repentance and amendment of life, with a profitable reward,
even an everlasting inheritance unto all such as are concerned thus to love and fear God.
My duty to my endeared and honourable father.

My dear brother, father, and friend, to whom I have committed all I have,
may the Almighty be pleased to bless yours and
mine in all spiritual and temporal blessings,
and enable us so to walk in all humble thankfulness, in reverence and in fear,
that our children may be his children, and our God their God.
Remember me in your nearest approaches, that my faith fail not; when you write,
advise and exhort me as best wisdom directs.

[.signed-section-closing]
In that love which changes not, I affectionately salute you,
and remain your loving brother,

[.signed-section-signature]
Joseph Oxley.

--

+++[+++After another little tour of one hundred and sixty-two miles into Chester county,
he remarks.]
The country in general is woody, except plantations which were in part cleared.
Fifth-day was at the week-day meeting at Market street, which was silent.
Sixth-day had intelligence of a vessel being arrived in the river from Cork,
on board of which was Samuel Neale, whom I much longed to see;
and set forward in company with John Pemberton and Samuel Emlen,
in order to meet him on the road, which we did about seventeen miles from the city.
When we met, we got out of our carriages, and saluted each other in much affection;
we then got into one carriage and came to town together, being much comforted,
for the love of God was with us.
I tarried in town the following first-day, was favoured to have two good open meetings,
where Truth was witnessed in a good degree to be in dominion: the evening meeting,
which is constantly held every first-day, was exceedingly large,
and to a good degree of satisfaction.

[.embedded-content-document.letter]
--

[.letter-heading]
Joseph Oxley to His Daughter, and to His Wife,

[.signed-section-context-open]
Reading, in Berks County, Pennsylvania, 19th of Tenth month, 1770.

[.salutation]
My dear Kate,

It has rather been for lack of a suitable opportunity than desire,
that I have not answered your very acceptable letter of the 26th of seventh month;
the remembrance of which at this time and at this great
distance is very comfortable to my mind.
I am, through Almighty goodness, a partaker of good health,
but how long so great a blessing may be continued is uncertain.
I therefore embrace this opportunity once more to recommend
you to that God who I trust is your father's God,
and in whom as we abide we shall do well,
and the more we put our trust in him the greater strength will
be administered to resist our enemies who assault us variously,
even if possible to slay the pure witness of God
which is revealed and made manifest in the heart.
My dear child, above all things love the Lord and his Truth, fear to offend him,
serve and obey him in every of his requirings, so will you wax valiant in fight,
and the name of the Lord will be precious in you.
I have at times to rehearse and set forth both in meeting and out of meeting,
of the blessings wherewith I am blessed:--the beloved wife and mother,
faithful in the cause of righteousness,
whose pious regard is to instruct and lead by the hand your dear father's children,
and I know you are near to her, and her life almost wrapped up in your life;
and I know your love to her is not a little.
May your love more and more increase in all spiritual blessings,
and make you together fruitful in righteousness, becoming the servants of God,
having your fruit unto holiness and your end everlasting life,--so says my soul!

I seem to have a great field of concern before me,
and I am willing to discharge myself honestly and faithfully,
as I may answer it before the Lord; in like manner do also,
whether in little or greater matters, and remember,
that the Lord will recompense you for every good word and work.
You are brought into sweet remembrance, sleeping and waking,
in meeting and out of meeting, and at times of the most awful approaches,
for the blessing of preservation and perseverance in the way of the Lord,
and above all things that his will may be done in you, whose name is glorious,
and whose goodness and mercy endure forever and ever.
Make my dear love acceptable to all near and dear relations, friends and acquaintance,
as if named, to your sister when you write, also to the poor doctor,
to whom fail not writing,
and let them know I am well and have my trust in Him that fails not.

Philadelphia, 20th of tenth month.
Yesterday morning intelligence was brought me of a vessel being arrived, from Cork,
at Newcastle, about forty miles from hence, on board of which was my dear friend,
Samuel Neale.
Samuel Emlen and myself in a chaise, John Pemberton and Thomas Fisher on horseback,
went out to meet him, and met with him about seventeen miles from this place,
which was very pleasing to us both: I hope our travelling together or separate,
will be under the government of best wisdom.
I hope you will write to me as opportunity offers,
and write freely the feelings of your mind in religious experience,
which may qualify me in making some return to further advantage.
So with my very dear love to all, I remain most affectionately your loving father,

[.signed-section-signature]
Joseph Oxley.

[.salutation]
My dearest companion and loving wife.

Though I have written several times of late to yourself, my brother, and others,
yet having a spare side,
I thought I could not do less than ask my dear wife how she does spiritually,
and if she is careful to preserve the outward weak and tender fabric,
of which I hope I shall hear in due course.
You see I have written largely to my dear Kitty of my outward and spiritual travels.
I continue in heart and mind given up to the Divine will, in life or death,
as it shall best please him; outward travels hitherto have been in woods, wilderness,
and forest, where the meetings for the most part have been large, comfortable,
and to edification,
many mothers with their infants attending:--the zeal of the mothers I
thought sufficiently compensated for the cries of the babes.
Yesterday being the first of the week, I stayed in town with my companion,
he appeared in all the meetings, morning, afternoon and evening,
very acceptably though short; he is very desirous of my accompanying him,
and I have nothing to object to it at present, so I think we shall jog off together;
he landed in very good health after a passage of eight weeks.

My dear and sweet companion and partner of my life,
and fellow-labourer in the holy exercise of Gospel travail,
I feel myself so given up in the service,
that the world and business scarce enters into thought.
Remember me most endearedly to all my nearest kindred,
from the dear wife to the least child,
and from the affectionate brother to the distant cousin,
and from the bishop to the least in that order.
I probably may not write again for some time: give me up freely, my dear, in every work,
and wherever the Lord requires,
that there may not be a returning without a proper
discharge from Him who has set his servant to work,
that if ever we meet again it may be in joy and not in sorrow.
My companion, and John Pemberton and wife, who are very kind to me,
desire their love to you.

[.signed-section-closing]
From your loving husband,

[.signed-section-signature]
Joseph Oxley.

--

The evening before, we had the company of several Indians, about twenty, who,
with many others,
were come to the city to hold a treaty with the governor on some particular occasion,
and at the same time were disposed to pay their respects to Friends,
which is not uncommon for them to do;
and many Friends met them at the house of our friend John Pemberton,
whose brother James had collected some presents of sundry kinds for them,
which he delivered, after making, or reading the following declaration:

[.embedded-content-document.address]
--

"`Brethren, we heard with love what you said to us the other day,
and it has reached our hearts.
We have great love and good will to our brethren the Indians,
and often think of the love and friendship which was
maintained between our grandfathers and their grandfathers,
and desire the same love and friendship may be continued between us and them,
and our children and their children.
We are always glad when we hear that our brethren the Indians in the woods are well,
and that they live in peace,
and are very sorry when we hear any differences happen between them and the white people.
When Onas, our first proprietor, came into this country over the great waters,
the Indians received him and our grandfathers very kindly.
It often reaches our-hearts, when we think of this.
Onas and our grandfathers loved the Great Spirit above,
who taught them to live in love and peace with the Indians,
and if we take care to love and fear the same Great Spirit,
He will keep us and our brothers the Indians in love and friendship one with another.
Brothers, we are not men concerned in the management of the affairs of government,
and therefore cannot do much to serve the Indians on that account.
But when any of them are sent down on business to the governor we are glad to see them,
and shall be willing to do them any kindness we can.
We hope what you have said to the governor will reach his heart,
and that he will do everything he can to keep up
peace between his people and all the Indians,
which will make us very glad.

"`Brothers, we should be glad that your young men, when they come down to this city,
would be advised by their old men, and not drink rum.
There are too many bad people here, who may quarrel with the Indians at those times,
and we are always sorry when we see our brothers the Indians get drunk,
it makes us ashamed.
Brothers, we have got a few small things which we give you as a token of our love,
and we wish you a safe journey home,
and desire our love to our brothers the Indians in the country.`"

--

I observed our friend James Pemberton in the course of his reading over the declaration,
that at the opening or finishing of a paragraph,
he generally presented a belt or string of wampum,
and in return the Indians gave the Yo-hah.
The Yo-hah denotes approbation.
The Indians were serious and attentive,
and after hearing what was said to them by Friends, and a silent pause among them,
a Delaware, the principal of them, expressed their satisfaction,
that they would think upon what had been said, and keep it in their hearts,
and inform their brethren the Indians, when they returned,
of the good disposition and kindness of their brethren, the white people;
and he would use his endeavours to promote love between
their brethren the English and the Indians,
and did not doubt that his relating the kind treatment
he had met with would reach their hearts.
That though he could not rule his young people, who would do as they pleased,
yet he would use his endeavours to prevail with them to keep sober and behave well.
He thankfully accepted the token of love manifested in the presents given him,
and smoked a pipe of tobacco, expressive of unity and concord,
and left the city in a good disposition.

Fifth-day, the 25th, in company with Samuel Emlen, went to Haddonfield,
about six miles over the river Delaware, a middling large meeting, and tolerably well.
Returned the same evening to town, and attended the meetings in course,
and visited many families to good content.
My companion as well as myself found our minds closely
united one to the other in Gospel fellowship;
and though some thought, if we parted for the service sake, it would be best,
it appeared to us to be our concern to continue together for the present.

+++[+++John Pemberton soon after this date thus writes to Mary Oxley:]

[.embedded-content-document.letter]
--

"`I received a letter lately from your husband, in which he says,
that he and his companion are favoured to meet with the ownings of
our heavenly Father's love both in public assemblies and in families,
much to their comfort and satisfaction.
I went to two meetings with them, and set them on their way about fifty miles,
and they appeared to me likely to be agreeable to each other both in and out of meetings,
much more so, than I was apprehensive of,
knowing the diffidence and rather backwardness of your beloved spouse.
They spent a short time in this city very agreeably,
being much united to the spirits of many here.`"

--
