== Chapter IX.

On third-day, the 30th of tenth month, we set forward on our journey southerly,
many Friends accompanying us out of the city.
Crossed the Susquehanna River, a mile over, and had a large meeting at Warrington,
but very much disturbed with little children, and the many dogs which the people brought,
as well as a frequent going in and out of meeting, both young men and young women;
a practice very unbecoming places of religious worship,
and which evidently bespeaks their great lack of spiritual concern and exercise,
to preserve them from such unseemly and unbecoming behaviour.
This is very customary in many places on this continent,
and people frequently leave their seats and come to the fires;
in this place there were two, which occasioned the meeting to be greatly interrupted,
to the sorrow and grief of the right-minded.

After meeting went to see a sick Friend, with whom we had seasonable service.
In coming from there somewhat late, and the evening dark, we lost ourselves in the woods,
but after some time got safe to our quarters.
From there went to Huntingdon; the meeting was small,
but in kindness our good Master manifested his love to the refreshment of our souls.

The next day at Monallen,
the meeting was greatly enlarged by the coming in of other professors:
the universality of the love of God was freely declared
in the demonstration of the Spirit and power,
to the comfort of many.

Passing through Pennsylvania into Maryland, we came to Pipe Creek,
where we had a small but very good meeting;
and continuing our route southerly we entered Virginia by Fairfax.
We passed over Shanandoah River up to the Blue mountains,
which abound with pines and fir trees; also many tulip-trees, commonly called poplars,
which according to the best of my observation
grow as tall and as large as our oaks in England.
The 27th we went to Jackson Allen's, where a meeting was appointed;
it was a mixed gathering, and not altogether to satisfaction.
We paid visits to families of the said meeting who had mixed
themselves in marriage with those of different principles,
and of near kindred, much to their hurt.
Fifth-day morning passed over many high mountains; it was very cold and much snow:
the country much abounds with pine trees of a very large size;
we passed over a deep river, which is often dangerous, and lodged at a public-house,
where was but middling entertainment and poor lodging.
We carried provision for ourselves and provender for our horses along with us.
This is a poor country for travellers.
Having travelled seventy miles from the last meeting, we came to John Douglass's,
where a meeting is held: here are very few under our name;
and the meeting was chiefly made up of other professors, who were many,
and on the whole it was to good satisfaction.

Had also a meeting in the family the same evening, which was a time of close exercise,
I wish it may have a tendency to their further improvement.
First-day, 2nd of twelfth month, had a meeting at Camp Creek, which was small;
I thought my companion had open service.
Second-day a meeting at Forkcreek,
at which place I was led more particularly to speak to those who kept Negros in bondage;
my companion was opened in more general service.
The evening spent at Husley Clark's, to which place came many people,
and we had a good meeting, which I desire may be had in thankful remembrance.
Lodged at said Friend's, who is an unmarried woman, sober and well inclined,
but solicited by one not in profession with us, who was then present.
I was under great exercise of mind respecting them,
and in the morning requested we might have a time of solid waiting before we parted,
which we had, and suitable advice and counsel were seasonably ministered,
which so affected them, as to make it necessary for them to break off their connection.
We then rode twenty-five miles to Beaverdam, at which place lives our kind friend,
Thomas Pleasants, where we rested two days, writing letters, etc.

Beaverdam, 7th of Twelfth month, 1770.

My dear and loving wife,

Opportunity has not yet favoured so as to receive a letter from you,
or any of my relations or friends in Old England, since my arrival in this country,
in which I have been upwards of ten weeks.
However pleasing such messengers would be, I dare not murmur,
when I consider the vast distance from Europe to America,
the few opportunities that offer, and when such advices arrive in Philadelphia,
it is very uncertain where I am, or where or how they are to be sent,
having no regular post as in England,
and much less so in the wilderness tract of country in which lie our meetings;
neither can I write with any greater certainty to you.
I am through Divine favour in good health, a blessing greatly to be prized,
and praised be the Lord for it.
But greater trials than these are, when the light of the Lord is withdrawn from those,
whose hope and trust has been in him, which state I hope ever to experience,
nor to speak murmuringly of the present dispensations,
believing all things work together for good unto all those that love and fear God.
I am often found in the exercise of my gift, but covet not to be heard for much speaking,
nor to speak much to have the praise of men.
I have bread daily, and therewith I am sustained from day to day.
My companion is hearty and strong, labours zealously in the cause of his God,
and I think is truly anointed for Gospel service,
and I am thankful for the church's sake, that he is with me.
We travel in much brotherly love and condescension,
and if we should part I believe it will be in great love and unity:
he enjoys a greater share of health than in his own country, and is a fine hearty man.
The state of the churches in the other part of the continent I am a stranger to;
but as to these parts, we find them much short of that life and zeal,
which gathers and cements into holy fellowship and desires after righteousness.

We meet but with few help-mates;
they are settled in a state of great indifference and coolness,
very trying to poor travellers.
I might say much more on this subject, but I will not permit my pen to do it.
We are now within a few days of Carolina,
where I expect we shall find the weather warmer, and hope, if I should live,
to get to Philadelphia about the third month.
My dear wife will perceive by the manner of my writing, the poverty of my spirit,
but why should I be ashamed to reveal anything to so near a companion.
I think I am right in my coming forth into this country,
and I feel the unity of my friends at home to minister
greatly to my strength in the lowest times.
My dear brother, whom I love as my own self, my children's guardian--my sister, his wife,
and their children,--may the Lord bless them and multiply his blessings to him,
who never deserted his brother in the greatest calamity,
but has sought me in times of joy and sorrow and close besetments,
both within and without.
My brother and sister Hawks, and their children,
whose growth and perseverance in the Truth I much desire,
that their and our children may be examples of moderation, both in dress and address,
that there may be no just occasion of stumbling through them.

Although, my dear, we are so far separated from one another and absent in body,
yet He that separated us is all-sufficient by His love to make up that deficiency;
and if ever I return, I hope it will be with sheaves of peace in my bosom.
Tomorrow we set forward for Cedar Creek Monthly Meeting.
Finally, as says the apostle, "`pray for us,
that the word of the Lord may have free course and be glorified,
even as it is with you.`"
The salutation of my endeared love is again unto you all, in which my companion joins,
and I remain your loving husband,

Joseph Oxley.

The 13th we forded over a river called Appomattox,
and got well to South River on sixth-day evening;
the next day was their Monthly Meeting which was small.
There are but few meetings in these parts;
many Friends came near one hundred miles from other meetings to meet us;
and we were favoured to speak to their states and conditions.
Some wrong things have crept in to their hurt,
yet a precious visitation of Divine favour had been offered to them,
and some of them were come forth in more public service.
First-day, the 16th, attended this meeting again, where many of other societies came in:
Truth was declared to the praise of God and rejoicing of his people.

We rode forty miles to John Embree's; and were ferried over Dan River into North Carolina.
The first meeting we had in this province was at Eno,
to which meeting belong many Friends, and it was in good degree to satisfaction.
Fifth-day at Centre, which was tolerable as to numbers,
but much interrupted with the cries of little children,
and unbecoming conduct as before related,
being very contrary to the nature of inward and spiritual worship.
Sixth-day rode to New Garden; took up our quarters at E. Hunt's, whose brother William,
an acceptable minister, was on his way to Europe on a religious visit to the churches.
Seventh-day was at their Monthly Meeting.
In the opening of the meeting for discipline,
a young couple proposed their intentions of marriage:
it is usual for Friends in these parts to admit those of other
societies to see the manner of our proceeding herein,
which when done they withdraw:
these opportunities draw many young people of other societies to our meetings,
whose minds are attended with too much lightness
and instability and other inconveniences,
so as to make it painful, and the disuse thereof desirable.
Third-day, the 1st of first month, 1771, was at a meeting called Mordecai's:
the house not large enough to hold the people, so held it out of doors;
and though this season of the year is so very cold in England,
it was here so warm as to make it necessary to take off some outside garments:
it was a good open meeting,
and I trust has made lasting impressions on the minds of many,
with suitable acknowledgements to the Author of all good.

Fourth-day crossed over Deep River, which was so high as almost to swim our horses,
but got safely through; also had to pass through another place called Drowning Creek:
got well through that, though it was very deep;
and breakfasted and dined that day in the woods.
We sat under a commodious pine tree, with which this country abounds;
the day was warm and pleasant.
I perceived many creeping insects, etc. which I mention only for the rarity of it,
being the 9th of the first month.
Fifth-day we had a meeting at Pedee, but few Friends, and many other professors;
they were quiet and it was a time graciously owned by the Master,
to his praise and our comfort.
Sixth-day crossed Pedee River in a ferry boat, and rode twenty miles;
and having provision in our bags for ourselves and also for our horses,
sat down in the wilderness, and, after a slay of about three quarters of an hour,
and getting well refreshed, we mounted again, and rode till after sunset.
We then encamped for the night in the woods:
our two guides were very assiduous with my companion in
forming a camp or cover for us to lie under,
which we made of young firs or pine trees; we also made a good fire,
having wood in abundance, and near to a good run of water.
We put shackles on our horses, and bells about their necks,
lest they should stray from us; raked up what leaves we could get,
and carried into our camp to lie on, which, with the help of our saddles, bags,
great-coats, etc., made a good bed, and after feeding our horses,
and getting our suppers, went to rest very contentedly.

In this part of the country the long leafed pine grows in great plenty,
whose foliage is seventeen inches long,
and found in bunches at the extreme parts like a broom, and much that size;
they are very fine stately trees, and make a noble appearance.
Seventh-day morning, after a composed night, got on horseback about seven o'clock,
supposing ourselves to be now in South Carolina:
we travelled this day about thirty-five miles to a place called Waterree.
First-day, the 13th, had a meeting with the few Friends here,
about seventy miles distant from any other meeting of Friends.
I think it is a great favour from the Lord of mercies,
to remember these few of his poor servants in this lonely wilderness, who,
through worldly desires, have scattered and separated themselves from their brethren,
to their loss both temporally and spiritually.
They were well advised and seasonably recommended,
in that love which wishes life and salvation to to all men.
The meeting was mixed with other professors, and I thought it an open good meeting:
in the evening had a meeting in the family, which tended to edification,
which I desire may be acknowledged with thankfulness and awful fear.

South Carolina is a very unhealthy climate for English constitutions;
the inhabitants are very sickly and of a swarthy complexion;
the chief products of the province are indigo, rice and hemp, Indian corn, some tobacco,
and cotton.
Of trees, there are many white cedars, long-leafed pines, and the cypress.
This was in the first month,
and though so early I saw our sort of broad-beans just coming into blossom,
and wheat grown up near half-a-yard high.

Here are only three or four meeting-houses belonging to our friends,
and they lie very wide one from the other.
The 29th we returned to Pedee; it rained all day, and all the next night;
the waters rose to a great height, which prevented our travelling for several days:
had another meeting here, which the Master owned, to our mutual comfort;
let his name be praised forever!
Our dear friends, Jeremiah Picket and William Lindley,
who had been with us several weeks, left us at this place, and returned home;
we parted in tears, but rejoicing in the love of God,
and in unity and fellowship of the brotherhood.
We visited Friends in their families to good satisfaction,
there appearing a good disposition in many to receive the advice given,
and it was a day of precious visitation to many of them.
We stayed over their first-day meeting, which was the crown of the whole;
the Lord's power wrought mightily, to the joy and consolation of our souls:
may the remembrance of these moments long continue with
me with living praises to the Fountain of all goodness!

Fourth-day, the 6th of second month, we had a meeting at Dunn's Creek,
which was very small, a very mean disreputable meetinghouse,
without either door or windows, and I thought much lacking in the life of true religion;
nevertheless, we had free and open service amongst them.
Many Friends in these distant parts have suffered
considerable loss to themselves and families,
in a religious sense, by removing from larger meetings to these back countries,
where there are very few or no Friends.
The following day we set forward, and when evening came on,
betook ourselves to the woods; the night was clear and serene; we made ourselves a booth,
a very good fire, and having sufficient provisions for ourselves and cattle,
spent the night peaceful and well.
Next day got to Richard Cox's, by whom we were kindly received:
this night was remarkably tempestuous and stormy, very different from the night before,
when we lay in the woods.
We crossed over many rivers and creeks, and through bad and dangerous swamps,
in coming to this place,
but were wonderfully preserved and helped to get through them all,
for which my soul was made truly thankful.
Second-day, the 11th, travelled on till evening, and again lodged in the woods:
it was a remarkably wet time,
but the reward of obedience was more than amply sufficient for the fatigues of the night.
The morning more moderate; we dried our wet clothes by a large fire,
which we kept burning all night, and mounted about daybreak.

The 28th had a meeting at Wells, which was very large, and I believe edifying to many,
praised be the Lord for it, who teaches our hands to war, and our fingers to fight,
and gives the victory.
This was the last meeting we had in Carolina.
I underwent much spiritual suffering,
because of the lukewarmness and indifference of many professors here and hereaway.
May the Lord, if it be his will, bless the labours of his servants,
and cause many people to bring forth fruits fit for repentance!

The roads are very bad in the lower parts of this province, very watery,
with swamps and quicksands in abundance,
which make it difficult travelling both for man and horse without being mired.
The country produces very many pines, which are of great height and bulk,
from which turpentine is extracted;
from these trees also is obtained great quantities of tar.
But what struck my mind with greater astonishment was to behold the great fall of trees,
which was general for more than one hundred and fifty miles in length,
occasioned by a violent storm of wind and rain,
which is far beyond what my pen is able to describe.
To see so large a tract of land covered with fallen trees bespoke desolation,
and my mind was affected and impressed with great solemnity.

+++[+++After passing into Virginia,
where at Petersburg he rested and wrote the following letter to his wife, he remarks:]
Virginia is a very thriving government, pretty thickly inhabited,
amongst whom are abundance of Negro slaves.
Few Friends but what have some of them,
though many are disposed to make way for their liberty as opportunity offers.
The woods abound with a variety of trees, as pines, hickories, oaks of several kinds,
poplars and walnut, etc.
The soil is very good, and air pleasant:
a great deal of tobacco and Indian corn is raised in this province,
which employs great numbers of Negro slaves.

Petersburg, in Virginia, 14th of Third month, 1771.

My dear wife,

I have not yet received any letters from you,
nor any of my relations or friends in Europe, which I much long for,
being upwards of eight months since I left my own habitation.

Since I wrote from Beaverdam I have continued visiting meetings in Virginia,
North and South Carolina, and find myself supported beyond what I could expect;
meetings lie very wide in many parts,
some from forty to eighty miles and upwards from each other,
and this for several weeks together.
The work of the Lord is truly great,
and no man is able to carry it on but as the Lord is pleased to afford strength,
and make way in the hearts of the people for the
reception of that good he sees fit to communicate;
and though there is a state of obduracy in some, yet there is a tenderness in many,
who drink in the Gospel rain with joy and rejoicing,
and who I hope will in due time make noble plants in the Lord's vineyard.
We are followed from meeting to meeting by many of all ranks of people,
and I think my companion has great place amongst them,
and I do think the great and good Master has
richly qualified him for his work and service;
he preaches with authority and power, and has a great reach over the audience,
and in private families continues to have good service.
He is of a humble, kind disposition, not difficult to please at table or with lodgings,
but in all states learns to be content;
in religious meetings very considerate to his companion,
as also loving and kind to me out of meetings, which is very uniting,
and the more so as I think his ministry sound, lively,
and much to my edification and comfort:
I trust we are agreeable companions to each other.
We sometimes think, for the service sake it might be as well if we were to part,
but I believe it will not be till we get back again to Philadelphia, if then.

On third-day, the 8th of first month, I received a bad kick from my horse,
and was forced to be led into the house by my companion.
I hope ever to esteem it a great favour that my leg was not broken,
it was very much bruised: I rested about an hour,
and afterwards rode about twenty miles further that day, but endured much pain.
The next day rode about thirty-five miles to a Friend's house,
who did the best they could for me;
had a meeting there the next day to pretty good satisfaction,
but yet my leg was very painful.
We set forward the next day for Fredericksburg, about seventy miles,
which we rode in two days, and lodged one night in the woods, near to a rivulet of water,
and a tent which we made of pine trees.
The evening was very favourable, and we made ourselves as comfortable as we could:
had sufficient provision for ourselves and horses, being four in number.
We set forward pretty early, but found, notwithstanding my care,
I had taken cold in my leg, and I travelled in much pain the greatest part of the day.
At night got into good quarters, called Wateree, where I took rest,
having something of a feverish disorder attending me,
and let my companion go forward to the next meeting, called Bush River,
about eighty miles, the furthest meeting southerly,
about seven hundred miles from Philadelphia.
I am now waiting his return, which I expect this evening, and being much better,
I hope I shall be enabled to join him in the service, for I have much unity with him.

I see by the newspaper that many evils seem to threaten poor England,
which probably may more nearly affect me if I should live some time hence.
But I hope I shall be enabled to put my trust and confidence in Him,
who has hitherto been my fortress and safe hiding place,
and shall cheerfully submit to his dispensations in joy and in suffering, saying,
in a state of resignation, "`Not my will but yours be done,`" who can, if He please,
work deliverance in time of great danger.
In my companion's absence, my mind was brought under great exercise,
lest by not visiting the meeting my companion went to,
I should fall short of my religious duty.
I do not remember that I ever underwent a greater combat,
but at length being wholly resigned, though in much bodily weakness, my mind grew easier,
and though willing rather to go than not, was not permitted.

My companion now returned from said place, much hurt from a fall with his horse,
and rested some days,
says he hardly thinks it would have been practicable in
my weak state to have got through at any rate,
and so said those who were with him,
which helped to confirm me that I was in my place in not going.
Oh! that I might but be preserved in doing that which is right,
and from forwardly doing anything that should in any wise
bring dishonour to the great Name and his precious truth,
and wound my own soul.
Am now so far on my journey as Petersburg in Virginia, and am a little comforted,
inasmuch as I hear there are letters at John Pemberton's,
and he waits to forward them to me.

My dear children, father, brothers, sisters, and near kindred,
I am filled with a love towards you beyond expression, and to your children,
all of whom I should be glad to see in the Lord's time, if it be his holy will;
and oh! if that time should again be permitted to be,
that it may be with an increase of heavenly improvement.
But on the contrary, it would be great sorrow to my mind, that any of us, great or small,
should have departed from the Truth, and gone backward and not forward.

My dear love salutes you all, the nearest in kindred first and so on to all,
and all the families throughout the whole meeting.
I am, through the Lord's goodness in a good degree of health, which I esteem a favour,
having lain many nights in the woods:
I hope I have got the worst of the journey over respecting the outward
travel it is likely to be six weeks before I can reach Philadelphia.
I remain in great affection your loving husband,

Joseph Oxley.

On second-day, the 25th of third month, we crossed Potomac River in a boat,
being three miles wide; and next day rode to Piscataway,
a small but pretty town in Maryland, within a few miles of a navigable river;
from there on to Patuxent, Indian Spring, Elkridge, and Baltimore,
which is a very pretty place; has a court-house and market-house,
a navigable river comes up to the town, and it is a place of considerable traffic.
Fourth-day, 3rd of fourth month, had a meeting at Patapsco, at which I was silent;
a large gathering of other people, amongst whom my companion had, I trust,
seasonable service.
Fifth-day rode to Gunpowder, which is the largest meeting I have seen in all Maryland,
both my company and myself sat through this meeting in silence:
it was a time of close exercise to us both.
Sixth-day we had a little meeting at Little Falls.
Seventh-day, not being free to go further without returning to Gunpowder,
rode to Mordecai Price's, whose wife was daughter to Ann Moore,
an eminent minister of the Gospel,
in which capacity she made a visit to England in the year 1760,
to general good satisfaction.
She was with us at this time, as well as others of her children.
First-day rode to Gunpowder; it was a very large meeting; we had each an opportunity,
as also had Ann Moore, but for all this, the state of the meeting was low, and not open.
Our said friend Ann Moore, went with us after meeting to dinner;
she had a seasonable opportunity at table in supplication.
Third-day to Bush River, fourth-day to Deer Creek:
many of other professions came to this meeting, and very many Negros,
which much increased the meeting; the largest meetings are not always the most favoured,
yet it was a time of love to the honest-hearted in Israel.
We accompanied a Friend home, who is a minister, as is also his wife.
He related to me,
that when my uncle Edmund Peckover was in that country on a religious visit,
he was high-sheriff for the county,
and one of his uncles at the same time a justice of the peace;
and hearing of a meeting which was to be at Deer Creek, inclined to be at it,
though they were in attendance at court, which was then sitting,
and his uncle the sitting justice.
Nevertheless, excusing themselves to the court, they two, with another of his uncles,
came to this meeting, and so effectual was the preaching of the Gospel that day,
that they were all convinced, and became serviceable members of our Society.

Maryland is for the most part hilly and stony; the soil strong and fertile;
its produce much like that of Virginia.
Seventh-day crossed the Susquehanna River, a mile over, in a very bad boat,
very leaky and dangerous, into Pennsylvania; lodged at Joshua Brown's,
a Friend in the ministry.
First-day, the 15th, had a meeting at Little Britain.
Second-day, one at West Nottingham, which was tolerably large and satisfactory.
We were met here by our worthy friend, that good man, John Churchman,
an eminent minister of the Gospel, whose services are well known to many in England,
Wales, Scotland, Ireland, Holland, Germany, etc.; his labour was great, instructing,
convincing, and edifying to many, by whom he is had in sweet remembrance.
Dear John Pemberton of Philadelphia, accompanied him a great part of the time,
a young man of a sweet disposition, sober and religious, of a humble and meek spirit;
as he was rich in earthly possessions, so he was a lover of hospitality;
he communicated freely to the necessities of the poor and needy,
both of our own and other societies,
a generous subscriber on public occasions for general good.
He was an enemy to slave-keeping, but a friend to slaves.
During the course of his journey, his mouth was opened in a ministerial capacity,
in which he moved with great caution,
and spoke of the things which he knew by experience.
His conduct was consistent with the doctrine he preached, and recommended to others.

From West Nottingham we continued with our above-mentioned friend John Churchman,
to East Nottingham, the place of his residence, where we tarried all night.
Third-day we had a meeting there, which was very large, chiefly of our own Society;
it was mercifully favoured with the overshadowings of Divine love,
to the tendering of the hearts of many,
which the good old man afterwards acknowledged with fear and reverence:
let the Great Name be praised for all these benefits!
Fourth-day at Londongrove: Fifth-day at Newgarden, a large congregation,
and I trust the meeting was profitable to many,
being owned by the Master with that love and life that make glad the heritage of God,
unto whom be praises forever!
Sixth-day a large precious meeting at Bradford.
Seventh-day went to Susanna Lightfoot's, who is well known both in Ireland,
from which she removed, and England,
for her many labours and acceptable services in those parts, and also in America,
where she now resides, in great reputation.

+++[+++The editor trusts the following extract from James Gough's MS. Journal,
will be acceptable to his readers.]


"`I was accompanied by my dear friend Susanna Lightfoot, then Hatton,
to such meetings as she could get out to attend.
She was a servant to Ruth Courtney,
and in that station accompanied her mistress in
a religious visit to North America in 1737,
and there first appeared as a minister.
On their return, they landed at Cork; Susanna being then eighteen or nineteen years old.
The work of the Lord appeared to me to be deeply rooted in her:
I was much affected with her inwardness, fervency,
and tenderness of spirit out of meetings, as well as her awful utterance in meetings.

Some time after they had been at home,
her mistress took her to the west of England in 1740,
and made her not only wash their linen constantly,
but supply with her own hands the horses with hay and oats,
and rub them with straw several times a day,
and would let no other Friend's servants intermeddle.
Her public services in meetings were generally acceptable to Friends, and they pitied her.
I heard, that on this journey,
a young man in good circumstances took such a liking to her,
as to make her an offer in marriage, and that she replied,
that she was under engagement to one in her native country.
After her return, in 1742, she married Joseph Hatton, a linen weaver.
Robert Richardson coming to the Half-year's meeting at Dublin,
collected for them from a few Friends about thirty pounds,
which enabled them to open a huckster's shop in Lisburn.
While she was capable of attending it, the shop seemed likely to do well,
but having twins a second time, and having them both to nurse,
as soon as she could inspect the state of affairs, she found them neglected and impaired,
which fixed such a weight on her mind, that she went herself to the creditors,
and desired them to come and seize what was left,
hoping there would be enough to pay them, though little or nothing over.
Hereupon a Friend in Lurgan,
having about three years to come of a lease of a little
land and a cabin upon it at a moderate rent,
out of regard to her, offered her the remainder of his lease.
Here then, in a poor plight, they moved.
When I was in Ulster in 1749, their time on this spot was almost expired.
I was often at Lurgan on this journey, passing and repassing,
and I daily went to see her, and always thought I got good by it,
I ever found her in such an excellent frame of mind.

Her husband kept two looms going, and she kept two cows, and they saved money;
but seeing no prospect of any land to be taken thereabout, except at an exorbitant rent,
they concluded to remove themselves and children to America,
and while I was there applied for a certificate:
but several Friends were so affected with the thoughts of her leaving them,
that they contributed their cares and endeavours to get her resettled amongst them.
Yet trials and troubles were to attend her.
Sometimes she had not a bit of food for herself or her children,
nor a farthing to procure any; but when reduced to the last extremity,
and ashamed to make her case known,
sudden relief would come in from one quarter or another.
Besides, she underwent harsh and severe persecution for her testimony to plainness,
against pride, and the violation of our Christian testimony,
which was required of her as a duty.
Through all these things, she grew brighter and more excellent in her ministry.
Her situation continued in this destitute way,
until it was discovered by Friends of Leinster and Munster, on a national visit.

She had then several invitations; but her way opened to Waterford,
where she was assisted by her friends to remove herself and family.
She left Ulster, much regretted by the religious part of Friends in that province,
amongst whom she had been a bright and excellent instrument.

Not one in those large meetings rose up with
that Divine authority and dignity that she did.
In this journey, I was at two province meetings in Lurgan,
after which Robert Richardson and I went to see Susanna;
we found many Friends of the better sort in her cabin:--a sweet silence arose amongst us,
after which she preached the Gospel to us with such penetrating energy,
that there were few or any dry eyes present.
After her coming to settle in Waterford, she visited Carlow, Mountmelick, etc.
A Friend put four guineas into my hand, and desired me to present her with them,
which I did; but she refused to accept them, telling me,
she had others offered before in that journey, but dared not receive them,
being under no present necessity.
Her children grew up, and many Friends conceived such an affection and esteem for her,
that her sons were readily taken as apprentices gratis,
and her daughter or daughters taken under the care of another rich Friend.
Her husband died in 1759, and she travelled to visit Friends in America.
In the interim, a rich Friend of Waterford died,
and left her fifteen pounds per annum during her life.
After her return from America, Thomas Lightfoot, a Friend in good esteem,
followed her to Waterford, and married her.`"

First-day, the 21st, was at Uwchland, which was very large, and to good satisfaction;
second-day came to Philadelphia, where I received many letters from my wife and children,
brother John Oxley, sister Ann Hawks, John Gurney, and Sarah Grafton;
these were the first from home I had received since I had been on the continent,
being upwards of nine months, which made me very anxious to know the contents.
Those from my dear wife and children were most pleasing,
giving me an account of their welfare,
and from which I was able to form some idea of the precious
visitation that had attended them during my absence,
which was much to their and my comfort and satisfaction.
These letters also brought me the sorrowful
tidings of dear sister Elizabeth Oxley's death,
which was no small affliction to me.
Not being very well,
on seventh-day I went with my friend Benjamin Swett to his house at Burlington,
his wife as well as himself in the ministry; they were indeed,
affectionately loving and kind to me, and I was much better for being there.

Philadelphia, 26th of Fourth month, 1771.

My dearly beloved wife,

I returned to this city the 23rd inst.
from our long journey southerly,
at which place I met with sundry letters from my dear relations and friends,
which I had been greatly longing for, it being ten months since I left my native country,
and these the first letters received on the continent.
I think my last to you was from Petersburg, and four I have now received from you,
all which are filled with so much good,
that I think mine to you on this paper will still leave
me very short of paying you what you justly merit.
Being so fully satisfied of my incapacity herein, I will turn the eye of my mind inward,
and pray to him that hears in secret, that he may be pleased to reward you openly,
and more largely and fully than heretofore,
which will far excel anything I can do or write, as light excels darkness; and,
however the lot of my inheritance may be on this side the water,
I am certain yours is in a good land.
I judge from the various testimonies I have from under your own seal,
as also from several others, and from the secret evidence I have in myself,
that you live in a good land, flowing as with milk and honey;
for which my spirit reverently bows in contrition and in thankfulness,
to acknowledge the descendings of his heavenly goodness, mercy and truth,
who is become the guardian of the beloved of my bosom,
the feeder and teacher and preserver of the wife of one,
who is in his own estimation least of all, and unworthy!
I am separated from all my nearest connections,
and am made to endure suffering upon suffering, even unto death: but of these,
there are various kinds;
some of which are occasioned through our own folly and misconduct in temporal things;
such as these, if rightly and properly attended to,
would lead to better order and regulation.
There is also a suffering of another kind, of a religious nature,
but for lack of being religious enough,
the creature slain and self become of no reputation; while in this state,
the creature is not sufficiently brought into
subjection to the will and mind of the Greater,
but remains in a state of disobedience and unfaithfulness to his will.
This is a suffering, which neither you nor I are altogether strangers to,
but it is a righteous and just judgment upon
those that know the Master's will and do it not,
and such indeed are worthy of many stripes;
such unfaithfulness occasions Divine withdrawings,
which to the pious soul are hard to bear;
but are expedient to prevent in future such disloyalty,
whereby we become robbers of the churches, and dishonourers of God.
Therefore let all such as have received their gifts and qualifications,
stand in the Divine counsel,
and minister in that ability which the Great Master is pleased to give; and in so doing,
they will become of the number of the righteous, who hold on their way,
and being of clean hands will grow stronger and stronger.
This is a faithfulness acceptable in the sight of God,
and is to the edification of the churches; its reward is peace,
and the effect of it righteousness, quietness, and assurance forever.

There is also another sort of suffering, of a different nature, though spiritual,
more sensibly experienced by those that are
seeking above all things the heavenly kingdom,
and to stir up the minds of the children of men in a like godly concern:
an arduous outward labour, added to an inward exercise, is oftentimes the lot of these,
who are most devoted to the cause of God; and they are more or less affected,
according to the state of the churches.
It is from a sense of man's wickedness, his wilfulness, his sins and transgressions,
which are manifold, and contrary to that pure, holy witness in him,
from time to time testified of by those who from living
experience can speak of the goodness and mercy of God.
But how little avails it in the hearts of the people generally;
they are grown into such a state of stupefaction, as to love darkness rather than light;
and it is because of these thoughtless, heedless souls,
that many are brought into this state of suffering and great trial.
Yet as we abide properly under it without shrinking,
it will tend more and more to our purification and refinement.
But what are all these sufferings to those of the holy
martyrs and faithful servants of God in former ages?
There is One,
who by the turning of his hand can and does at
his pleasure make our wilderness like Eden,
and our desert and solitary places as the garden of God: therefore,
whatsoever my sufferings may have been, inward or outward, I dare not, I do not repine,
at the dispensations of Divine Providence,
whose visitation is so mercifully extended to you, my dear wife, and my children,
which I trust is more to us than thousands of gold and silver.

It has been matter of comfort to me to be informed of
your and family's health from time to time,
and I may say so of myself except colds, and at times fatigue in riding.
I am pretty much fallen away with long travel and exercise, and my spirits sunk,
as you know how it was once with me; but in all things, my dear, I am easy and resigned,
and am learning contentment in every state.
There is a probability of my companion and I parting,
as we seem to be led different ways; he thinks to take the Eastern Shore of Maryland,
my mind seems to draw towards New England, and to be at the Yearly Meeting at Flushing,
if it please Providence so to enable me.
William Hunt, a ministering Friend, comes by this vessel,
whom I have mentioned in former letters; he is now in this city.
Our friend S. Morris, also before mentioned, intending for your parts,
has had a long time of indisposition, both inwardly and outwardly, is now better,
and has revived her concern to the Monthly Meeting of Philadelphia.
Her companion is Elizabeth Smith of Burlington, at which place I now am,
as is also S. Morris; they are two weakly women,
but in good reputation in conduct and ministry.
I was at Burlington meeting yesterday, where the Master was graciously pleased to own us,
to mutual comfort and edification.
I left my companion in town, being somewhat indisposed.

I am at the house of Benjamin Swett, whom you probably may remember in England:
I rest here a few days to recruit body and spirit, to write letters, etc.
I have received a very kind affectionate epistle from dear John Gurney,
which I intend answering; my kind love to him and all his family.
If I am preserved in health, I shall not loiter away my time,
but not being so strong as some who have passed before me, I take it more leisurely:
some have travelled too fast,
and thereby have rendered themselves and service not so useful,
as if more time had been taken.
At present I think little about home, or whether I have a home,
otherwise than where I am led by my great and good Master.
So with my very dear love to Friends in general,
and if you have freedom to all the women Friends
of your Monthly Meeting in a collective capacity,
whom I love in the Lord Jesus Christ; grace, mercy, and peace be with them and you;
let them know I am well, and fully resigned to the disposal of the Divine will.

From your loving husband,

Joseph Oxley.

First-day, 28th, was at Burlington meeting;
there were also from Philadelphia Sarah Morris and Joyce Benezet,
two valuable ministering Friends.
Deborah Morris was also an attendant on her aunt,
whose respect and kindness to me was not a little, I loved her much for the Truth's sake.
We had two good comfortable meetings, being owned by the Master,
to the increasing of our love to him and one unto another.
Fourth-day had a meeting at Mount Holly; fifth-day was at Burlington week-day meeting;
also their select meeting of ministers and elders, which in some part was well,
but not throughout.
I thought there was lacking more of that love and unity which should
harmonize and cement Friends together in those religious stations.
Rode to Philadelphia,
and on seventh-day attended their Quarterly Meeting of ministers and elders,
which was large.
William Hunt, an able minister of the Gospel from North Carolina, was here,
and said much in this meeting.
This Friend had it long on his mind to pay a religious
visit to Friends in different parts of Europe,
and all things being in readiness for his embarkation,
I accompanied him a part of the way to Chester, where he was to go on board,
and returned in the evening.
First-day, 5th of fifth month, attended all the three meetings in the city.
Second-day came on the Quarterly Meeting for business,
which was entered upon after a solid meeting for worship,
and conducted with becoming condescension and brotherly affection.

