== Chapter XI.

We reached New York on the 6th of ninth month,
and were at both their meetings the first-day following; our friend Samuel Nottingham,
a ministering Friend well known in that capacity both in England and America, was there;
the service in the morning fell on me, and on him in the afternoon,
and I hope to some edification.
Second-day we passed into Jersey, attended by Samuel Bowne.
At Mount Holly lodged at a widow woman's,
who with another Friend of that town was at some difference;
and both being present and desirous that the cause of the difference might be opened,
and themselves again reconciled one to another,
left the affair for my companion Joshua Thompson
and myself to judge thereon and determine,
according to the best of our understanding.
This we did, in that wisdom which was given us,
and two other Friends were present as witnesses;
we experienced the Truth to cover our minds,
and the parties were brought to acquiesce in our judgment,
and were thoroughly reconciled to each other, for which our hearts were made thankful.

Fourth-day rode to Philadelphia, where I received many letters from Old England.
This same evening also, came into the city my dear companion, Samuel Neale;
we were much pleased to see each other, and the next day,
with several other Friends went to Haddonfield Quarterly Meeting;
it was large and to pretty good satisfaction.
On seventh-day following, the 21st of ninth month,
began the Yearly Meeting of ministers and elders for Pennsylvania and the Jerseys,
held at Philadelphia, which we attended throughout.
At this meeting were presented certificates on behalf
of our friends Sarah Morris of Philadelphia,
an able minister of the Gospel, and Elizabeth Smith of Burlington, an excellent minister,
and who for many years past have had it on their minds
to pay a religious visit to Friends in Old England;
and produced certificates from their Monthly and
Quarterly Meetings for the Yearly Meeting's approbation.

After many weighty sittings and solid deliberation,
the meeting having a near sympathy with them in their religious concern,
recommended them to the Lord for protection and to the guidance of his Holy Spirit,
and granted them certificates to proceed as their way
might more fully open to their satisfaction.
These, and the preceding meetings for worship and discipline,
continued till late on the fifth-day following, and were very large,
many weighty matters were brought before them, and spoken to according to Gospel order.
It may be said that the meetings both for
worship and discipline were to the glory of God,
the praise of his great name,
and to the comfort and edification of his church and people.
Great is his power and goodness, and worthy to be had in everlasting remembrance,
even forever and ever!

Second-day went to Abington Monthly Meeting; the meeting for discipline not satisfactory:
many having gone out in marriage, contrary to the good order established amongst us;
some recent instances appearing at this time,
brought sorrowful exercise upon well concerned Friends.
Many also showed themselves very disorderly in going
frequently out of meeting during the time of worship,
and very much so in time of transacting the service of the discipline,
which was painful to bear.
Fourth-day was at Byberry; lodged at James Thornton's,
who came from Old England some years since and settled in this country:
he is a worthy minister and elder.

Sixth-day rode to Philadelphia,
where I received a melancholy letter from my dear brother John Oxley,
giving me an account of his being attacked with a paralytic stroke,
and though he was getting better, I was much concerned and affected with the news,
lest another attack of the same kind should soon follow,
and be of still worse consequence.
Third-day, in company with Samuel Emlen, senior and junior,
went to Woodbury and had a meeting there; it was a time of laborious exercise,
but I hope not without some advantage.

Went home with our friend and elder David Cooper,
in whose family we had a comfortable meeting: he has some promising children,
inclined to sobriety and virtue; such I think are an honour to parents,
and also such parents an honour to children.
Fourth-day, rode to a meeting at Upper Greenwich which was much crowded.
I was led to speak of the variety of dispensations that
were allotted to the righteous for their purification:
it was an open good meeting, and the name of the Lord was praised for it,
who is worthy of all praise.

First-day, the 13th, was at Salem meeting, which was very large,
both of our own and other societies.
I had to speak of the universality of the love of God
to all people of every profession everywhere,
and to exhort those who were more immediately called
into religious services to be faithful therein:
the meeting ended in prayer and praising the Lord.

Next day to Lower Alloways Creek, and after meeting went home with James Daniel,
an able minister of the Gospel,
who visited some part of Europe in the year 1752 in a religious capacity,
which was to his own peace and the satisfaction of Friends: had a meeting in his family,
which was mercifully owned to the refreshing of our souls.
He accompanied us the next day to Lower Greenwich meeting:
after dinner several Friends coming in, we had a short but profitable sitting,
and some bread was cast upon the waters, which I believe will remain after many days.
First-day, the 20th, had a meeting at Middle Egg-harbour, which was low and small,
but the Lord was with his ministers, helping them to divide the word rightly,
blessed be his name for it!

Seventh-day, the 26th, began their Yearly Meeting at Shrewsbury:
amongst others who attended were Robert Valentine from Pennsylvania,
Mark Reeve from West Jersey, Isaac Andrews from Haddonfield,
Richard Titus from Long Island, Sarah Morris, Benjamin Swett and wife, and some others.
In the meetings on first-day I was silent:
the meeting for worship on second-day previous to that for business was very large,
and though it gathered very badly,
yet afterward it settled into solemn and profitable waiting,
and it was a glorious good meeting, the Lord got himself the victory,
and it ended in supplication and thanksgiving to him for all his mercies and benefits.
The discipline of the church was carried on in the spirit of love and condescension;
sundry necessary remarks were made and advices given for counsel and instruction,
and were well received, all tending to edification.

These meetings being over, went with many other Friends to Richard Lawrence's,
who was formerly a member of parliament,
but he became convinced of the Truth and took up the cross,
so that he had not freedom to continue his seat in that house; he, as also his wife,
are steady valuable Friends, and he himself waited on his guests at table,
as one being redeemed from all worldly pomps and honours.

Shrewsbury, 7th of Tenth month, 1771.

My dearly-beloved wife.

Your kind and affectionate epistle of 23rd of seventh month,
I have received with the usual marks of the loving and faithful wife;
and in return please to accept these lines from your dear and affectionate husband,
though separated so long and at so great a distance.

This I think nothing temporal should have occasioned, but He on whose account it is,
is still worthy to be served and obeyed;
and here I trust we consider ourselves as being married in the Lord,
and so he is become our husband and head.
It is our incumbent duty to be subject to him
however nearly we are united as husband and wife,
yet his commandment is above all to rule us and to be attended to; and in this matter,
I trust, we are of one heart and one mind, and are one another's in the Lord.

I am through Divine favour in good health and spirits,
and at times made strong to declare the goodness of the Lord, and to invite to him,
whose ways are ways of pleasantness and whose paths are peace;
and sometimes I have a hope that my labour is not altogether in vain in the Lord,
though my all be only as the two mites.

This letter, and indeed all that I have received from you,
are proofs not only of your integrity as a loving wife and an affectionate mother,
but also as valiant and bold in the cause of Israel's God:
if it should please Him for whose cause we are separated, to bring us together again,
I trust it will be a joyful meeting.
I have now travelled over great part of the continent, so far as even to think,
at least if health is preserved and nothing unforeseen prevent,
I may finish what remains with the year; but if it should be so,
there is great probability that the frost and other impediments may prevent,
that I shall not say more at present on that head, nor draw hasty conclusions.

I am now at Shrewsbury attending this Yearly Meeting,
at which there are many Friends of higher degree, but none so little and mean as I am.
We have been favoured this day with a large and good meeting.
Truth rose into dominion, and the Lord's great name became glorious,
his own arm wrought salvation: the meeting ended in prayer and praising him,
who is worthy forever!

Seventh-day, 2nd of tenth month, had a meeting at Hardwich or the Great Meadows,
which was large, but gathered in so much disorder as to make it quite burdensome;
and as it met so dishonourably,
the Great Master would not condescend to honour as at other times.
I faithfully spoke what was given me, which I believe will be long had in remembrance.

Second-day was at their Monthly Meeting at Buckingham,
which I think was the largest I have yet seen in Pennsylvania: Grace Fisher,
a ministering Friend from Philadelphia, also Susanna Lightfoot were there,
and we were much pleased to see each other.

The meeting for worship was to good satisfaction, but that for discipline not so,
many of other societies crowding themselves in,
on account of seeing some young couples present their intentions of marriage,
which when over they generally withdraw, and many of our young Friends go out after them,
to the great disturbance of the meeting,
and it is to be feared many times it has a hurtful tendency to our young people.
Much was said in order to put a stop to this unbecoming and disagreeable custom,
which is painful to many Friends,
and it is to be hoped the advice that was given would have a happy effect.

Third-day went to Wright's Town Monthly Meeting,
after which went to our friend Joseph White's, an able minister of the Gospel,
well known by many in Old England for his acceptable service there.
Sixth-day, had a meeting at Bordentown, in the afternoon visited Joanna Sykes,
who had buried her husband but a few days before,
who was in the ninetieth year of his age, and his widow almost eighty-eight;
they had lived together in a married state sixty-seven years,
and both of them acceptable ministers of the Gospel.
I felt some good in my heart, while sitting in retirement, of which I communicated,
and we were comforted together thereby.
About this time, there came down out of the wilderness into Pennsylvania many bears,
which did considerable damage; we heard that a child was killed by one of them,
and a man and woman much hurt by another.
The coming down of bears so near Philadelphia has not been known for many years past.

Seventh-day, had a meeting at a place called Robins;
this meeting and meeting-house was fallen much into decay;
scarcely any Friends left to uphold the meeting with any degree of reputation;
yet it was to us a time of Divine favour,
and strength was given to speak well of the name of the Lord, whose presence is near,
and able to preserve those who put their trust in him.
We afterwards set forward for Philadelphia;
and ferrying over Rancocas and Delware Rivers to the city,
was made thankful in that I witnessed the protection of
the Lord to preserve my body in health,
and my mind from sinking into unprofitable lowness: blessed be his name forever and ever!

The soil of the Jerseys towards the east is very barren,
but abounds with cedar-swamps and pine trees, much made use of for building.
The timber in the northern part, which is mountainous, is oak of various kinds,
some of which are three, four, five and six feet over; black walnut,
commonly called in Old England Virginia walnut, much used by joiners for desks, drawers,
tables, coffins, etc.; poplar, hickory, chestnut, ash, beech, sassafras,
with swamp bushes of various kinds, as the bay, magnolia, white and black alder,
sumac of various kinds; one of which, called the swamp sumach,
is of so poisonous a nature that even handling it will
so poison a person's flesh as to blind them.
Peaches they have in great abundance, also quinces, pompions, squashes, melons, etc.
Their horses in a common way are not handsome,
but travel much easier and are much more hardy than ours in England.
Of wild beasts there are bears, wolves, panthers and deer,
which decrease as the inhabitants increase: also foxes, raccoons, otters, musk-rats,
opossums, etc.
On the sea-coast and bay are numerous quantities of flies and mosquitoes,
which extremely annoy both man and beast by
their biting and injecting a poisonous quality,
which is painful to bear.

Fourth-day, 13th of eleventh month, was held a meeting for the Negros;
the service that day fell on Sarah Morris, Samuel Emlen, and John Pemberton;
there were few at this meeting but Negros, they generally sat soberly,
and conducted themselves well;
these meetings for the benefit of the poor Africans are held quarterly.
Fifth-day, left the city in company with John Pemberton.
My late companion Joshua Thompson returned home,
having travelled with me upwards of two thousand miles,
whose company was very agreeable and useful, he being an elder worthy of double honour.
We passed over the river Schuylkill to Derby,
where there was a marriage of a son of William Home,
a ministering Friend well known in England for his services there in the year 1762.
Sarah Morris was at this meeting; and it was an opportunity of Divine favour to many,
which our souls were made thankfully to acknowledge.
The same evening to Springfield, and lodged at Mordecai Yarnall's,
an excellent minister of the Gospel, who visited Old England in the year 1757,
and whose services are remembered by many.

Seventh-day to Providence, then to Chester, and lodged at Joshua Hoskins's,
who was husband to Jane Hoskins, an able and well approved minister,
who visited Europe in company with Elizabeth Hudson in the years 1749 and 1750.
Third-day had a meeting at Center, to which many were gathered,
wherein was preached the testimony of Truth in a good degree of heavenly life and power;
thanksgiving and praise be given to Him who gives strength and power to do it.
Fifth-day attended a very large meeting at Wilmington:
the chief part of the inhabitants of this town, which is a very improving one,
are under our denomination.
In this meeting I gave way to fear, and discouragement prevailing,
I let go that faith which before I had known to be my support,
and without which we are not able to please God.
At this place live Elizabeth Shipley and Esther White, both eminent in the ministry,
particularly the former: they visited Friends in Great Britain, etc. in company,
in the year 1745, to great satisfaction: they are now far advanced in years.
I visited them to my spiritual comfort and refreshment.

First-day, the 1st of twelfth month, attended a meeting at Marshey Creek,
where were some of the people called Nicholites and also of other professions.
After taking some refreshment at William Edmundson's,
at whose house we had lodged the night before, we bent our course toward Little Choptank.
The wind blew very hard,
and we had to pass over a bad and dangerous causeway about half a mile long;
it was with great difficulty we got our horses through without being mired:
at the end of this causeway was a ferry over Choptank River.
When we came to the river-side, we were all afraid; the ferrymen said,
the wind was so boisterous,
it was not possible for us to get over but with the greatest danger.
We overtook three Negros who were also going over;
one of them said he had been used to that sort of work,
and he did not fear but that we should get over very well.
For my own part, I was very much discouraged,
and exceedingly reluctant to come away from our friend William Edmundson's house;
but my companion was very much for it, so,
in condescension to him I complied and set forward.
We all of us got into the boat, being nine in number besides three horses.
The wind being exceeding strong,
it was with great difficulty we could put off from the shore, which at length we did,
and soon got driven far beyond the usual place of landing; the wind being ahead of us,
we could make very little way across the river, and it increasing,
blew the water out of the river like rain; also at the same time it froze very severely,
so that we became quite benumbed with cold.
The men rowed with all their might, and sometimes got a little forward,
at other times lost what they had gained, and night coming on,
there was very little better prospect than our being cast upon a wide swampy marsh,
where was no landing, and in a dark, frosty night in an open boat:
we concluded we must be all dead by morning.
At length it pleased Divine Providence to cause the wind to lull, as the sailors term it,
and we got a little forward, but it soon increased again, and we were in great distress,
and it was now almost dark; our horses also began to be very unruly,
which increased our difficulty.
Some of the men would have us endeavour to go back
again to the place where we entered into the boat;
others said it was impossible, and advised our using our utmost strength to get forward,
which we did,
and with long and hard labour we at length got happily over to the other side,
but far wide from the landing-place, and reached a Friend's house not far distant.
I hope to be thankful for this merciful deliverance,
and in future to be more attentive to my inward feelings,
which when duly attended to are many times
preservatives both from spiritual and temporal dangers.

First-day, the 15th, rode to Goshen,
where we lodged at our worthy friend Thomas Goodwin's, a minister of the Gospel,
who paid a religious visit to England in the year 1762.
Second-day was at their meeting, and went home with Aaron Ashbridge,
an elder in good esteem, who was husband to Elizabeth Ashbridge,
a minister well approved;
she visited some parts of England and Ireland in company with Sarah Worrall,
who was also well approved of in the same religious capacity.
Yet it pleased the Lord to visit them with sickness,
under which affliction they long lingered, and with hard travel,
and inward and spiritual exercise grew weaker and weaker,
and at length quietly departed this life,
and I doubt not are at rest and peace with the Lord.
Fourth-day, was at Concord Meeting, which was a day of great power,
wherein the Gospel of Christ was preached in good authority, and the great Name praised,
who is worthy forever and ever.
From hence to Nathan Lewis's, who is a minister, as is also his wife;
she visited some parts of Europe about the year 1753.
Seventh-day at the Valley meeting; I thought it like unto Rephidim,
a place where there was no water: I was altogether silent, but my companion,
Thomas Carleton, communicated a little matter.
After meeting to Edward Jones's,
where I was met by my kind friend and landlord John Pemberton,
who brought me letters from my dear wife and children,
with good accounts respecting their welfare, for which my mind was made humbly thankful.

First-day, 22nd, was at Radnor meeting.
Second-day to Haverford, and so to Philadelphia; through Divine favour,
in very good health: blessed and praised be his great and excellent name for ever more,
who has so wonderfully preserved me in this great and arduous engagement,
through this long wilderness, with a measure of that peace,
which he the Lord only can give,
and it pleases him to bestow it upon those who in faithfulness follow him,
in the way of his requirings.

+++[+++John Pemberton about this time writes thus to Mary Oxley:]


"`Your dear husband has stepped along wisely, and has gained the love of Friends, and,
indeed, it is a great blessing and mercy to be so preserved,
and I expect he will leave us much united to him.
Visiting the churches in our time is attended with much suffering:
frequent baptisms into death, in sympathy with the suffering seed,
is the allotment of the Gospel labourers;
but where faith and strength are vouchsafed to discharge duty, there is a satisfaction;
and the sweet evidence which at times through adorable
condescension is granted to the sincere in heart,
who have nothing in view but the glory of God, and the good of souls,
and that they may be found faithful, tends to support in seasons of secret mourning.`"

+++[+++The following is an extract of a letter from Joseph Oxley to his wife:]


Philadelphia, 1st of First month, 1772.

Since my last to you I have been visiting Pennsylvania and the Jerseys,
and about two days since was met by my kind friend John Pemberton,
who gave account of the Pennsylvania packet.
Captain Osborne, being arrived, and brought me yours of 2nd of ninth month,
which is truly acceptable,
with the comfortable tidings of  your and our family's welfare.
My last would acquaint you with my intention of returning by Osborne.
The time of her sailing is settled to be the middle of next month,
if nothing unforeseen prevent.
Having finished what I apprehend to be my duty, I am waiting in the city,
visiting Friends.
I think I may say I find much freedom and openness in their hearts,
as well as in their houses to receive me,
and am shown much respect by Friends in general, though undeservedly.
I am, through the favour of a kind Providence, in good health and tolerable spirits,
content with my wages, and murmur not.

Dear Elizabeth Smith continues in great bodily weakness,
and more likely to die than to live.
Samuel Emlen, at our last Monthly Meeting at Philadelphia,
laid before the meeting a concern he had on his mind,
to pay a religious visit to Friends in some parts of Great Britain; also another Friend,
John Woolman, a wise sensible man,
having a good gift in the ministry and well approved of, has a concern of the like kind,
more particularly to Yorkshire.
I suppose the latter will hardly leave the continent till the summer.

May Divine Providence bless us, keep us, and preserve us temporally and spiritually,
by sea and land, that we may once more meet together,
rejoice in the mercy and goodness of God,
and live to praise and adore his great and excellent name, who is worthy for ever!
I again salute you, my endeared wife and affectionate companion, and you,
my beloved children, with the blessing of a loving husband and tender father:
you still remain the objects of my care,
with strong cries to the Lord for preservation both for you and me.
During this long separation, I have had many trials, exercises,
and besetments you know not of,
through all which the Almighty's power has wrought my deliverance,
praised be his great name for it; and you, though not in the same way, have, I doubt not,
had your trials, even to the trial of your faith and patience;
and it is as we endure these siftings and provings that our souls are purified,
and our understanding and judgment ripened; thus we are fitted for service,
some in one way, and some in another: therefore, live and walk in him,
in whom you have believed.

Joseph Oxley.

The hard frost being now set in, stopped the navigation;
I spent much of my leisure time in paying religious visits to Friends in their families,
which being numerous, occupied my time till the first month, 1772.
This service, I had cause to believe was in the will of the Lord,
who gradually leads his servants forward into service, step by step,
to their joy and his people's rejoicing.
The 6th of second month, I was at the Youths' Meeting in Philadelphia,
which was attended by some Friends from the country.
At this meeting was Nicholas Wain, who had his education amongst the Society,
but was brought up to the law, and became great in his profession as a counsellor,
and who had pleaded at court but a very few days before.
He sat under an awful weighty exercise of mind
from the early sitting down of the meeting,
and removed his seat into the ministering Friends' gallery; he appeared to be agitated,
and trembled very much: after sitting about half an hour, he kneeled down and prayed;
but his behaviour and dress being so contrary to such an appearance,
occasioned Friends to be much divided, and made some disorder in the meeting,
but afterwards it settled and ended to the edification of many.
The said Nicholas Wain declined his practice as a counsellor,
which it was said brought him in from one thousand five
hundred to two thousand pounds per annum.
I went, at his request, to visit him, in which visit I had much satisfaction;
I found him solid and weighty, and since that time have heard well concerning him.

On the 12th went with Benjamin Swett to Mount Holly meeting; and, in our way there,
about four miles from Burlington,
we went into the woods to see a person of whom Samuel
Smith in his history of the Jerseys writes thus:
"`Four miles from hence, a recluse person, who came a stranger,
has lived alone near twelve years, (now twenty,) in a thick wood,
through all the extremities of the seasons, under cover of a few leaves,
supported by the side of an old log, and put together in the form of a small oven,
not high or long enough to stand upright or lie extended.
He talks Dutch, but unintelligibly, either through design,
or from defect in his intellects: Where he came from, or what he is,
nobody about him can find out.
He has no contrivance to keep fire, nor uses any in very cold weather: he lies naked,
stops the hole he creeps in and out at with leaves: he mostly keeps in his hut,
but sometimes walks before it; lies on the ground, and cannot be persuaded to work much,
nor without violence, to forsake this habit, which he appears to delight in,
and enjoy full health.
When the woods and orchards afford him no nuts, apples, or other relief as to food,
he applies now and then for bread to the neighbourhood, and with that is quite satisfied;
he refuses money, but has been frequently clothed by charity:
he seems to be upwards of forty years of age (now sixty,) as to
person rather under the middle size--calls himself Francis.`"

After meeting at Mount Holly, which was low, went to Evesham,
and lodged at William Foster's, a justice of the peace.
After meeting at Evesham,
went to the house of our ancient friend and minister of the Gospel Thomas Evans,
and lodged; and from there next day to Philadelphia,
where I met with my dear companion Samuel Neale:
we greeted each other in brotherly love and affection,
and were pleased to see one another in the enjoyment of health and peace.
On the 18th was at London Grove Quarterly Meeting, which was large,
and owned by the Master's presence to our mutual comfort and strength:
his works praise his name!
John Churchman, William Brown, John Pemberton,
and many other men who were in the ministry,
besides many women Friends in the like capacity, attended on this occasion.
The next day returned to Philadelphia,
where I continued my friendly visits to Friends' families,
and prepared myself for embarking to Europe.

All things being now got in readiness for my departure, Sarah Morris,
of whom I have several times made mention,
having at length yielded in obedience to what she believed to be her duty,
in paying a religious visit to Friends in England, and having Friends' concurrence,
approbation, and certificate,
it was thought well we should accompany one another over the great ocean.
She had also a kinswoman to accompany her, and though one not in the ministry,
yet was exercised in spirit for the prosperity of Truth,
and having near sympathy with her aunt in her present concern,
gave up to attend her in her said undertaking: her name was Deborah Morris; and, indeed,
I thought her an excellent mother, raised up in our Israel.

On the third-day of the week, being 3rd of third month,
we had a short but weighty sitting together in
the house of our dear friend John Pemberton,
to which place many were gathered, in order to take their last farewell;
it was a time of love, wherein our minds were much affected,
and our spirits broken and contrited before the Lord,
who was pleased to bless us together; in this heavenly frame,
we took our leave and parted!
Several of our kind friends from the city accompanied us to Chester,
the place where we were to embark, Samuel Neale, John Pemberton,
and I suppose more than thirty in number:
after we had taken some little refreshment at Chester,
we retired into a humble awful reverent waiting, which was again graciously owned,
and crowned with heavenly life and power.
After thus taking our farewell of our dear Friends,
many of whom went with us to the brink of the waters and then returned,
we set sail on board the Pennsylvania packet, Peter Osborne commander.
The nearness of unity into which I was brought with these beloved
Friends and citizens has made deep impressions on my mind,
which I trust will prove lasting, and made it very hard for me to part with them.

We ran aground twice before we left the Capes of Delaware,
and the latter time threatened great danger;
the captain and sailors said there was but
little likelihood of getting the ship off again,
the wind blowing pretty hard.
But the men used their utmost endeavours, which Providence was pleased to bless,
and the ship worked off, but the captain said he hardly knew how:
my soul reverently praises Him who wrought this deliverance for us.
We passed through much stormy weather,
but through mercy were in a good degree preserved in stillness,
trusting in him who has power to still the winds and calm the seas at his pleasure.

About thirty-one days after we left the Capes we got to soundings,
and the next day brought us in sight of land, and on the 10th of the fourth month,
my companions and I landed at Dover,
which time from our going on board was five weeks and three days.
My mind was made thankful for this great mercy and favour,
the Lord's mighty preservation and protection, while on this large continent,
as also on the wide ocean; in consideration of which, my soul praises His holy name,
who is worthy for ever and ever!
The next day I came up to London with my companions,
and was kindly received by our friends and my dear relations.
After two or three days stay in London,
I set out for Norwich on the 15th of fourth month, 1772,
and got well home the same evening to my dear wife and children and friends,
who all expressed great joy and thankfulness at seeing me; and so it was to me,
after an absence from them of about one year and nine months, in which time I travelled,
by a moderate computation, thirteen thousand seven hundred and fifty-five miles.

The End of Joseph Oxley's Journal.

It does not appear that this humble-minded servant of the Lord Jesus Christ,
continued his journal,
or left much if anything on record of his life or religious exercises,
after his return from America.
This sacrifice seemed like the winding up of his day's work,
and was crowned with the sheaves of peace in his bosom,
and the answer of "`Well done`" from his great and good Master,
as to a faithful steward in the Gospel vineyard; likewise,
with the approbation of his friends in various parts of the heritage,
amply expressed by them in their public documents, where his lot had been cast,
as well as in private correspondence.

Of the few additional particulars that have come to hand respecting Joseph Oxley,
the editor has only to produce an extract from the testimonial of his friends,
given forth after his removal by death, respecting his character and latter end;
and to close the volume,
by inserting a letter from his valued companion in ministerial labour and travel,
Samuel Neale, addressed to his widow,
on receiving the intelligence of his release from the probations of time.

"`Joseph Oxley was a man exemplary in conduct, and agreeable in conversation,
honest in advice, charitable in sentiment, universal in benevolence,
deservedly esteemed by his neighbours, and beloved by his friends.

"`A few months before his decease,
he was impressed with a sense that his departure was at no great distance;
and sometimes hinted to some nearly connected with him, that it would be sudden;--yet,
not as fearing it, but rather in a serious and pleasing acquiescence with the prospect.

"`Accordingly, after attending two meetings on first-day the 22nd of the tenth month,
1775, which were held in silence, and spending the evening with his family,
in a disposition more than ordinarily pleasant, he cheerfully went up to bed;
where he laid but a few minutes,
before it pleased Almighty Goodness to take him from the vicissitudes of mutability,
without a struggle,
or passing through the tedious and afflicting pains commonly incident to nature:
no doubt, to him, an easy passage to a heavenly mansion.

"`His remains were interred in Friends' burial-ground at Norwich,
the 26th of the tenth month, 1775, in the sixty-first year of his age,
and thirty-fourth of his ministry.`"

Samuel Neale to Mary Oxley.

Springmount, 19th of First month, 1776.

About a month ago I heard of the removal of my truly near and dear companion,
your dear deceased husband,
whose translation is to a better inheritance
than to continue on this theatre of probation.
A letter from dear Edmund Gurney brought the tidings to Robert Dudley,
and he to me at our last Quarterly Meeting: it struck me with surprise, and yet,
when I consider the man and where he dwelt,
I look upon it only as a remove from a limited Goshen here,
to a Goshen of endless light and duration.
I seldom or ever have known him appear in his vestment, but it covered him:
diffident and humble he was, preferring others before himself.
He waded along with becoming fortitude in his
visit to the churches in America and Ireland,
and was universally esteemed.
In his last moments the great Master unveiled his kindness to him,
in removing him without much conflict or pain,
his spirit escaping from a mansion of mortality
into a mansion of immortality and eternal life,
where he has entered his lot,
and sings with the sanctified the songs of thanksgiving and praise!

Your letter I received two days ago, which I acknowledge as a favour,
and can sympathize with you in the removal of a living branch of your family,
who had not only leaves, but fruit also:
his residence was near the spring which replenished his life,
covered his head in the hour of Gospel labour,
and kept him in the union and fellowship of the faithful at home and abroad.

Dear friend, when I consider how many are called from works to rewards,
it raises a desire, that I may so fill my lot here in the church militant,
as to be ready when the messenger arrives, to give an account of my stewardship,
so as to meet acceptance, and an entrance into the church triumphant.
There are many called, but when made willing to be chosen, something interposes,
dazzling, worldly pomp, splendour, or the cords which allure that way,
and which sink the mind in supineness, stop the ardency of the awakened intention,
and so turn into the wilderness, where many are torn as with the briars and thorns;
and some are corrected, but sustain so many wounds, that they become lame and impotent,
and centre down in an unprofitable state both to themselves and the church,
and the stream of Divine life becomes dried up in them.

May this never be our lot, but may we daily know the girding of the heavenly Master,
keep on the armour that he has once given,
and feel the unction that brightens the shield;
that we may have fellowship with the living; gradually ascending the hill,
where the clean-handed have their residence,
and are replenished with the water that issues therefrom,
that ever did and still makes glad the heritage.
I trust, dear friend, the Lord of living mercies will be with you in your pilgrimage,
sustain you with food convenient, strengthening your bow,
and fitting for whatever he requires.
When we are shaken with an uncommon, unexpected stroke in our experience,
we are like the needle in the compass-box, greatly agitated,
and it will take some time before we settle so as to be able to traverse truly;
but by centering in a state of quietness and acquiescence to the Master's will,
we shall feel the influence of the heavenly attraction,
and our spirits will be directed in the right line of duty,
to our own peace and the Master's praise.

It gives me pleasure to hear how my dear friend's family is likely to settle; and,
if they keep to the saving Truth their worthy father loved, and served, and lived in,
they may be ornaments in their day in the church and in the world,
and inherit his virtues.
My dear love to them, and particularly my friend Joseph,
whose union I trust is established in the counsel of best wisdom;
the reward annexed is righteousness and peace.
I salute you and them in near sympathy and affection, and remain,
in the fellowship of Gospel love,

Your nearly united friend,

Samuel Neale.

The End