[quote.epigraph, , Gen. 53:19]
____
I know him, that he will command his children and his household after him.
____

== Joseph Oxley's Address to his Children.

My dearly and well beloved children, unto whom I send greeting: grace unto you,
and peace from God our Father, and the Lord Jesus Christ.

You are nearer and dearer to me than all things here beside.
Divine Providence was pleased to bestow you on me in the days of my youth,
since which you have been my constant care; and, as you have been increasing in years,
so in like proportion have my cares been increasing towards you.
While very young, you were instructed to fear and worship your great Creator,
and oftentimes directed to him, and to the guidance of his blessed, holy,
unerring Spirit, which, as due regard is paid thereunto,
would lead and guide you into all truth.
This becoming the rule of government of our actions, will make us,
of the children of men, the children of God.
I have not been wanting in bestowing on you a liberal education,
to qualify you for business,
and brought up and settled you in such business
and callings as are in esteem and reputation,
in all which I have had an eye to the glory of God.

As occasion required, I have exhorted, advised, reproved, and restrained you.
You know well that I was exemplary in attending religious meetings,
and you also therein became my companions.
My increasing cares, and laudable endeavours, through Divine favour,
have in some good degree procured for me that blessing,
which above all temporal blessings I have desired,--the
blessing of sober and virtuous children.
It is the all-wise, great and good Benefactor, the Lord, the everlasting I AM,
the Alpha and Omega, before whom my soul seeks to worship at this time,
and with earnestness to entreat,
that he would still vouchsafe the renewings of
celestial rain upon the seed of his poor servant,
that thereby they may grow as plants of the Lord's own right hand planting,
to his glory and praise for ever and ever.

I am now pretty far advanced in years, waiting daily until my change shall come,
having no desire to stay longer than is my Master's good will and pleasure.
In this state of resignation I desire to live, and to live so as to be fit to die.
I trust, in this passage through life, I have not been unmindful of that great work,
unto which I have apprehended myself called;
and when concerns of a religious nature have appeared to be my duty,
have not to charge myself with neglect or backwardness;
but stood in passive submission to be made willing in the day of his power.
Herein, as I was made to give up, I had great peace,
and have no cause to murmur or repine at any of his requirements,
though I thought myself not worthy, not pure enough to run on his holy errands.
I do not know how better to recommend you, than to follow me, my dear children,
in like manner, only in greater degrees of purity.
The more pure and holy and perfect we are made,
the fitter we are to be sent on his errands, and to bear the Gospel message.
In former manuscripts I have recommended brotherly love and unity,
without which there can be no real, true happiness.
The same I again recommend to you.
There is much beauty in beholding brothers and sisters living in love,
endeavouring to help one another as occasion may require,
in counselling and advising in temporal or spiritual matters.
I charge you be not unmindful in so doing, my dear children;
peace will flow in upon you abundantly,
and your reputation and honour will be increased among men.
The Lord will delight himself in you, and you will be a praise to his great name.

My life being attended with variety of dispensations, I have, as opportunity presented,
committed to paper some things, among many that have fallen to my lot,
in the course of my pilgrimage;
not with any intention or desire of its going forth to the public,
but intending chiefly to have it kept within the circle of my own family;
not thinking it better worth.
You will find in the perusal of these few sheets,
the tender dealings and merciful visitations of the Almighty to me,
after long provoking him to anger; by which means,
judgment and condemnation were brought over my soul.
May he who reached poor me when I was gone astray,
and brought back again that which was lost,
in like manner effectually reach the hearts of my dear children,
that closely joining in with the visitation of Truth,
they may at length become warriors and champions in our Israel,
contenders for the God of their father, in their generation;
and the Lord so bless the work in their hands,
that sinners may be converted from the error of their ways,
that souls may be saved from death, and thereby hide a multitude of sins.
In that day the wisdom of God will be made manifest,
and according to the saying of the prophet Daniel,
"`those that are wise shall shine as the brightness of the firmament,
and they that turn many to righteousness, as the stars, for ever and ever!`"
For this great and good end, many have been called into the Lord's work and service,
and their reward shall be according to their measure and faithfulness.

Great is the loss which many sustain who have been long hearing, and not obeying,
being diverted and turned aside by strangers,
of which there are many to delude and enchant; deceivers, and not true,
captivating allurements, called by fine names.
Thus it is, that the creature is exalted above measure,
and is set up in the mind above the heavenly witness;
turning aside the deep counsels communicated from Him who is perfect,
who delighteth not in the death of sinners, but is graciously seeking,
immediately and instrumentally, to save sinners from their sins,
and to preserve them from sinning.
How strange a thing it is that minds should be so infatuated,
as to prefer pleasures rather than peace.
It is by seeking and pursuing after pleasures, that many hearts are wounded and slain;
but they that seek after peace, shall be made peace-makers,
and shall be called the children of God.
The testimonies and labours of the Lord's servants,
tend to bring off from those things that are of a
hurtful and destructive nature and evil tendency,
wounding the poor soul, bringing it into great distress and confusion;
which do not settle it upon a right bottom and sure foundation,
wherein dwelleth true happiness, comfort, and peace.
Thus is an understanding given, not a verbal declaration only;
for the knowledge and Christian experience of such, as have been seeking after the Truth,
and by obedience to its manifestations have found it, and have it in possession,
speaks of what they know, and not of what they know not.
I therefore direct and recommend you to such teachers, and to the teacher of them,
the Lord Jesus Christ in your own hearts, the true and infallible Teacher;
that by attending thereto, you may come in this manner to attain to the like experience,
and in the end obtain your hope, even the salvation of your souls.

Remember my counsel, herein recommended, and depart not from it.
It is what above all things else I covet for you.
