== Chapter II.

I NOW began to have an inclination in my mind to change my condition;
in the prosecution of which, sundry remarkable occurrences befalling,
make it necessary to insert more largely than otherwise I should have done.
A sober virtuous young woman of a reputable family struck my attention:
I weighed the matter very deliberately, and moved as I thought in the openings of Truth.

I had but bare knowledge of the young woman,
but she bore a good character as a religious Friend,
which weighed with me more than any other thing.
I was altogether a stranger to the family and they to me,
which made it a matter of difficulty to get properly introduced,
which at length I did by giving some prior intelligence.
I addressed myself in the best manner I was capable of to the parents of the young woman,
who were both of them then living, and received me becomingly,
and heard me pretty fully on the subject.
They acknowledged the respect I showed to them and their daughter,
in presenting myself in such an honourable and commendable manner,
becoming my profession; but withal signified, however they might be in my estimation,
that I was not so in theirs,
and therefore desired I would desist any further attempt of that sort,
for they should not give their consent,
and hoped I would not do anything that was dishonourable.
I answered them, "`No,
far be it from me:`" and after some little more time and conversation, we parted.
They were people of greater property in the world than I expected or thought of,
and probably that might be some objection.
I returned home somewhat disquieted, lest whilst I thought I was doing right,
I had done wrong.
But even to this day I believe I did right according to the best of my judgment,
and remained without condemnation:
and at night I laid myself down to rest with a sweet composed mind.

Parents and children should be careful not to
thirst too much after the love of the world,
but above all things seek first the kingdom of God and his righteousness,
and those things shall be added unto you.
Young people, who are sober and religious and withal industrious,
are to be preferred to those that have worldly riches
without the other necessary qualifications.

I had strong inclinations once more to go into the
country to see my ancient and honourable grandmother,
Catherine Peckover, with the rest of my relations;
and to save expenses I travelled on foot, which fatigued me very much.
But when I got there, I found a very kind reception,
and very comfortable was this visit to me.
After being here a few days,
my dear brother proposed my staying and settling in the country, which I liked very well,
if my friends would be kind enough to assist me, without which I could not;
nor had I courage to ask any such favour,
and had but little to expect from such a proposal, considering my past conduct.
But my brother was very pressing that it might be so,
and was the chief and principal instrument in bringing it about,
which was at length effected, but not without some difficulty.
I was bowed in awfulness and in thankfulness to the great Master,
who was pleased to open the hearts of my Friends for my help.
I then hired a little shop at Fakenham, and was to board with my grandmother,
who seemed more than commonly pleased with the thoughts of my company,
and I not less so with the thoughts of hers.
After a short stay in the country, I returned again to London to settle my affairs there,
and to furnish myself with what was necessary for my little shop;
which I did in the best manner I was capable of,
not having a larger capital than thirty pounds, and that not my own.
Before I left London,
I requested a certificate of removal from Peel
Monthly Meeting to that of Fakenham in Norfolk,
which was granted me, signifying my life and conversation were sober and orderly,
that I was clear in respect of marriage,
and recommending me to the care of the said meeting.
Having forwarded my things, and taken leave of my friends in town,
with many of whom I had sweet and precious unity, I returned into the country,
about the middle of the year 1741.

I was greatly pleased with this change of life,
as I never before knew what it was to live so comfortably.
After a time, I got my little shop furnished and myself agreeably settled.
I had now to consult with my grandmother how I should
conduct myself during the time of our week-day meeting,
my shop standing by itself: without hesitation, she soon advised me what I should do,
and that was, when the meeting day came, to shut up my shop, "`for,`" says she,
"`thy grandfather and I did so, and when we returned from meeting,
generally found many customers waiting for us,`" and believed they never were
sufferers by shutting up their shop for the sake of going to a religious meeting.
I immediately joined in with my grandmother's advice, being of the same judgment,
and sweet, comfortable, edifying meetings we had,
such as I trust will make long and lasting impressions on my mind.
I thought nobody could be happier than I was, settled in the midst of my relations,
among whom there dwelt so much love and harmony.
I had hitherto been brought up and educated at a
very great distance from my brother and sister,
but now kind Providence so ordered it,
that we were all settled within the compass of a very few miles of each other:
so pleasant was my situation,
that I thought I should not desire to have a better settlement in this world.

But the Lord our Maker, the Creator of the ends of the earth,
who has given us these blessings, for a time and season,
that we might be one another's in him, knows best when, by his ordering hand,
to take away as well as to give; and it behoveth us as finite beings,
to live in fear and in subordination to his all-wise providence, and to say,
"`Thy will be done.`"
When I had lived thus happily about three months, my dear grandmother was taken ill,
and grew weaker and weaker, and in a little time was confined to her room.
As I was one day sitting by her, she spoke very awfully of eternity,
and what a solemn thing it was to die, and said unto me, "`My dear,
I would have thee to be faithful to that which it may please the Lord to require of thee.
It may be that thou mayst have to bear a testimony in this place; and if it should be so,
I would have thee to be faithful to it.`"
She continued but a few days longer, and quietly departed this life,
in the seventy-fifth year of her age.

The following is a testimony from the Monthly Meeting of Wells, in Norfolk,
concerning her.

"`We think it incumbent upon us to say something
in commemoration of so good and valuable a woman,
counting it no small blessing to the churches in these parts,
wherein she continued from about the twentieth year of
her age to her departure out of this life,
and was all along a very serviceable and honourable member amongst us.
Her many excellent qualifications, attended with a meek, humble,
reverent deportment in all respects, rendered her very near and dear to us.
It pleased God to bestow upon her a gift of the ministry,
to which she was faithful and very exemplary in waiting on it,
delivering the matter she had to say with much plainness and brevity,
being attended with great power, to the no small edification and comfort of the churches.
Her life and conversation well corresponded with her doctrine,
and she was much respected by people of other societies:
she was very charitable and full of good works,
her delight was to be found in practices becoming the Gospel,
and she was an eminent pillar amongst us, a worthy mother in Israel,
and a great ornament to the Society.

She received the Truth whilst very young, and with her honourable mother,
was imprisoned for her testimony thereunto before she was sixteen years of age,
and undauntedly confessed the same,
and pleaded for it in her examination before the judge in court,
being the first called to answer to their indictment,
though there were upwards of sixty persons then present upon the same good account,
and she the youngest of them all.
She conducted herself with such modesty,
giving pertinent reasons for her joining with her
friends in assembling together to worship God in spirit,
etc.; and refusing her liberty on terms inconsistent with her religious profession,
as drew from the court no small attention and surprise: and it was so ordered,
that she with her fellow-prisoners were all set at liberty.

This she would afterwards often mention,
with great sweetness and gratitude of soul to the Divine hand,
by which she was supported to hold out to the end of her days,
in a constant dependence on that arm of power
which gloriously visited and wrought upon her.
She retained the sense and savour of Truth in as
precious and lively a manner as in the beginning,
it being very frequent for her to express the same in her living ministry amongst us.

Much more might be said concerning this our worthy friend, but we study brevity,
being nearly affected with her removal from us, which though it be our unspeakable loss,
we doubt not is her great gain,
and that she is centered in the holy mansions with saints and angels,
and the spirits of the just made perfect.
She departed this life at her own dwelling-house in Fakenham, in the said county,
on the 1st day of the eighth month,
and was attended to the grave by great numbers of Friends and others.
She was born about 1666 and died in the year 1741,
and was a minister about forty-six years.`"

I was very much affected by this great loss, both in respect to my outward settlement,
and because my grandmother was a choice companion and counsellor;
yet I found my duty was to be still, and not to murmur,
but to put my trust and confidence in the Lord, in whom there is everlasting strength.

I continued to live in the same house; and as my uncle, Joseph Peckover,
and aunt lived in the same town, they were very kind to me,
and I believe had an esteem for me.
There was a care on my mind, that as I believed in the Truth, I might also walk in it,
that being a good example I might be an encouragement to others;
and as I was honest before the Lord, he was pleased to increase these desires in me,
and to bless me with the aboundings of his good Spirit,
by which I was often comforted in religious meetings more than formerly.
I was glad to experience this, and that my removal from London into the country,
and from a worse to a better living, as to the outward, was not to my spiritual hurt.
It was not long after this, that I found myself uncommonly exercised in meetings,
but had not liberty to say to any how or in what manner my exercise was,
as I thought it might wear off.
I had great and weighty ponderings of soul,
fearing lest I should be drawn into delusions through the craftiness of the enemy;
but still trusted, that the Lord would not suffer me to be deceived by him.

About this time, my dear uncle Edmund Peckover,
laid before our Monthly Meeting a concern which
had been on his mind for a great many years,
to pay a religious visit to the churches in America,
and requested our approbation and certificate.
It was a singularly moving time, and almost the whole meeting was broken into tears,
so deeply exercised was all within him for the cause of righteousness,
and for the prosperity of our Zion; he spoke with Divine power and authority,
and the Lord's love and gracious regard was largely manifested to us that day.
My brother carried on his business till his return,
which I believe he did as a faithful and just steward;
and the Lord has richly and plenteously rewarded and blessed him for it,
for which my mind is made humbly thankful at this time.
All things being in readiness, divers of us went as far as Swaffham, twelve miles,
at which place it was agreed,
that Joseph Ransom and I should continue with him up to London.
For which purpose, Joseph Ransom and I turned back, after we had rode a few miles,
to get some few necessaries for our journey,
and returned to our company as expeditiously as we well could.
We found they had dined at Swaffham and gone from thence: still moving forward,
we saw them at some distance, going but a foot's pace and in much stillness.
The nearer we approached, the more awful and solemn they appeared:
when we got up with them, we found they were all retired into silence,
and our spirits were also gathered and united with theirs in the holy solemnity.
In this manner we continued some time, and then dear uncle made a full stop,
and so did all the rest, and alighted from our horses;
uncle being filled with the power and love of God, kneeled down on the wide heath,
and supplicated the Almighty with fervency of spirit,
and we were all so affected and reached by the power of Truth which was over all,
as was to our inexpressible joy, consolation and comfort.
This was a renewed confirmation to our dear uncle and us,
of his concern being grounded upon a right bottom.

I never at any time felt and enjoyed anything to the like degree as this;
it was to us at that time, even as if the very heavens were opened,
the fragrancy thereof remains sweet in my remembrance to this day!
In this heavenly frame, we saluted one another,
whilst tears plentifully trickled down our cheeks:--we knew not how to part,
and yet it must be; -- thus in much brokenness and contrition of soul and spirit,
we took an affectionate leave one of another; but indeed, we were so overcome,
as to be almost past utterance!
After some little time more, we mounted our horses and turned our backs one upon another,
the heavenly virtue still remaining with us,
Joseph Ransom and I accompanying him towards London,
and the other Friends and relations homewards.
When at some distance, he turned about,
to take another look of his relations and Friends, and they also in like manner,
shaking their heads and waving their hands, with hearts full, bidding farewell:
and even whilst he sorrowed, he rejoiced!
So we passed on our journey filled with Divine love,
that it was some considerable time before we fell into any conversation.
He had two public meetings at Hertford,
besides a few Friends gathered together in the evening to take their leave,
and a memorable opportunity it was, owned by the Master himself,
whose living presence was experienced to our comfort and edification.
Having conducted him safe up to London, he went on board the vessel soon after,
and I returned with the plenteous reward of peace in my own bosom,
for having attended this good man so far on his journey.

