== Chapter III.

To return to the close and weighty concern which
I found on my mind in religious assemblies.
This would sometimes bring before my remembrance,
what my grandmother said to me a few days before she died,
at which I have already hinted; a great dread would often attend me,
lest I should too readily engage in an office for which I was not sufficiently prepared.
I besought the Lord day and night with cries and with tears,
that he would be pleased to be with me in the way that I should go,
whatsoever I might suffer as to the outward; and, blessed be his great and holy name,
I witnessed him to be as a shepherd, who "`gathereth the lambs with his arm,
and carrieth them in his bosom, and shall gently lead those that are with young.`"
And in the work and operation of this great duty,
I found the gradual and gentle drawings of the Divine Leader,
who requires no more of us than he is pleased to give us power and strength to perform.
Great was his love, and manifold his tender mercies towards me,
in forming and fashioning me according to his holy pleasure.
Notwithstanding all this tender dealing and gentle leading,
when the time came that I was fully convinced of what my duty was to do,
I was very unwilling and loath to comply with the requiring,
and entreated with the greatest earnestness that I might be excused; and was afraid,
when the meeting day came, lest a concern should come over my mind to say something.

In this state I continued long, until by sorrowful experience I found,
that the Lord was angry with me, and withdrew his loving-kindness from me;
then was I in great distress of mind, and said in secret,
If I might but enjoy his Divine presence as I had formerly done,
and the like concern should again befall me, I would certainly be faithful.
And the Lord, who retains not anger for ever,
was pleased again to restore me by his grace, and condescended to my petition.
Soon after, I was tried in like manner as heretofore;
and notwithstanding what I had already undergone in time past,
in bringing his displeasure over me for my disobedience,
and the clear evidence I had in my own mind of the certainty of the concern,
and that it was no delusion nor work of the enemy,
all this would not work a compliance in my hard
heart even to do what I knew was my duty to do,
and so I suffered the meeting to break up again,
being in a state of disobedience and unfaithfulness.
As it was in the cool of the day, when the Lord called unto Adam and said,
"`Where art thou?`"
so in like manner, when I was come from meeting,
and settling myself amongst my outward concerns of life, the piercing cry of,
"`Where art thou?
overtook me,`"--with, "`Vengeance is mine, and I will repay it, saith the Lord.`"
It is not an easy matter to describe the state of my mind, the distress of my soul.
Formerly I had been favoured with the love of God,
but these times and opportunities seemed now to be at an end,
the fruitful field was turned into a wilderness,
briars and thorns and nettles were spiritually brought forth in me, as scourges,
to chastise and punish for my wilful neglect, omission, and transgression.
Day was turned into night, and this night was a continued distress of soul.
Light was become darkness; I think no pen can write, nor tongue describe what I underwent.
He laughed at my calamity, and mocked when my fear came: when I went to meeting,
instead of Divine approbation and love which I used to feel,
I was condemned and reproved: "`I will not hear the melody of thy viols.`"
In this dark lost state I remained long;
and when the fierceness of his anger was somewhat abated,
I was far from enjoying comfortable meetings as before,
but sat in much drought and barrenness,
and had not power to lift up my spirit to ask forgiveness of him whom I had offended.

At length it pleased the Lord,
that we were favoured with a religious visit from our dear friend Elizabeth Dennis,
whose company was truly acceptable: it was my lot to be guide to her to the next meeting,
and on our way she spoke many comfortable things concerning me,
as that I should come up in acceptable service in our religious Society, etc.
I did not hide my state from her, but gave her to understand, that I thought not,
for I feared the Lord`'s precious visitation to my soul was over,
in that I had withstood the day wherein I was called,
and that I never expected the like call any more.
But she said, "`Yes;`" and that she was well satisfied it would be so.

This was to me a joyful message, and I now began rather to revive,
and hope sprang in my mind,
that the Lord would once more favour me with the
lifting up of the light of his countenance,
and I found by degrees his displeasure wear off.
I suffered so much in this state,
that now I only wished and desired if it might be his will, he would please to accept me,
and I would willingly serve him,
if I could but have those former and precious
visitations of Divine love and life revived.
I experienced my religious meetings to be more still and quiet than heretofore;
and after considerable time I felt a gradual increase of the Divine love and life,
of which my poor soul had long been deprived: I now only waited for a fresh commission,
and strength to do what his will commanded.
Blessed be his great name,
who had made me as passive clay in the hand of the potter! for, of a truth,
I had learned to say, "`Thy kingdom come,
thy will be done:`" and being now fully given up,
the Lord was pleased to renew his tender visitations to my soul as formerly.
I was constant in attending meetings,
in which divine favour was abundantly communicated and experienced.
I escaped for some time being tried in this very great duty;
for although I was fully given up in my mind,
yet I was to be mindful not to be too forward,
for that I thought would be as bad or worse than being too backward.

About this time, we were favoured with the company of Daniel Badger,
a Friend in the ministry,
whose service was attended with demonstration of the Spirit and with power.
In this meeting, I found my mind afresh baptized into the service of the ministry,
and though I said nothing at all,
yet I was well satisfied I bore my testimony in standing uncovered,
trembling before the Lord and his people; and if anything had been given me to say,
I should certainly have spoken it, whether little or much;
however I had great peace in this first and foolish appearance.

I now thought myself again restored into Divine favour,
which was more to me than great temporal riches;
and began to think that nothing more of this kind might befall me,
and that what I had done was only for a trial of my love and obedience;
for it was some time before anything of the like kind was again required.
But on a certain time, when Mary Goodwine, a young woman in the ministry,
was on a religious visit to us, it was my lot to conduct her to Wells,
which was the next meeting,
and there again I found the concern came very powerfully on me;
and I sat the chief of the meeting under an exercise of supplication,
which in faithfulness I gave up to, and most in the meeting were remarkably affected;
which I do not mention boastingly,
but it was a confirmation that I was right in this weighty undertaking.
And though, in this great duty,
I acknowledge myself to have been backward even to unfaithfulness and stubbornness,
yet if it is rightly considered, it is not to be much wondered at,
that the creature should be made to suffer greatly before it
is brought to be altogether passive to the heavenly will,
and fit for`' the Master`'s use.
How awful was the work which the Lord wrought by his servant Moses,
and great the pleadings he made as to his unworthiness and unfitness in divers respects.
Notwithstanding the Lord suffered his servant to reason with him,
yet he continued it so long, that the Lord was angry with him;
though he so remarkably manifested to him his greatness and power and authority,
with visible signs and tokens, beyond all imaginations and doublings;
by which Moses was to understand,
that although he was but as the rod or twig which he had in his hand,
yet at the Divine command it could be turned into a serpent,
to strike terror into such as lived in defiance of his holy will.
So plainly did the great Master condescend to his servant,
that at length he was brought into a compliance with the Master`'s will;
for I think the Holy Scripture gives this testimony concerning him,
that "`Moses did as the Lord commanded him.`"

I continued faithful in that which appeared my duty;
and whilst very young in my ministry,
had drawings in my mind to pay a religious visit
to Friends in Lincolnshire and Yorkshire;
and a Friend in our county having somewhat of the like concern,
I thought it a good opportunity for me to shelter myself under him,
if it could be so ordered.
Accordingly, I paid a visit to the Friend, signifying to him the engagement of my mind;
which proving very agreeable to him,
I then took the necessary steps in settling my business,
and sought the unity of my friends and relations,
with the approbation of my Monthly Meeting, from whence I obtained a certificate.

On the 26th of third month, 1743, I set forward on my journey from Fakenham to Lynn,
at which place I met my companion, John Norris, of Mattishall;
and we had a meeting there that day.
A very hard meeting it was,
and the occurrences that befell us in the course of our
visit to this meeting were very discouraging,
and had not the power of God been near to support against all the contrary,
I must have returned wounded in the first engagement: at length we parted friendly.
We had a meeting next day at Wisbeach to more satisfaction;
and from thence to Gedney in Lincolnshire,
where we witnessed the Lord`'s power to our great comfort.
The next was Spalding, and so to Boston; had a large, good meeting,
chiefly of other societies.
We passed to Wainfleet the next morning, and in the evening at Partney,
and had meetings there and at Waltorn the day following;
at which place the Lord was graciously pleased to shower down his Gospel rain upon us,
causing us to bring forth fruits to his praise.
On first-day, being the 5th of the fourth month, were at Brigg;
and in the afternoon had a good meeting.

The hearts of the people were opened,
and I hope drank in that of which their souls and ours stood in great need.
I cannot well forbear mentioning,
that about twenty years ago this was one of the most flourishing meetings in the county;
about fourteen ministering Friends belonged to the said particular meeting.
But since that time,
it hath pleased Infinite Wisdom to call most of them to their long homes,
and divers through unwatchfulness grew cool,
and instead of contending for the saints`' victory, settled down in spiritual indolence;
and a slothful spirit prevailing,
many of their members turned their backs on the Society,
many married contrary to the rules of our wholesome discipline,
and became ruined as to religion, and otherwise falling into divers hurtful lusts,
lost their credit and reputation as to the world:
so that now the meeting is declined from being one of the largest,
to be one of the smallest in the county.
I am sorry I have no better account to give of my native place.
It is a great pity that any who have attained to a good state in religious experience,
should depart from it; for as the wise man saith,
"`A good name is rather to be chosen than great riches.`"

On the third-day following went to Winterton, and from thence to Gainsborough.
The state of the Society seems to be at a very low ebb in this place,
and the people grown very indifferent about attending religious meetings.

From thence to Beltoft, and in the evening had a good satisfactory meeting;
then to Thorn, and had our meeting somewhat disturbed by one in profession with us,
but not perfectly clear in his understanding,
yet the Lord`'s power was Over and above all.
It being first-day, had two good meetings,
and in the evening visited the wife of our friend John Fisher,
who had been sorely afflicted for a long season.

Hannah Taylor, a Friend who had a gift in the ministry, was with us;
we had a comfortable opportunity, and our minds were edified in the Lord.
We passed on to Braithwaite, and had a meeting there that evening;
and good was the Master whom we served, in shedding abroad his love in our hearts.
From this place we went to Rawcliff and Holden, and so to Cave and Beverly,
at which last place we had a large meeting,
consisting chiefly of people of other societies,
who conducted themselves with a great deal of sobriety.

From hence to Hull, which proved to us a time of great exercise,
the people very much wanting in the life of true godliness.
The following meeting was at Regement, which was very different from the former,
being a meeting chiefly of living members; our visit there was well accepted,
as many expressed themselves afterwards.
Thence to Welwick, where we had a very good meeting, many were brought into tears,
and others under weighty exercise in themselves.
At Oustwick we were divinely favoured; let praise be given unto Him, to whom it is due,
for all these spiritual blessings!
From thence to Hornsea and Bridlington, which last was trying.
Then to Scarborough, where we had large meetings to good satisfaction:
then made the best of our way to York Quarterly Meeting,
which was well attended by divers Friends in the ministry.

Finding in myself a clearness to look homeward, and James Seaton,
a Friend at this meeting having a concern to visit our county,
we agreed to accompany each other.
So, at York, my companion John Norris and myself parted,
he not being as yet free to return, and took for a companion John Scott,
who was an elder and minister.
James Seaton and myself left York the 1st of fifth month for Thornton,
and on the first-day following went to Holm Yearly Meeting,
where we met with my former companion John Norris, and again at Amberwell,
and had a good meeting together at Huby next day;
then passing to Thirsk we met with a company of noble plants, though young,
and through the mercy of our God experienced a renewal of inward strength.
In company with divers Friends we passed on to North Allerton,
and were again favoured with a heavenly precious visitation,
blessed be his great and holy name for it!
In the compass of this Monthly Meeting a fine
spring of ministry is opened amongst the youth,
within a short space of time.
In the evening we had a meeting at William Proud`'s, to good satisfaction;
from thence back again to North Allerton, and so to Rounton and Richmond,
this latter a very hard laborious meeting, the people being too much settled in form,
and short in the life and spirit of true religion.
Then to Leyburn where things went much better, as also at Masham and at Boroughbridge.
From thence to Knaresborough, Nethersdale, Asquith, Fairfield and Skipton;
at which last place we had a good meeting,
being well attended by ministering Friends and others; and so to William Slater`'s,
who with his wife was exceedingly kind to us:
went to Lothersdale meeting and returned back to William Slater`'s.

The next day had a meeting at Ayton, to our comfort and refreshment,
thanks be given to the Almighty for it! and then to Settle,
where we were kindly received.
After meeting, paid a short visit to our ancient friend Julian Franklin,
very satisfactorily.
In the morning, went to a little meeting at Dibdale, and returned to Starburtop;
had a meeting with the neighbours in the town to good satisfaction,
and set forward to Stainbrigg.
But when we came there we understood the meeting was held at Hawes, three miles distant;
thither we went, and the next day had a heavenly meeting at Askrig,
where the loving-kindness of God was largely extended
to the praise of his own everlasting name.
Next morning to Masham again, my companion not thinking himself clear,
and so to Richmond general meeting.
This was also the more immediate concern of my companion, whom I was free to attend,
as also he was free to attend me to Thirsk,
which place I apprehended it to be my duty to visit a second time,
not having an opportunity of clearing myself when I was there before.
I would have all who travel together as companions in the service of Truth,
to see that they condescend as much as possibly they can one towards the other;
by such conduct they show forth that mutual love,
which ought to live and dwell in companions,
by which they receive strength one of another.
This was a day of great love to our souls,--for
ever blessed be the great Shepherd of Israel,
who at times is pleased to look down upon the low estates of his servants,
and to give them of the new wine of his kingdom!--I wish those here,
who have received a precious visitation,
may be preserved from the many evils that are in the world.

We had two or three meetings at Billsdale in private families, much to our satisfaction;
lodged at Thomas Kendra`'s, a poor but good man, his children sober and religious:
his eldest daughter Rachel came out in testimony at about the age of fifteen,
and promises to make a very useful and serviceable member in the church;
her father also has lately appeared in like manner.
Thus is the Lord pleased to visit by his mighty power, and call in both young and old.

From Billsdale we came to Hutton-in-the-Hole,
at which place lived our worthy and honourable friend and minister of the Gospel,
John Richardson: we staid here two nights,
and were greatly benefitted by this good man`'s company and conversation:
he accompanied us to Kirby Moorside, and had a meeting appointed for the towns-people,
which proved pretty satisfactory.
On the first-day following, being the 1st of the sixth month,
our aforesaid worthy friend, John Richardson,
with several others accompanied us to Pickering,
at which place and on this day a meeting is held once in the year,
called a Yearly Meeting,
to which there is a general resort of people from many miles round:
it was computed there were assembled on this
occasion between three and four thousand people.
The Lord was pleased to favour us with a good opportunity,
and his living presence was over and above all, to the praise of his great and holy name.

After meeting we went in company with George Mason to his house at Fadmore,
and next day to Farndale, to the burial of John Peacock,
and I trust it was a season of mutual edification.
Then we passed to Wellbourn and to Whitby,
where Divine favour again owned us in a wonderful manner:
the next day to Thornton and so to York.
On the first-day in the morning the work was hard and laborious,
but in the afternoon Truth sprang up and got the victory, and a blessed meeting it was:
let the praise thereof be given to Him who alone is worthy!
We should not have returned to this city again; but when there, at the Quarterly Meeting,
not being faithful to what I apprehended to be my duty, I was,
for the sake of peace to my own mind, necessitated to return,
which step I found profitable to me in my future deportment.
Finding the work which had been weightily on my mind to wear gradually off,
I bent my course homewards, journeying through Lincolnshire.
I found my business in my absence had been conducted very agreeably,
and my relations and friends generally well.

Some time before I set forward on this journey I had it
on my mind to change from a single to a married life:
I had acquainted my brother where I had made my choice,
or rather where I thought kind Providence had chosen for me;
but I must first serve my great Master in this present duty and requirement,
and in so doing there might be the better hope of his
blessing to attend and prosper me afterwards.
I found in the course of my journey,
this pre-engagement of mind was a great preservative and stay to my affections,
from looking after anything of the like kind.
Some under the like travel, it is to be feared,
for want of keeping themselves with watchfulness in this particular,
have hurt the work and service to which they have been called;
which service is altogether sufficient to attend to,
and nothing else ought to take up our minds,
lest thereby it should prove ensnaring to us,
and an hindrance in the performance of our religious duties to God and his people.

After being at home some time, I acquainted my relations with my intentions,
and requested their approbation; which being agreeable to them,
I set forward with my uncle Joseph Peckover, whose hearty concurrence I had,
to pay my respects to Elizabeth, the daughter of Edward Fenn of Norwich,
a man truly valuable and honourable in our Society, and generally beloved of others,
a lover and possessor of peace, an Israelite indeed, in whom there was no guile;
and his daughter a virtuous, prudent young woman.
Having obtained the consent of the good old man, I was by him introduced to his daughter,
and after paying sundry visits, there appeared some probability of succeeding.
I had again to consult my uncle concerning where I should settle,
for my business at Fakenham I thought scarcely sufficient;
but I proposed to my uncle who was in a very large business,
that if he would please to turn over an article or two of his business to me,
it might do, and as but few Friends lived there, I thought it might be agreeable.
But this proposition not being approved, I turned my thoughts about settling at Norwich,
and requested of my intended father-in-law to ask counsel of Norwich Friends,
which he did.
It was their united judgment that I should come and settle at Norwich,
which I did soon after, and boarded with my intended father-in-law till my marriage.
This took place on the 28th day of the then fourth month, called June, 1744, at Norwich,
in a very large and solemn assembly of the people called Quakers and others,
where the Lord was pleased to favour us with his divine and living presence;
blessed and for ever praised be his great and holy name,
who was pleased to bestow on me one of the best of women and one of the best of wives.
