== Chapter IV.

About this time my uncle Edmund Peckover returned from
his religious visit to Friends in America,
to the joy and rejoicing of many.
After I married, I continued pretty close at home at my business,
but not to the hindrance of my service.
I visited meetings in and about our own county, and parts adjacent,
as concern and freedom led me; till the year 1750,
when a concern came over my mind to visit some meetings in and about London,
and in some parts of the west of England, of which I acquainted my dear wife,
which pretty closely affected her,
and proved a greater trial to her than I believe either she or I expected,
which I attributed to the great love and affection she had for me.
As she seemed loath I should leave her, I said to her, "`My dear,
I perceive thy unwillingness to part with me, and I hope I shall be made easy to stay,
and the concern wear off:`" here I rested the affair for some time,
having great peace in my own mind, in that I was so freely given up in my own particular.
But it was not very long after,
that my poor wife began to grow uneasy in herself with what she had done,
and I believe kept it as long from me as she well could,
and when she could keep it no longer,
she said she hoped I would forgive and excuse her conduct in offering to stay me at home,
when she believed it was my place and duty to be elsewhere in religious service;
that it was her great love for me, and the trial was so great,
that she said she did not know how to give me up.
I was not hasty in saying anything to lessen the present exercise of her mind,
believing it might be for some good, both at the present, as also in time to come.
And so I recommended her to wait in patience and stillness,
and feel after the renewings of Divine favour,
that she might be the better enabled to judge whether I was right in my concern.

She cried bitterly, and with great earnestness said, "`O, my dear husband,
I entreat thee to forgive me: I am so distressed in mind, that I know not what to do:
I hope I shall never offer to hinder thee any more on the like occasion.`"
"`Now,`" said she, "`I freely and willingly give thee up,
and desire by all means that thou wouldst go,
for I believe the Lord requires it of thee.`"
I then did all I could to pacify her, and to mitigate her distress of mind,
which I was sensible was very great.
So herein the wife had a part, and the husband a part;
and I trust it is or ought to be with all husbands and
wives who live in love and in the true fear of God,
as through divine favour we were concerned to do,
and were preserved in that in which the true unity stands.
I then made the necessary preparations,
in which my dear wife was very assiduous and willingly helped forward;
and I laid my concern before our following Monthly Meeting,
in order to obtain a certificate, and they having unity with me, granted one.

I was favoured in this journey to be companion to my dear uncle Edmund Peckover,
an eminent minister of the Gospel of Jesus Christ.
All things being ready, we set forward on the 1st day of the eleventh month, 1750:
but when I came to take my farewell of my relations and friends,
especially my dear and loving wife and tender children,
our minds were so affected as is not easily to be set forth.

We were accompanied to Wymondham by my father-in-law, Edward Fenn,
where we lodged that night; early next morning,
my brother John Oxley came to attend us to Mildenhall,
at which place we had a meeting the following day,
and so to Edmundsbury and Saffron Walden, where Truth made way for us,
and the enjoyment of it was sweet to our souls.

Next day had a meeting at Royston, where lived a valuable Friend, Francis Gibson,
whom we visited.
We had a public meeting at Ashwell, to which came many people of other persuasions,
and I believe it was a time of heavenly visitation and favour.
We had also comfortable meetings at Baldock, Hitchin and Hertford,
witnessing the blessed enjoyment of peace for our faithfulness,
and reached London the 14th of eleventh month, 1750.

After our stay in London about two weeks, we took a little tour into the country,
to Uxbridge, Jordan's, Wycombe, and Chesham,
in which meetings my uncle was favoured to the joy of many;
from hence to Hempstead and Alban's, being their Monthly Meeting, which was but small,
yet mercifully under Divine notice, to our mutual comfort and strength.
The next being seventh-day, we set forward again for London,
in order to complete what we further apprehended to be our duty;
and visited all their meetings on the first-days, and also their week-day meetings.
We were favoured to have many good and precious meetings in this city.
O that it may please the great Lord of the harvest to bless the many labours of love,
which have been bestowed on this large city,
and plentifully water the seed which has been sown, that it may take root in many,
and bring forth abundantly, so that many souls may be saved,
and his great name over all praised, who is worthy for ever and ever!

Having it on our minds to pay a religious visit to Friends at Bristol and parts adjacent,
we took meetings in Oxfordshire,
many Friends accompanying us out of London to Maidenhead, where we had a large meeting,
chiefly consisting of the towns-people;
unto whom my companion was led to preach the universality of the love of God,
which had a good effect on the minds of many; and though the meeting held long,
yet the people were very unwilling to disperse.
The next day had a meeting at Reading, which was large, and then to Henley,
both low meetings, wherein I suffered my mind to let in discouragement,
by which I received hurt.
But, at Warborough the next day, the Lord was pleased to dispel those mists and fogs,
and to arise with strength, to the refreshing of my poor weary soul,
and again at Bichester the day following, where was a great throng of other people,
and the Gospel was preached with good authority, to the joy and rejoicing of many.
The next morning we set forward for Banbury,
where we found our dear friend Benjamin Kidd in a very indifferent state of health,
and not likely to continue long.
The removal of so great a minister and so useful a member in society,
will be a very great loss.
We were renewedly favoured and comforted together in the love of our heavenly Father,
though we parted very sorrowfully, believing we should not see one another any more;
neither did we, for he died soon after.
Thus we travelled in the love of God and fellowship of the Gospel from place to place,
till we came to Bristol, where we had several meetings to good satisfaction to ourselves,
and hope to the profit and edification of our friends.
My uncle inclined to go to Bath, and make some stay there on account of his health,
not being very well.
I attended him thither, and after a time he grew better,
and the concern still continuing with him, he travelled more largely.
But not so with me: the concern abated; and as such, I found it my duty to return home;
and after taking an affectionate leave of each other,
I set forward for London by Reading, and in a few days reached home,
and found my family and friends well, and my business reputably conducted in my absence,
having in some degree the evidence in myself that I had pleased God.

I continued at and about home for a considerable time:
my family increasing pretty fast required my diligent attendance,
with whom I took great delight.
As the Lord had been pleased to bless me in a wonderful
manner in a state of marriage for about nine years,
so now he saw meet in the course of his providence to deprive me of that happiness,
in removing from me my beloved wife and sweet companion,
the greatest of all temporal enjoyments.
It was a sharp and a close trial: she was taken ill of a fever,
in which she continued about three weeks,
and departed this life the 15th of seventh month, 1753, aged above thirty-four years.
She completely fulfilled the marriage covenant,
in that she was a loving and faithful wife, an affectionate and indulgent mother,
a wise and prudent mistress, a good friend, and a kind neighbour:
as she was generally beloved in her life,
so in her death she was lamented and mourned for.
She left a sorrowful husband and four small children.
I continued in a state of widowhood about four years;
and though I disposed of my children in the best manner I was able,
yet I lived very far short of that happiness I enjoyed in the time of my dear wife.

I continued in the watch-making business, etc., until my eyes in part failed,
and a Friend in reputation and character, and of considerable worth in the world,
agreed with me to go into business together in the worsted manufacture of Norwich;
and as I became the principal in conducting the business,
I was often abroad on that account, sometimes at London and other times in Holland.

In the year 1757,
finding myself very lonesome and unpleasantly situated in many respects,
I thought a good wife for myself and a good mother for my children,
would in measure make up what I much needed.
For this end I sought the Lord again,
that he would be pleased to bless me as he had done in time past;
and as my eye was to him, I believe that he ordered and directed my steps,
how and where I should choose for myself, and also for my children:
and so in due process of time, I made my addresses to Mary, the daughter of Thomas Burr.
He was a man in good reputation as a minister and elder, at Royston, in Hertfordshire,
open hearted, and generous in his house to entertain ministering Friends.
His wife also was a woman of a good spirit, had an acceptable gift in the ministry,
and travelled pretty much in the unity of Friends.
My dear friend Mary Burr was about forty years of age, well educated,
sober and religious, had an acceptable gift in the ministry, naturally affectionate,
and a great lover of children; and after a suitable time,
we were married at Huntingdon on the 5th of first month, 1757.
I esteemed it a very great mercy and favour,
that I was once more made happy in a state of marriage, with a wife who truly loved me,
but one that never offered to hinder me in any religious service,
whether at home or abroad, far or near.
She was a true helpmeet in religion, and I loved and valued her the more,
because of her service in the church; a woman of a good spirit, not forward,
but of a good courage, and sometimes travelled abroad in the service of Truth,
in which I was not slack to help her.

I continued at home one whole year after I married,
when I found drawings in my mind to pay a religious
visit to Friends in some parts of Leicestershire,
Nottinghamshire, Derbyshire, Yorkshire, and Lincolnshire; and Isaac Grey,
a suitable companion, offered in the like concern.
So I gave up to what I believed to be my duty, and ordered my affairs for this purpose;
and on the 3d of first month, 1758, set forward on my journey,
accompanied by my dear brother John Oxley to Milner.
They usually having a meeting that evening I was free to attend it,
though much fatigued with my journey, which proved to my comfort and satisfaction.
My brother and I parted next morning in great affection; he returned home,
and I went forward to Godmanchester, where my companion and I agreed to meet.

We had a good meeting at Huntingdon the next day, though the fore part of it was low;
at which time was brought to my remembrance what is
written concerning the good old patriarch Jacob,
when he passed over the brook though with his staff only in his hand;
yet when he returned he was become two bands;
at which I received encouragement to hold on my way,
and my companion and I were truly united in the service,
and loved each other in brotherly affection, as becometh labourers in the Gospel.
Our desire was that the Lord would be pleased to be with us, and though we were weak,
yet he was and is strong,
and able to make himself victorious over his enemies by few as well as by many,
and to magnify the honour of his great name by small as well as by great instruments.
The next day we had a meeting at Gedington, which I hope had its service;
things were pretty closely spoken to,
that there might be a due care in each to come up in a
faithful discharge of that gift which is given to profit with.
We went forward to Leicester, Castle Donington, Nottingham, Mansfield, Chesterfield,
and Dronsfield, a small meeting, where a little bread was handed with hard labour.
On the following first-day we were at Sheffield, and had two pretty,
large and laborious meetings; from whence we travelled to Ponlefract, Wakefield, Burton,
Highflatts, and many more meetings in those parts,
wherein we experienced the love of the great Master to flow to his poor servants,
though the state of the church in these parts is very low,
more in form than in substance.
On the 3d of second month, went to Skipton,
at which place my son Joseph was at a boarding-school,
and we were much pleased to see each other.

On first-day, the 5th, we were at their meeting; my companion was wholly silent,
and I was led in a very close manner,
signifying how eminently they had been favoured in an instrumental way,
and yet were not bringing forth fruits meet for repentance.
On the 8th went to Lothersdale,
lodged at William and M. Slater's. William was above ninety years old,
yet retained a lively sense of Truth; we had a meeting at the meeting-house,
and another with them at their dwelling in the evening,
the latter was exceedingly comfortable, the Truth was extended to all and over all,
blessed be the Lord for ever!
Fifth-day, the 9th, had a meeting at Satterforth, at which place I was much indisposed.

Seventh-day was a little better, had a meeting at Moneybent, and same day went to Settle.
I yet remained very unwell: next day, being first-day, the 12th,
I was favoured whilst I was at meeting with a fresh degree of Divine love,
and my spirit was brought into a sweet heavenly calm,
by which my inner man was so comforted and strengthened,
that I became truly resigned to the Lord's will,
it appearing to me as if my peace was made with him.
May I ever live under a sense of his divine mercy, and regard to my poor soul.

+++[+++This coincides with a similar expression in a letter to his wife, dated Settle,
14th of second month, 1758, namely, "`Although I am low in body and mind,
I am strong and rich in faith;
greatly rejoicing in the warfare in which I am now afresh engaged.
The answer of peace and well done still accompanies me from day to day.`"]


On fifth-day I had a meeting at Hawes; the state of which was low:
and the day following had one at Garsdale to good satisfaction.
Lodged at the widow Harker's, a poor but honourable woman, who nursed me well.
We found drawings on our minds to Westmoreland, to take some meetings there;
and accordingly set forward next day.
After being clear of those parts, returned into Yorkshire again,
and got to York on third-day, the 26th. In the evening,
began their Quarterly Meeting of ministers and elders:
next morning was a meeting for worship, in the afternoon a meeting for discipline,
and in the evening public meeting for worship,
in which I was concerned in a short testimony,
exciting the people to a humble gathering and waiting for Divine and heavenly teaching:
the meeting was held pretty much in silence.
Next day, being the fifth of the week, was another meeting for discipline,
which was to pretty good satisfaction; in the afternoon another meeting of worship,
in which several testimonies were borne, but the true seed was under much oppression.

After this meeting, the ministers and elders retired into a room by themselves; when,
if anything further was necessary to be communicated, either in word or doctrine,
it might be then and there given.
Mercy Bell, who was present, concluded this meeting in supplication.
My companion, Isaac Grey, thinking himself clear, and desirous of returning homeward,
left next day, being the 31st, intending for home without appointing any more meetings.
But I could not find myself so at liberty;
and endeavoured to make myself as easy as I could without my companion,
hoping the good hand of the Lord would still be with me, as he had not hitherto failed,
blessed be his name for it!
The same day I had a meeting appointed at Thornton in the Clay,
and returned in the evening to York.

+++[+++After attending a few more meetings in Yorkshire, Joseph Oxley proceeded homewards,
through Lincolnshire, taking meetings as he went.
At Brigg he remarks,]
We were informed of a man being in town under the character of a Friend:
I soon made out that he was not in unity; a man of a forward spirit,
and very weak capacity.
We were much afraid of having our meetings on the first-day disturbed by him.
He, in his own forward and weak mind, invited many to the meeting,
and many through his invitation came,
it was judged with intent rather to mock than to profit thereby; but,
blessed be the Lord, who was with his poor depending children,
though we had much of the rabble, Truth kept them in good order:
the Gospel was preached freely, all was quiet and still,
and the Truth was in dominion over all, praised be the Lord for ever!

Fourth-day, the 26th of fourth month,
I now apprehended I had done all that was required of me,
and returning home I felt sweet returns of peace flowing in my bosom beyond measure,
my heart was abundantly comforted,
in which melody of soul I thanked and praised the Lord for his great goodness.
I had the happiness of finding my wife, family and relations well,
and we received one another in the same love in which we parted.

I was now favoured to stay at home with my family,
taking the necessary care for their support;
yet when I felt my mind drawn to pay a religious visit to any meeting
or place I was very careful not to let business hinder me.
After continuing at home about two years, my mind was under a fresh exercise and concern,
to make a like religious visit to Friends in Essex and Hertfordshire;
and as in times past,
I carefully settled my temporal affairs and sought my Friends' approbation;
and having their concurrence and certificate,
after taking a solemn and affectionate leave of my dear wife and children,
I set forward on the 6th of fourth month, 1760, to Diss.
It was their general meeting, which was very large;
but not so much to satisfaction as could be desired, on account of many unruly comers,
not of our profession,
who seemed to come more out of vain curiosity than for edification.
Cousin E. Peckover attended me to Woodbridge,
it being their Quarterly Meeting for Suffolk, and was in a good degree to satisfaction.

On fourth-day I set forward,
accompanied by my uncle Jonathan Peckover and Richard Brewster, to Ipswich;
at which meeting was Elizabeth Roberts;
and the Lord was pleased graciously to own us with his life-giving power and presence,
greatly to our comfort and inward refreshment.
I quartered that evening at John Head's, and in the morning was conducted to Manningtree,
where live our much esteemed friends Elizabeth Kendall and Mary Bundock,
valuable women in ministry and conduct: they received me very cordially,
and the next day was their weekday meeting, wherein my spirit was deeply exercised;
the Lord's blessed power and spirit was prevalent,
and the meeting concluded in prayer and praising his great name.

The same evening I went home with Matthew Swindale,
a man truly valuable for his innocency and simplicity,
and as such is worthy to be called an elder in our Israel.
The next morning he conducted me to Colchester;
and on the 13th we with several Friends set forward to Oakley,
at which place is a meeting held about twice in the year.
This meeting was very much incommoded by reason of rude people and children.
I had to warn them from the dreadful consequences that
befell the children who mocked the Lord's servant,
the prophet Elisha,
and afterward to invite them that they might
seek the Lord whilst he in mercy was to be found,
etc. that, being brought into a state of repentance and amendment of life,
they might find mercy with Him whom they had much offended.
The meeting ended in supplication, and I hope it was profitable to many.
After taking some refreshment went to Manningtree,
and from thence the next day with my friend John Kendall and his mother to Colchester;
in my way thither a post-chaise boy turning very suddenly upon me,
the hind wheel went over my mare's hind foot, by which she was so hurt and affrighted,
that I feared she would be spoiled, and being new and handsome it gave me some concern:
she soon got the better of it,
but I was reminded by this not to like my mare beyond what I ought,
because that would create too much care and concern.

Second-day I staid at Colchester, and visited some families of Friends.
Third-day had a meeting at Coptford, which was large,
being attended by pretty many Friends from the city: the meeting was hard and laborious;
after which I went with Joseph Docwra to his house,
and on fourth-day had a meeting at Kelvedon, which was more to satisfaction.
This evening I went with Robert Ludgater, an elder whom I think very honourable.
Next day had a meeting at Halstead,
where I was met and accompanied by my friend John Drewett,
and the next day at Coggeshall, where the true seed was in great oppression.

On the first-day following at Colchester,
the morning meeting was open and to edification,
the afternoon one more close and shut up.
Had a more public meeting in the evening, which was to a great degree of satisfaction.
I was favoured at this place with the company of
my towns-woman and fellow-labourer in the Gospel,
Hannah Lucas, also Ann Homing of Ipswich,
both valuable instruments in the hand of the Lord,
they being then on their return from London on a religious visit.
Third-day was at an appointed meeting at William to good satisfaction;
the same evening at Maldon, wherein I was silent.
Fourth-day had a meeting at Braintree, which was large,
but a very long time in gathering,
the inconsistency of such a conduct became the subject of my testimony.
This evening to Joseph Smith's, who in the morning accompanied me to Chelmsford,
as also his wife and Hephziba Smithies, both in the ministry:
the labour and exercise of the meeting that day was very trying to
those that were rightly concerned for the prosperity of Truth,
and unto these the Lord was pleased to open a spring of
comfort to the refreshment of their travailing souls:
the meeting concluded in supplication.
Lodged at Stephen Levitt's,
our friend John Griffith being at that time from
home on a religious visit to Friends in Ireland.
Next day held a meeting at Felsted, which was drowsy and dull;
the people were called to and warned,
lest they should settle in a state of carnal ease and security,
and so be like the church of old, which was neither hot nor cold, but lukewarm,
and as such highly offensive in the sight of God.

On first-day, being the 27th of fourth month, was at a general meeting at Stebbing,
where were Judith Clay and divers other Friends in the ministry:
the meeting was large and mercifully favoured.
Third-day was at Thaxted Monthly Meeting, which was small, and the state of it very low.
There were by appointment several Friends on a visit to such as were
unfaithful in their Christian testimony concerning tithes,
priests' demands, etc.

Next day to Saffron Walden, where live many well-disposed Friends,
notwithstanding which it was far from being an open meeting.
Here my companion John Drewett left me; we were very agreeable to each other,
and parted in great love and nearness of affection, he returning homeward for Bury,
myself towards Hertfordshire.
But before I leave Essex, I would just observe, there are many meetings in this county,
and a fine appearance of Friends,
and I do not remember ever visiting a county wherein I have
had greater openness and freedom in preaching the Gospel.
Fifth-day was at Royston meeting, which I hope was profitable to some,
though to myself hard and laborious.

Sixth-day at Baldock meeting, to which came many Friends from Royston;
it was a time of deep travail and exercise to my mind; a testimony was given me to bear,
and I trust I did it faithfully.
Seventh-day to Hitchin, which place I went to in such fear and bowedness of spirit,
that I was almost ready to sink, by letting in the reasoner so much to my discouragement.

When I came thither my relations, of which I had many,
and Friends seemed pleased to see me.
The next day, being the 1st of the fifth month, was at both their meetings,
where through the goodness of Him who called me thither,
all slavish fears and doubts were removed,
and the Lord alone became my strength and support, blessed be his great name,
who is strength in weakness, riches in poverty,
and all in all to them that put their trust and confidence in him,
which now I experienced wonderfully to my help:
we were mutually comforted in the overspreading of the love of God in our hearts,
to his praise and our rejoicing.

Third-day was accompanied by Joseph Ransom, senior, a worthy and honourable elder,
my wife's uncle, to Ashwell, where although there is but one family of Friends,
I had a large meeting of the neighbours.
In this place lives Barbara Everard, a poor, honest, decrepit creature,
apparently convulsed all over, by which her speech is much affected,
and understanding also.
Yet the Lord has been pleased to make use of this young woman in an extraordinary manner,
having bestowed on her a gift in the ministry,
in which office she appears above many of far more natural talents;
in common conversation she is difficult to be understood, being of a stammering tongue,
but very clear in utterance in her ministry, her matter very correct and sound,
opens the Scriptures very clearly,
and preaches the Gospel with great power and authority,
and is of singular service in this place: she had at this meeting good service.

+++[+++The following is a letter written not long
afterwards by Barbara Everard to Joseph Oxley.]


Ashwell, 9th of Seventh month, 1760.

Loving friend,

This with my love to thee and thy loving wife,
hoping these lines will find you in good health, as we are through the mercy of our God,
who is the Father and Fountain of all our mercies,
to whom be glory both now and for ever!
Although we are far separated in body yet we are near in spirit,
for I do not forget thee nor thy labour of love when amongst us,
neither do I think thy labour was in vain,
for it tended to encourage us to press forward towards the
mark of the prize of our high calling in Christ Jesus,
that so we might come to the knowledge of the things
that belong to our soul's everlasting peace.
My desire is, that we may wait humbly for the teaching of that blessed anointing,
that so we may witness a profiting; for the Lord is come to teach his people himself,
yea, his presence is sometimes sensibly felt among us in our meetings.

The 6th of the sixth month, we were at Baldock Yearly Meeting,
which was a large good meeting,
the testimonies were to the reproving of the backsliders from the Truth,
and to the encouraging of the sincere and upright-hearted
followers of our Lord Jesus Christ to hold on their way.
At this meeting Isaac Sharples gave notice,
that he intended to be at Ashwell meeting the first-day following,
which was very large and a good open meeting,
the Lord's presence being sensibly felt amongst us,
to the comforting of the mourners in Zion;
and I believe the Lord will have a people to bear
testimony to his great name and Truth in the earth,
for he is sometimes pleased to make use of mean and contemptible instruments,
to bear testimony to his great name, of which number I am one as thou knowst very well.
Yet the Lord doth not forsake me,
for he is near to help all those that put their trust in him.

For some time I had a concern upon my mind to go to a place called Weson,
about two miles from Baldock, to have a meeting,
where there had not been a meeting held for about twenty years before,
which made me loath to give up to it.
But when the mighty power of God arose in me, I was made willing,
and my uncle and one of our young Friends went with me, and the meeting was very large,
there being as was supposed two hundred people at it,
and I had a good open time among them, and they behaved soberly,
so that I came away with a reward of peace in my own bosom:
for the Lord is a rich rewarder of all them that faithfully serve him.
Having given thee an account how things have been lately in these parts,
I conclude with praises and hallelujahs to the everlasting God,
who is near unto his people in all their exercises,
to whom be glory both now and for ever, amen!

My uncle joins with me in love to thee and thy loving wife,
our love is also to all sincere and true-hearted Friends.

Barbara Everard.

Fourth-day was at Statfold, a small, hard, laborious meeting,
but witnessed the Divine presence to sustain me, and I hope I was in the way of my duty.
The above Barbara Everard was likewise at this meeting,
and had a short but acceptable opportunity.
The same evening I went to Clifton, and had an evening meeting,
consisting chiefly of the neighbours, of whom there were many.
At this place I was met by my very kind friend and former companion,
Isaac Gray of Hitchin,
a man of a pleasant disposition and earnest for the prosperity of Truth;
the meeting not large, but I hope profitable.
After which, I went with John Gunnis, an acceptable ministering Friend,
who accompanied me the next day to Cranfield: the people were earnestly laboured with,
that they might have in possession what they had in profession.
The same evening to Ampthill, and lodged at John Morris's;
had a meeting here on the sixth-day to good satisfaction:
here are a pretty number of Friends of the right sort.

This evening went to Luton, and lodged at Daniel Brown's;
seventh-day had a meeting at this place, John Gunnis and Isaac Gray being with me:
it was a good and very comfortable strengthening opportunity to us;
I desire to bear it in remembrance with thankfulness.
After this meeting went to Hempstead, and lodged at the widow Dearman's;
from this place John Gunnis returned home.
I was pleased with his company, being a man of an innocent life and sweet conversation,
of a humble spirit and meek disposition, savoury in his ministry,
and I think him a man much in favour with the Lord.
Third-day morning had a meeting at Alban's,
in which I had to speak pretty closely to parents on
educating and training up their children,
and the advantages of demeaning themselves becomingly,
which is too much wanting amongst us.
From hence to Hertford, and was met here by my kind friend Samuel Scott, junior.
Fourth-day had a meeting with them to good satisfaction,
concluding in prayer and praising the Lord.
Went to Buntingford that night, and had a meeting there next day;
both myself and Samuel Scott had an opportunity in testimony:
the doctrine declared was very close, and I believe there was occasion enough for it.
I was informed afterwards,
that they had not had a stranger to visit them on the like occasion for three years past.
Went forward to Bishop Stortford, and the same day had a meeting at Stansted,
where I was quite silent.

First-day, the 15th, was at their morning meeting at Hertford,
and in the afternoon at Ware: returned to Hertford,
it being their select meeting for ministers and elders,
in all which the good hand of the Lord was near to uphold and support.
I now apprehended myself at liberty from the service,
in which I had been so closely engaged,
and to the best of my understanding had faithfully discharged myself.

I went up to the London Yearly Meeting,
wherein I experienced my mind to be much comforted and renewedly strengthened.
The affairs of the church were carried on in much brotherly love and condescension,
and meetings for religious worship attended by many able, living ministers,
both of our own and other nations: yet,
several of our meetings for worship were disturbed by some of a contrary spirit, who,
in their own forward wills, would say a great deal to the burdening of the right-minded.
In my return from London I came by Saffron Walden,
thinking it my duty to pay them a second visit: had two very good, comfortable,
satisfactory meetings there, the 1st of sixth month,
after which I set forward for Norwich, which I reached the next day,
and found my wife and family in the enjoyment of health.
We were truly glad and thankful to our great and good Master,
who had thus favoured us with an opportunity of meeting together again,
this 2nd day of sixth month, 1760.

Let it be weightily considered by all such as apprehend
themselves called to travel in the work of the ministry,
that he who hath called us is holy, and hath said, "`Be ye holy,`" and in another place,
"`Walk before me, and be thou perfect.`"
As we preach Christ, the way to perfection, in all manner of conduct and conversation,
it behoves us to walk in great circumspection and care, lest, unwarily,
our example should be such as to occasion the Truth to be evilly spoken of.
Some, in the course of their travels, for want of watchfulness,
have been drawn out into conversation respecting individuals, and of ministers,
to speak slantingly of them, and disrespectfully of their service; by such conduct,
these ministers and their ministry become lessened in the esteem of some Friends;
and though there may appear some face of approbation,
yet at the bottom the slanderer is had in greater contempt.
It is therefore rather to our reputation, that we should be silent on such occasions,
than to speak to the hurt of any, and to the hindrance of their service.
I would rather recommend, as a general rule, to speak evil of nobody.
Show also thy moderation at table, in eating and drinking,
and let it not be known that thou art dainty: there are many beholders,
some probably for good, but not all.
Some young and well-minded are seeking our company, for conversation,
that they may be profited and improve from our experience;
unto these be not heard to murmur and repine, because of spiritual adversity,
and lowness in mind, and distress of soul, and the like; lest by so doing,
others may follow thy example,
and let in discouragement to the hindrance of their growth and spiritual improvement.
But, rather speak pleasantly of the dispensations of Divine Providence,
believing that all things work together for good to them that love and fear God.
And let us seek to be endued with that wisdom which is from above,
that all our actions and ways may demonstrate that we are governed by it.
This will preserve us in a steady, persevering conduct from place to place,
and such will be favoured to see the work and service that is to do;
of which be thou mindful, and in so doing thou wilt be esteemed no loiterer, nor hurrier,
but moving with stability; and walking consistently, according to the leadings of Truth,
will add strength unto the minister,
and honour and praise unto Him that hath thus called us.

