== Chapter V.

I had now been at Norwich about sixteen years,
during which time our meetings had been evidently increasing, and still continue so,
not only as to numbers amongst ourselves, but also from amongst those of other societies,
who have been convinced of the blessed Truth, and joined us in religious fellowship;
some of whom have become as princes among the people.
The Almighty has been abundantly gracious in affording a time of precious visitation,
wherein many sons have been called as from far,
and daughters as from the ends of the earth; a growth in the Truth has been experienced,
and many have become publishers of the same glorious truths of the Gospel.

At my first coming hither, there were but three Friends in the ministry, namely,
George Dupledge, Joseph Gurney, and Robert Letchworth;
the former was removed by death a few weeks after my coming,
Robert Letchworth removed himself and family towards London,
Joseph Gurney lived about six years after my coming, and then died:
so that in that capacity I was left almost alone.
But a hope sprang up in my mind at that time, that it would not always be so;
and it is now a matter of no small comfort,
that the Lord in his goodness has been pleased to increase the number,
that I think there are of men and women not less than sixteen,
who appear in public testimony in an acceptable manner.
I wish we may all be preserved through the various
trials and vicissitudes of life unreproachable,
and stand faithful to the end in the testimony of Jesus.

In the year 1761,
my honest and faithful wife being also engaged in the work of the ministry,
as before related,
had it on her mind to pay a religious visit to Friends in Huntingdonshire,
the Isle of Ely, and parts adjacent.
She took her departure from home the 5th of ninth month, 1761, and returned,
after a tour of about two months, in much peace.
By sundry accounts she had very acceptable service,
being a woman of a holy life and godly conversation,
and a zealous contender for the cause of righteousness.

After being at home about two years,
I found an increasing exercise and growing concern to pay a
religious visit to Friends in the nation of Ireland.
The prospect of this visit had attended me more or less, for fifteen years,
and now I could no longer, with any degree of peace, withstand the divine requiring;
I therefore made suitable preparations for leaving my business and family,
and laid my concern before our Monthly Meeting,
and a certificate was granted me for that purpose.
I set forward on the 31st of fifth month, 1762, on my way to Liverpool,
and took with me my youngest son Edward,
whom I left by the way at Highflatts in Yorkshire, at a boarding-school.
We got to Highflatts on sixth-day, and the following third-day I went to Manchester,
and attended next day their week-day meeting, which was pretty well as to numbers,
but seemed to be wanting in that spiritual exercise which tendeth to profit.
After meeting went to Liverpool,
where I heard there was a vessel then ready to sail for Dublin.

The seventh-day following we set sail in the afternoon; the weather fine, and clear sky,
with little or no wind stirring;
so that we did not reach Holyhead until third-day morning, being almost becalmed,
and what wind there was was not in our favour.
The next morning the packet-boat sailed from this place for Dublin,
and as some of our passengers grew weary, they left us and went on board the packet.
Fourth-day evening we weighed anchor, the wind being a little more in our favour,
but fell off again: we at length got to Dublin the 18th of sixth month,
after a passage of about six days.
The master of the vessel was very kind, but one of the passengers,
an officer in the army, was not so, but made ridicule of the Quaker, as he styled me,
and the movings of the Spirit.
He had me in great derision, and at length, growing very insolent and affronting,
I found it my duty in the Truth to reprove and admonish him: which I did,
and the Lord was with me and gave me courage and strength, and power over him.
He was afterwards still and quiet, and continued so all the time we were together.
Some few years afterwards, being in London,
I went into one of the prisons to see one that owed me some money, where I saw this man,
who viewed me with great shame; he was there for some misdemeanour.

But to return.
When I landed, I went to my friend Samuel Judd`'s, at whose house I lodged;
he was an aged man, and very infirm,
but very loving and open-hearted to travelling Friends.
I attended their week-day meeting the day I landed, which was small,
and I thought not the most profitable.

[.offset]
+++[+++In a letter to his wife, after speaking of Samuel Judd`'s kind attentions to him, he says,
"`I am in a very low, needy state,
yet well satisfied I am in the way of my duty to Him whose
judgments and mercies cause us both to fear and love him.
I desire of thee, my dearest friend and companion,
with whom I have sweet unity and fellowship in that life that is everlasting,
to seek the Lord for me,
that I may be preserved and upheld to the praise of his great name.
Oh! that I may not sink in this great undertaking,
but be enabled to stand boldly for my Lord`'s cause,
and that no blemish may be suffered to come upon me in any future time,
so as to cause our holy profession to be evilly spoken of.`"]

After meeting, several Friends retired into an adjacent room,
according to their accustomed manner, and being asked for my certificate,
it was produced and read, which was to pretty general satisfaction,
and some Friends were appointed to assist in purchasing a horse for my journey.
First-day I went to meeting, which was pretty large,
and I was favoured to preach the Gospel with a degree
of openness and freedom beyond some other times.
Between the two meetings, there landed a woman Friend from Coalbrookdale, in Shropshire;
her name Ann Summerland, who had at dinner a sweet heavenly opportunity in supplication:
we were glad, though strangers, of one another`'s company,
and went together to the meeting in the afternoon,
which was much smaller than that in the morning,
but hope it was to pretty good satisfaction.
I stayed their meeting on third-day, and on fourth-day set forward to Ballicane,
where a meeting being appointed, was I hope to some profitable instruction.

Fifth-day to Erratt`'s, which was very small; and a few came in not of our Society:
the Lord`'s power was over us, and the Truth declared in the demonstration of the Spirit,
and it ended much to our comfort and edification.
About this time that worthy and highly valued Friend, James Pim, of Mountrath,
departed this life; he was an elder, and worthy of double honour.

Sixth-day was at Wright`'s meeting, the room well filled,
both with Friends and with the goodness of the holy, quickening,
enlivening virtue and presence of Divine love, which is the crown of our assemblies.
Went to Enniscorthy Monthly Meeting, also had meetings at Cooladine and Randal`'s Mills,
where lived a worthy Friend named Joseph Williams; the meeting was held in his house.
I was led in the course of my testimony to speak on the parable of the lost sheep,
and of leaving the ninety and nine to seek that which was gone astray.
It was a time of merciful visitation to some present; Truth was exalted,
and the holy name praised, who is worthy for ever!

Next day had a meeting at Wexford; fifth-day, 1st of seventh month, at Forest;
and sixth-day at Ross, wherein appeared a state of great hardness of heart,
and an unwillingness to bow and submit to the tendering visitation of Divine Grace.
First-day attended the meetings at Waterford,
wherein I found the love of God abundantly shed abroad
in the hearts of many to our souls`' comfort.
I also stayed the week-day meeting, which afforded consolation,
and in the afternoon went forward to Clonmel.
The meeting here was pretty large,
and many amongst them are concerned to seek the
way to the kingdom of peace more earnestly,
growing in the root as well as branch.
The day following was conducted by Robert Dudley to Cashel; the meeting very small,
and the true seed imprisoned.

Next morning set forward for Youghal, it being their Province Meeting,
which was very large, many other people coming in,
whose behaviour was very becoming in all respects; the meetings were well conducted,
and the Lord`'s powerful Truth owned us in a wonderful manner.
James Toomey, John Morris, Samuel Neale, Joseph Grubb, James Keys and Thomas Whiley,
were appointed to visit several families in the said town.
I accompanied these Friends in their visit,
which was attended with a good degree of satisfaction, both to the visitors and visited.
After which, set forward for Cork meeting on sixth-day.

The following week, accompanied by my kind friends Samuel Neale and James Toomey,
attended meetings at Bandon, Limerick, Mallow, Birr and Roscrea,
where the Lord was pleased to favour, so that his doctrine did drop as the rain,
and his speech was experienced to distil as the dew, praised be his name!
Next day at Knockballymagher,
where the meeting was held at the house of our worthy friend, James Hutchinson;
and he accompanied me to Ballinakill, where, in a particular manner,
parents were recommended to be more circumspect in bringing up
their children and families in the fear of God.

The next day, being the first of the week and the 1st of the eighth month,
had two meetings at Carlow,
wherein the Lord was pleased to favour beyond our expectation,
comforting the weary travailing soul,
and giving fresh courage and strength for future service:
may we live in thankful remembrance of the continuance of his
merciful and precious visitations from time to time extended,
which we have not merited.
The same evening I went home with Robert Leckey and wife,
and third-day had a meeting at Kilconner:
here also the Lord blessed with great openness to preach the Gospel,
and the meeting concluded with prayer and thanksgiving.
Fourth, fifth, and sixth-days, had meetings at Newtown, Ballitore and Athy,
at all which places Divine Goodness owned us by the breaking of bread,
to our inward comfort and spiritual consolation.

[.offset]
+++[+++From Ballitore he writes:--"`Oh! how does my poor weary soul travel from place to place,
and from one meeting to another, seeking the living amongst the dead.
There is in most places great plainness and great dryness, emptiness and show:
I hope the Lord`'s servants by their many faithful labours will be clear,
and the blood of the unfaithful will be on their own heads.
I have travelled in company with a very honest Friend for two or three weeks past,
whose name is James Toomey, of Limerick; he is seventy-two years of age,
and in good esteem in his service, short and savoury: we parted this day.
Through mercy, I continue in a good state of health, much better than I expected:
but my spiritual exercise is greater than ever yet I have met with; yet,
blessed be the name of the Lord, when I am near sinking and almost ready to faint,
he is pleased to appear, to uphold and strengthen,
to refresh and comfort his poor tried servant!`"]

First-day, the 8th, my companion James Toomey, being now returned,
I was joined by that eminent worthy elder, Abraham Shackleton,
whose company was very agreeable to me.
We were this day at Mount-melick, and had two meetings to very good satisfaction.

After meetings at Tullamore, Moate and Ballymurry,
on sixth-day rode to the widow of James Pim, of whom I have before made mention.
She was afresh affected with grief on seeing my companion,
because of the intimacy and unity of these two brethren;
who might with propriety be compared to Aaron and Hur,
that were companions and helpers together with
Moses against theirs and the Lord`'s enemies.
Seventh-day made a visit to our ancient friend and elder, John Pim of Lackey,
who having a son in a lingering disorder, wholly confined to his bed,
we had a little meeting in his chamber to a good degree of satisfaction.
Although my dear companion, Abraham Shackleton, was not engaged publicly,
he was a man truly worthy of double honour,
and in family visits and select opportunities he was of singular service,
advising and admonishing as he was opened in the Truth,
and the people loved him with great affection:
he ministered a word of counsel to this young man to good satisfaction.
In the evening returned to my quarters,
where I met with many letters from my dear relations and friends in England,
all signifying their approbation and unity with me in my religious visit to this nation.

First-day 16th, was at two meetings at Mountrath, which were large and divinely favoured,
to our mutual comfort and strength.
Third-day was again at Carlow, being their Monthly Meeting, which was large,
and that for discipline conducted with a good degree of unanimity and concord.
The same evening returned home with my companion to Ballitore.
Fourth-day, his son Richard, who promises to come up in the paths of his worthy father,
accompanied me to Baltiboys.
The meeting was small, and the love of God grown cool in the minds of many,
yet he is pleased to continue striving with them that they may be saved.
After meeting at Rathangan, returned to Christian`'s town, and lodged at Samuel Neale`'s,
a choice Friend with a very large family.
After taking meetings at Timahoe, Edenderry, Oldcastle, Coothill, Castleshane,
Ballyhagen, Charlemont, Toberhead, Colerane, and Ballinacree, came to Ballamana,
and on fifth-day had a meeting there;
and though many things would have crowded in on the mind to
hinder the performance of true spiritual worship,
yet it pleased the Lord to arise,
and his enemies and the enemies of his people were scattered.
We were favoured beyond our expectation with the power of Truth,
and comforted in his holy presence; and though our number was very small,
our strength was increased in God, the fountain of all good.

On sixth-day had a meeting at Grange, small of Friends;
a few others came in who behaved well.
I was led to speak of the free ministry,
and to invite unto God the inexhaustible fountain that cannot be drawn dry,
and setting forth the insufficiency of man`'s teaching without Divine assistance,
and witnessing Christ in God to be all in all.
I was informed after meeting, that there was a Presbyterian priest there,
of which I knew nothing.
Same evening went to Antrim: amongst the few Friends here, the enemy had got in,
and made great havock.
On seventh-day I had a meeting with them,
and endeavoured to shut out all prejudice of every kind,
so I witnessed the renewings of Divine favour to be shed abroad in my heart,
inviting all to return, repent and live.
Went home with the widow Boyd, about three miles;
had a meeting at her house to which came many of their neighbours,
and the Lord was pleased to favour us in a memorable manner,
and his name was exalted and praised over all, who is worthy for ever and ever!

After meetings at Lisburn, Newtown and Hillsborough, went to Ballinderry on sixth-day,
it being their Quarterly Meeting for the province of Ulster.
The meeting of ministers and elders sat down about the first hour in the afternoon;
toward the close of said meeting there appeared
a little matter on my mind which I gave up to,
and had good satisfaction therein.
Seventh-day morning was a large meeting for public worship;
and in the afternoon one for the transaction of the affairs of the church,
which were carried on in much unanimity, and brotherly love and condescension.

First-day, the 16th, the meeting was very large,
and favoured by the Master of our assemblies,
who gave many of us signal tokens of his heavenly regard,
which my soul gratefully acknowledges at this time.
Second-day was at Lurgan, at the burial of Thomas Trueman,
a ministering Friend in good esteem.

Third-day went to Rathfriland: a very poor appearance of Friends.
I was led in a very close manner, though in much love, yet afraid of their steadfastness.
Fourth-day went to Moyallen, and had a meeting there; and although silent,
I believe I was favoured to see that the Lord had a righteous number in that place,
which was much to my soul`'s peace and comfort.
Went to Castleshane, Oldcastle and Edenderry, where I paid a visit to Joshua Wilson,
grandson to that ancient and worthy minister and elder Thomas Wilson;
and hope there is of the same righteous seed and principle growing up in him.
Third-day had a meeting at Rathangan;
the testimony of Truth was against the spirit of the world;
which delights itself therein to the hurt of the growth of the most pure part.
Fourth-day went to Dublin; and on seventh-day our dear friend, Ann Summerland,
returned from her visit to this nation, of whom mention has before been made:
having paid a pretty thorough visit both to her own and Friends`' satisfaction,
she felt at liberty to return home.

First-day we stayed their morning meeting at Dublin, which was large,
in which I think Ann had very good service.
A ship being ready to sail for Liverpool, we agreed to accompany each other to England;
and going on board in the afternoon were favoured to
land safely at Liverpool the next evening,
for which our hearts were made truly thankful.
We had a meeting there next day, in which the goodness of the Lord was abundantly felt,
and acknowledged in reverence and fear.

Fourth-day went to Warrington, where we parted; I returned by the way of Highflatts,
and took my son Joseph who had been there some time for education.
We got safe home on the 6th of tenth month, 1762,
after a journey of about seventeen weeks, in which I travelled about 1482 miles.
Before I close this account I would just remark,
that I was detained in this country two or three days longer than I expected,
occasioned by some apprehension of duty to visit two or three meetings a second time,
to which I was faithful; yet could not see any extraordinary service attending,
which occasioned deep travail in my mind;
as in all probability I should have gone in a vessel
which sailed two or three days before we did,
for the same port.
But a great mercy it was for me that it was otherwise ordered,
for we were given to understand, when we got on the coast of Liverpool,
that the said vessel was lost, and all the people perished.
So I had to behold the preserving hand of the Lord in guiding me by his providence,
and making way for deliverance and escape from the most imminent dangers,
which I hope to bear often in remembrance with reverence and fear.
I have only now to add, that I found my wife and family well,
and my business was well conducted in my absence.
I gratefully acknowledge and own the goodness of that Divine hand,
that was with me in all this journey, and preserved me without fainting.
May the continuance of heavenly wisdom guide me in all things,
that I may walk in those paths, and practise those rules,
which I have so earnestly recommended to others!

The work of true Gospel ministry is a very great mystery,
which they that are exercised therein can testify by experience.
Its source and spring is everlasting goodness, diffusing itself into the soul,
by which it is enlivened, quickened and strengthened,
to call and invite mankind to come to a state of repentance and amendment of life,
that thereby they may live in the love and favour of God,
and at length die in acceptance with him.
Many of these godly messengers, for so I will venture to call them, who are thus taught,
instructed, and qualified, oftentimes meet with great exercises and trials,
such as leaving wife or husband, children, business, and everything else,
to go whithersoever they apprehend to be their duty, far or near,
without fee or reward from men.
And this continues to be a great mystery,
to divers amongst the many professors of Christianity unto this day.
I write not these things,
because I am dissatisfied with any lot or portion I have in the work,
though I have met with many close trials and proving seasons,
and have found myself hitherto upheld and supported to yield in
submission and in obedience to God in every requirement of this kind;
and if more should be required,
I hope my will may be brought into subjection to the Divine will, and at length say,
as I am taught by the great Master, I am an unprofitable servant.
He said unto his servants formerly, "`Go into the vineyard,
and whatsoever is right ye shall receive;`" and
he who thus promised is faithful to perform;
and on all occasions, I have witnessed him to be a rich rewarder, a God nigh at hand,
and a present help in the needful time.
Praised for ever be his great and worthy name,
who has not only blessed me with the knowledge of his precious Truth,
and by it hath to this time in a good degree preserved me;
but has been graciously pleased to bestow a measure of
the same good Spirit on my dear children,
by which they not only believe in the Truth, but also are concerned to walk in it;
and this I esteem far greater riches than the increase of worldly inheritance.
