== Chapter X.

My companion and myself having travelled in much love and unity,
through a long desolate wilderness,
now finding our minds drawn to different parts of the continent, for our own peace,
and we hoped for the more general service, we in the same love agreed to part,
and requested the company of divers Friends on the occasion,
to commune with them thereon: and after a solid time of waiting,
Friends expressed their approbation and unity therewith, believing,
according to their feelings, that it was the pointing of Truth,
and they were well pleased and satisfied with our conduct in calling them together,
and hoped others would follow our example under the like circumstances.

+++[+++The following is an extract of a letter from William Brown to Mary Oxley.]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Philadelphia, 6th of Fifth month, 1771.

[.salutation]
Dear friend, Mary Oxley,

It is in my mind to visit thee with a few lines,
to give thee an account of thy dear husband,
who with his companion is now with us at our Quarterly Meeting,
they being returned from the southern parts of this continent,
which we think the most difficult part of their work as
to travelling and entertainment for man and horse.

It was with me at their meeting in this city,
to give a caution about joining as companions
through their religious labours in this country;
but to that they both seemed to lend a deaf ear;
for I feared they might give more time and place to each other,
than the nature of their gifts and the necessity of their labour would admit of:
for their Master fails not to furnish them with
his hidden treasures to deal out to the churches,
and though thy honourable companion thinks himself a little man every way,
yet it is the pleasure of Him that called him to the work of the ministry,
and separated him to this part of the service, to give him part with the great,
and a name with his princes in Israel.

[.signed-section-closing]
I affectionately salute thee, who am thy loving friend,

[.signed-section-signature]
William Brown.

--

Third-day attended their youth`'s meeting the public service fell on Sarah Morris,
Samuel Nottingham, Isaac Andrews, and my companion: I thought it a favoured meeting.
Sixth-day had a meeting at Plainfield,
where the Lord was pleased to own his people with his life-giving power and presence,
to his praise and our rejoicing.
Seventh-day at Woodbridge, Elizabeth Morris and myself had each opportunities,
to the stirring up those who were careless and
indifferent about the attendance of religious meetings,
and of that worship which is to be performed in spirit and in truth.

First-day, 12th, was at two meetings at Rahway, both which were large,
open and satisfactory.
Elizabeth Morris had good service; the Gospel was preached with life and power,
blessed be His name, who is still continuing such gifts to his churches.
Second-day rode to New York; fourth-day crossed over to Long Island;
fifth-day had a meeting at Newtown; in the evening rode to Matthew Franklin`'s,
a ministering Friend who attended us to most of the meetings on the island.
At Bethphage we visited a poor woman Friend, whose name was Clement Willis,
who was taken ill when she was about nineteen years of age, with the rheumatism,
soon after which she was confined to her bed, even until the time I saw her,
which she then told me, in the presence of many other Friends, was thirty eight years.
She is so emaciated and reduced as to be an object of wonder to those that see her;
she is so decrepit as scarcely to be able to move one joint, or any part about her,
and has not seen her hands for very many years.
She has almost outlived all her pains, which are now centered in weakness;
that she continues to live, is marvellous,
and through all her sore afflictions and trials
praises the Lord for his blessings to her soul,
lies in great composure of mind, and wholly resigned to his pure will and pleasure.
The time we sat by her bedside was one of renewal of
heavenly favour to her and many present,
which was acknowledged in humble supplication,
with thanksgiving and praise to Him that makes hard things easy,
and bitter things sweet to the afflicted soul.
We parted in much love and sympathy, and went to our lodgings at Samuel Willis`'s.

At Flushing attended their Yearly Meeting,
where were also Elizabeth Morris and William Horn from Pennsylvania,
and Timothy Davis and Patience Brayton from New England.
These meetings were resorted to by many besides those of our Society;
I hope all was well, yet not so open as I have known some smaller gatherings.
In the meeting for discipline there appeared a considerable defection,
from one quarter in particular,
refusing to answer the queries in the form recommended by the Yearly Meeting of London.
This was a matter very exercising to the right-minded,
and a committee of weighty and judicious Friends
were appointed on that service to visit them,
which I hope may tend to the honour of Truth, and strengthen the feeble of the flock.
Second-day the meeting for discipline sat again, which was large and solemn,
far excelling any of the former.
Sundry affairs were spoken to in that authority which Truth gives,
and Israel prevailed that day.
A number of Friends were chosen to visit those who kept Negroes in slavery,
in order that they might be set at liberty.
Our friend Israel Pemberton from Philadelphia, attended this meeting,
and was particularly instrumental in forwarding this good work
of visiting the masters of these poor enslaved Africans,
which in the end will I hope prove successful.
These meetings being over, I finished my visit to the island, which,
however it might prove to my friends, was very much to my satisfaction and peace.

[.embedded-content-document.letter]
--

[.letter-heading]
Benjamin Swett to Mary Oxley.

[.signed-section-context-open]
Burlington, 5th of Seventh month, 1771.

[.salutation]
Dear friend,

As every instance of attention to thee, though from a distant junior brother,
during the absence of the partner of thy life,
may have a tendency to strengthen thy mind, under so trying a circumstance,
I have engaged to inform thee,
that early in the fifth month I accompanied him to New York and Long Island,
and we were at several meetings, particularly the Yearly Meeting at Flushing;
and I think I may say his service was attended with evident demonstration that it
proceeded from the influence of the Minister of the sanctuary and true tabernacle,
which God has pitched and not man.
Being thus called to act under so great a Master,
I hope the time of his absence will be alleviated by the reflection thereof;
and I make no doubt but he that promised to be a Father to the fatherless,
will abundantly fulfil his gracious promise to the children of my dear friend,
during the privation of so tender a parent,
and that He will be as a husband to thee in this thy temporary state of widowhood.
As I am convinced thou art well acquainted with the
proper place of waiting for a renewal of thy strength,
and increase of that patience which alone can reconcile thee to thy present situation,
I would not presume to dictate anything on that head;
but suffer me to suggest a sincere wish, not only on thy behalf,
but the children of my dear friend--that the Lord may be pleased to
grant a double portion of his Spirit to rest on you respectively;
and that when he may be pleased to unite the family again,
it may be with an increase of Divine favour and wisdom,
whereby you may all reflect upon his absence as
a time of improvement in the things of God,
and as I know the encouraging prospect of the state of your family, transmitted by thee,
has greatly comforted his mind,
I doubt not the fruition of that account will afford him still greater satisfaction.

I am with the united love of my wife, though personally a stranger,
to thee and thy family, thy affectionate friend and well-wisher,

[.signed-section-signature]
Benjamin Swett, jun.

--

Third-day returned to New York in company with other Friends,
at which place was a meeting appointed for our friends, Timothy Davis and William Home.
Joshua Thompson, near Salem, in New Jersey, a worthy experienced elder, joined me,
having come from his own home to Flushing with that intent,
with a certificate of recommendation, and he proved to be a choice companion,
and very serviceable in the discipline of the church.

Fifth-day, 30th of fifth month, we embarked for Rhode Island:
the New York Friends were so kind as to send a young man along with us,
whose company was both useful and pleasant, his name was William Rickman.
We had a pleasant passage and landed at Newport, the principal town on the island,
but old; and here they build their houses almost altogether of wood.
They have a very commodious haven for ships,
also a House of Assembly which sits as occasion requires.
We lodged at our ancient and worthy friend, Joseph Jacob`'s,
and next day were at both their meetings, which were very large of Friends,
and a great many of the towns-people; the morning meeting was silent,
but not so the afternoon.
There are many in profession with us at this place, but scarcely a minister amongst them:
a very large commodious meeting-house, with two tiers of galleries round,
except over that of the public Friends, and there only one.
Second-day had a meeting at Portsmouth, and then went to Jacob Mott`'s,
an ancient Friend upwards of fourscore, and had a sitting in his family to edification.

Attended their Yearly Meeting for New England at Newport,
of which I have nothing extraordinary to remark, save that the meetings were large.
First-day, the 16th, the morning meeting very large, all the galleries filled,
and it was a favoured meeting.
Peter Davis, an ancient and honourable Friend and minister, attended this meeting,
though in the ninety-second year of his age,
and I thought he preached the Gospel with Christian boldness,
and stood unshaken in the cause of his great Master,
and the meeting concluded in supplication and praise to Him that lives for ever and ever!
On second-day were held two meetings for discipline,
which were expressive of brotherly kindness.
Friends uniting their endeavours to afford help where need required.

Our select meeting was adjourned to the conclusion of this, and was to good satisfaction,
and so these meetings ended, and Friends parted in great love and peace.
Sixth-day had a large meeting at Joseph Rotch`'s at Bedford, amongst a seeking people,
who were very attentive to the testimony of Truth; the good old man, Peter Davis,
had good service,
and the meeting concluded in supplication and praising
the Lord for his goodness to us this day.

+++[+++In a letter to his brother John Oxley, he remarks:]

[.embedded-content-document.letter]
--

"`Peter Davis was born at Dover in Old England,
and was brought over into America in a state of infancy;
he now resides at a place called Westerly,
about thirty miles from Newport in Rhode Island.
He visited some parts of Old England in the year 1749, is an able minister of the Gospel,
being sound, living, and his labours to edification.
Though in the ninety-second year of his age, he mounts his horse very actively,
without taking advantage of rising ground.
His company to me has been very pleasing:
we are just returned from a very large meeting at Bedford,
in which the Lord got himself the victory, and his name was praised,
who is over all and above all, worthy for ever and ever!
I have written thee a little, my dear brother, though I owe thee much,
and love thee more: I might write thee many sheets and quires of paper,
yet owe thee much, and love thee more.
May Infinite Wisdom keep us and ours in this mutual love, happiness and joy,
which neither pen can fully describe, nor tongue utter,
this is a love which remains beyond time, and is everlasting!
Though I am yet in the world, my mind is redeemed from it,
and desire to have no more fellowship with it,
no more to be a partaker of its cares or its joys.
Once more my love to my endeared spouse, to my beloved children,
whom the Lord in his love has blessed, to thy dear self, etc.,
from thy affectionate brother,

[.signed-section-signature]
Joseph Oxley.`"

--

On third-day went on board a vessel, and set sail for Nantucket;
we passed a place called Wood`'s Hole,
near which is a strait so narrow as not to be
safe for two ships to go abreast of each other;
the rocks were considerably above the water,
and our vessel so near on each side as that a
person might jump from the vessel on the rocks.
It was proposed by the captain and passengers that we should go into harbour that night,
but I was of a different judgment, so kept out at sea: the night was very foggy,
as was the next morning, till about the middle of the day,
so that our captain and passengers were well pleased that we kept out,
for had we gone into harbour,
the foggy weather would not have admitted our coming out next morning,
and so might have been disappointed in attending
some part of the Yearly Meeting at Nantucket,
which was our principal view in going there at this time.

+++[+++Fifth-day wrote the following letter to his wife.]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Nantucket, 2nd of Seventh month, 1771.

[.salutation]
My dear and loving wife,

I take up my pen in order to essay something in answer to thy
two last letters received at Flushing on Long Island,
dated the 5th and 20th of the second month;
the former giving me a very pleasing and satisfactory
account of thine and our family`'s welfare,
also of the kind visit of our dear and worthy friend Robert Willis,
whose labours of love amongst you have been to your comfort and edification;
likewise of the growth and prosperity of Truth in general,
and in particular amongst my own children.
Such pleasing accounts, my dear, create reverence and fear,
humility and lowliness of mind, to approach with thankful acknowledgements the great,
good and all-wise Creator, without whose presence we are not, nor can be,
perfectly happy.

I rejoice with thee, my dear and welcome messenger of these glad tidings:
thou art a mother in Israel, a guardian to many begotten of God and made precious,
being bound to the testimony,
and thy faithfulness in the great Master`'s precious cause productive of much good fruit,
better than the increase of corn, wine or oil,
which are great and good blessings but perish with the using;
but the pure unchangeable Truth waxeth not old as doth a garment,
but as its nature throughout is purity,
so it preserves all those pure that walk in it to the end.
I think, my dear, both thou and I have cause to be thankful,
and have great encouragement to hold on our way,
and in order to it let us walk in fear and trembling,
and not seek after the praise and exaltation of men,
but as we dwell in a state of humiliation we shall dwell safely and in a teachable state,
and improve more and more in religious experience, to our own and others`' good.
Since I last wrote thee from Philadelphia,
thou wilt be informed of my visits from thence to Long Island, Rhode Island, etc.,
by letters to my dear children, and lastly to my brother.
I am through Divine favour in good health,
a blessing which I covet may be the enjoyment of my dear wife, my children,
relations and friends.

My dearest companion, I have now to notice thy affectionate address of the 20th of second month,
which was a mixture of sorrow and joy,
but as I had heard of the departure of dear sister Oxley,
so I was the better prepared to receive it in that full manner as represented by thee.
It was an afflicting circumstance, a great loss to dear brother and his children,
as also to ourselves, yet no great surprise to me,
as I thought I should scarcely see her again when I parted with her.
I am well pleased that brother is so well supported under it,
as also that she herself was so given up to the trying dispensation of the Divine will,
and as she was willing, so I believe she also was ready to be offered up,
which I greatly desire may be the case with all of us,
when we meet with the like summons, that our end, as I trust hers was,
may be eternal life.

I have found my travels, since I have left Philadelphia,
much easier than my southern journey, both as to the outward and inward,
also as to health of body and peace of mind;
and however little I have got for the little I have done, there remains no condemnation:
when anything of dissatisfaction would arise,
it is judged down with the remembrance of that exhortation,
"`Be content with your wages.`"
I love the people wherever I go, for the work sake,
and trust I am in part beloved of them; but of all who have travelled in these parts,
none exceeds dear Rachel Wilson,
whose labours of love to and amongst all people have gained general esteem:
and many there are who have been convinced through her ministry,
and others renewedly strengthened thereby.
In New England there are but few ministers, and still less of faithful labourers,
on which account let us ask of Him who can alone
send more faithful labourers into his harvest.

Since I left the city, I understand my kind friend John Pemberton has been very ill,
but now is better;
have had a letter from him in which he takes notice of
a letter he received from my virtuous religious wife,
which he expresses was much to his comfort and satisfaction:
he shows himself upon every occasion affectionately loving and kind to me.
I am much pleased, my dear, that we feel ourselves so happy in our present separation,
wherein our love has not abated, but in the Truth grown stronger;
and our resignedness and faithfulness I believe has so wrought
as to bring our children to be more in love with it;
and this is my great comfort, my joy and rejoicing,
when at times I am almost ready to despair of ever seeing my native country again,
that there remains a hope of spiritual survivors in some of my posterity,
who may with greater dignity fill up my place when I may be removed.
Let us so continue to live in a state greatly given up and resigned to the will of God,
that of a truth we may say with the apostle,
"`To me to live is Christ and to die is gain.`"

Remember me very affectionately to all, beginning at the house of Joseph,
to his brethren, and so on.
Should I be favoured once more to get to Philadelphia,
I should think the greatest danger over respecting health;
but I trust in Him who is able to keep and preserve both body and soul.

Think of me, my dear wife, relations and friends, as I do of you more often than the day;
and in a state of resignedness to the Divine will,
do I once more salute my dear wife and affectionate children; yours till death.

[.signed-section-signature]
Joseph Oxley.

--

Sixth-day opened their Yearly Meeting,
first holding a select meeting at eight in the morning, which was very small;
at eleven a public meeting for worship, which was exceedingly large of our own Society,
and a great many of the neighbourhood.
I think the meeting-house is the largest of any I have seen in America or elsewhere;
the meeting for the most part was silent.
Seventh-day, another general meeting for religious worship only,
which was still and quiet, becoming the occasion.
First-day, the 30th, two public meetings for worship were held, which were more open,
very large, profitable and good: bless the Lord for his goodness and mercy!
Second-day at eight, a select meeting, which though small was owned by the Great Master,
to the consolation and strength of his little flock and family;
at eleven another large public meeting for worship,
which was mercifully favoured with a degree of the same life,
by which an increase of heavenly love was experienced,
and Gospel fellowship maintained and preserved.

At the close of this meeting was held their usual Monthly Meeting,
which was large both of men and women, but, according to the answers to the queries,
the state of the church was low in many places, and indifferent in divers respects;
yet there remained in some a holy concern for the prosperity of Truth:
after this meeting Friends parted in much brotherly love.
I had divers meetings in Friends`' families, and visited the sick,
in all which Truth favoured, and the hearts of many were made thankful.
Sundry Friends came to our quarters at William Rotch`'s,
in the evening of the last day we were with them, and after a time of solemn retirement,
which tended to reunite and encourage to persevere in the way of truth and righteousness,
we parted in much love and brokenness of spirit.
I visited an ancient wealthy widow woman, Mehetabel Pollard, in her 79th year,
who informed me that her mother, Mary Gardner,
was the first white woman born on that island, also that her grandmother, Sarah Gardner,
who died in the 93d year of her age, left at the time of her death, children,
grandchildren, great grandchildren, and great great grandchildren,
five hundred and fifty-five.
This island is said to be about fifteen miles long, and three or four broad;
with little or no wood upon it; and is a level sandy country;
its chief produce is Indian corn;
and the inhabitants are mostly employed in the whale fishery, which is very considerable.

Third-day, 2nd of seventh month, between three and four o`'clock in the morning,
we took our solemn farewell of our dear landlord, his wife and family,
whose kindness I hope to remember with a grateful mind,
and embarked on board the same vessel that brought us.

Mary Callender, Amy Thurston, our dear friend C. Russel and his wife,
with several other Friends, returned with us.
After we had sailed, I queried with our friend M. Callender, how she fared,
and if she apprehended herself clear of her service in the island;
at which she was much cast down and wept, and finding her not easy,
brought sorrow over many of our minds on her account,
the ship being under sail with a fair gentle breeze.
The unfaithfulness of our friend made our going very irksome,
and we gladly would relieve her, but did not know how.
After a time, we perceived at a considerable distance a boat with two sets of oars,
double manned, coming from the shore, and as if she was making for our vessel,
and gained upon us fast, and as they approached nearer,
they gave signals of their wanting to come with us, which they did in a little time,
having with them a pair of bags of our said sorrowful friend`'s,
which were by mistake left behind.
This gave a favourable opportunity for our dear friend to return, which she did,
and Amy Thurston, who bore her company from home, returned with her.
This providential circumstance wrought greatly
to the delivering our minds out of much trouble:
let it be a caution for all concerned Friends,
that they discharge themselves faithfully in the Lord`'s service,
and then the Lord will reward them with peace, but if otherwise, with trouble.
So we parted in much love and tenderness,
after giving some admonition and counsel toward promoting and
encouraging faithfulness on future occasions.

We landed about noon at Falmouth;
where we parted with Caleb Russel in much brokenness of spirit.
Fifth-day rode to Sandwich, and attended their Monthly and Quarterly Meetings.
Second-day set forward to Pembroke, and stopped at a place called Plymouth,
a pretty large sea-port town, with wooden houses, and but indifferent accommodations.
In our way, passed by one or two large rocks by the road-side,
which were called by the Indians Sacrifice Rocks,
which they suppose and believe were those rocks which were rent or
cleft asunder at the time of the crucifixion of our Saviour,
and it remains to be a custom and practice with these poor creatures, the Indians,
that whenever they pass by these rocks, to lay either stick or stone thereon,
in commemoration of that day,
otherwise they think they shall not return without some evil befalling them;
and once a year they were used to assemble to
make a sacrifice by fire of these offerings.
Seventh-day went to Hampton Quarterly Meeting,
which opened the same day with a select sitting,
as is common in this country on this day of the week.

Second-day another select meeting, and afterwards the Quarterly Meeting for business,
which was little more than answers to some few queries.
There appeared great remissness in divers respects, and a want of faithfulness,
by which spiritual worship and the discipline of the church is become too formal and dry,
which is cause of mourning to Zion`'s travellers.

Sixth-day set forward for Falmouth, and first-day, 24th, had two meetings with them,
which were held in the life and power of Him who
rules in the hearts of his obedient children.
There is a considerable body of Friends here,
and many of their sober neighbours are pleased to attend our meetings,
especially when they are visited by strangers.
Second-day rode to a place called Casco, and took boat for Marriconeaque.
In Casco bay are very many islands;
it is generally said there are as many as there are days in the year:
there are also a great many sharks in and about this place.
We had a meeting with our friends at Marriconeaque,
who are very few and I fear not so mindful as they ought to be;
the testimony of Truth was open to reprove and
call sinners to repentance and amendment of life:
we spent the evening at Lemuel Jones`'s. Second-day had a meeting at Barrington,
which was held in a barn; the people were many, and though I was very unwell,
yet the Master strengthened the servant who spake, to the praise of His own great name,
and the meeting ended comfortably.

After meeting rode to Lee, and had a meeting there next day,
and many people came to it of other professions,
among whom were those called New Lights and their preacher.
I was still ill with a disorder that reduced me low in body and mind,
but abundantly strengthened in the Lord`'s blessed cause,
and witnessed his holy presence to attend us, which gave strength to our endeavours;
and we had a glorious meeting, to his praise and our edification.

Fourth-day had a meeting at Epping, to which came many of those called New Lights,
Separatists and others.
Some of these endeavour to outdo Friends in plainness of dress,
the women not wearing any border to their caps,
nor do they put their hair under their caps,
nor allow themselves to wear any clothing that is dyed:
the men also had white clothing from head to foot.
They have set up a meeting of themselves, in the form and manner of Friends,
and hold a Monthly Meeting, etc.
One of them, a woman, appeared in this last meeting; what she said gave trouble to some;
she was requested to be silent,
but persisted till she was easy to sit down of her own accord,
and afterward the meeting settled to better purpose.

Third-day had a meeting at Newbury, which was small and dull,
but suitably ministered unto.
We dined at our ancient friend, Daniel Sawer`'s, whose wife is an acceptable minister,
and had some service in the aforesaid meeting; in the afternoon set forward to Salem,
twenty-five miles; in our way thither rode through Newburyport,
the place where George Whitfield departed this life a little before.
He was a man in great estimation with many for his unwearied labours and services,
both in England and America, as well as in divers other places,
and his removal occasioned much lamentation and sorrow amongst his followers,
which he justly merited.

Fifth-day rode to Boston, it was their Monthly Meeting, which was heavy and dull,
much unsettled by frequent going out and coming in;
some few of the town`'s people came in,
but I had not liberty to open my mouth amongst them by way of testimony.
An ancient Friend at Casco, James Winslow, told me,
his father would often be telling him of the execution
and sufferings of our dear Friends at Boston;
that his father was at that time apprenticed in that town, and saw them all hanged.
I saw the place near to where they suffered, which is now pretty much hid by buildings.
I have also to remark, what before I have read and also been informed,
that whereas before our friends were put to death in this place,
the ground used to produce very good crops of wheat, even very near to the town;
but ever since that time there has not been any of account.
Benjamin Bagnall, an ancient and honourable Friend at Boston, at whose house I lodged,
told me that one of his neighbours related to him, that three years before,
he had a pleasing prospect of a very good crop of wheat,
but when it came into the ear it mildewed and came to little or nothing.
I also made my observation,
while on my religious travels in those parts in the seventh month, 1771,
that there was no wheat growing within twenty miles of the town of Boston.

At their last Yearly Meeting, held at Newport on Rhode Island, for New England,
a proposition was made to address the governor, who was then lately entered into office,
which after weighty consideration was agreed to, and is as follows:

[.embedded-content-document.address]
--

[.blurb]
=== To Thomas Hutchinson, Governor-in-chief in and over the Province of the Massachusetts bay, in New England. The Address of the people called Quakers, at their General or Yearly Meeting for worship, and transacting the affairs of our Society, held on Rhode Island for New England, by adjournments from the 13th to the 17th day of the sixth month, 1771, inclusive.

[.salutation]
May it please the Governor,

As divers of us have had an opportunity of observing thy conduct in the
various public stations in government which thou hast hitherto sustained,
and it appearing to us that thou made justice and equity the rule of thy actions;
thy being appointed to the chief seat of government is
very agreeable and satisfactory to us.
We earnestly desire that thy administration may be to the honour of God,
acceptable to the king, and a blessing to the province over which thou presidest,
afford peace and satisfaction to thyself,
and in the end tend to promote thy immortal happiness.
We hope to be always ready and willing to contribute to the support of government,
in every respect consistent with our religious principles;
and where any of us are or may be restricted thereby within thy jurisdiction,
we entreat thy assistance and protection.
With sincere love to thee, we conclude, and remain thy assured friends.

[.signed-section-closing]
Signed in and on behalf of our said Yearly Meeting by,

[.signed-section-signature]
Isaac Lawton, Clerk.

[.blurb]
=== The Governor`'s Answer.

"`I desire it may be made known to the Friends
within the several governments of New England,
that I have a very grateful sense of the regard and
esteem which they have expressed in this kind address.
It is the more obliging because a great proportion of the members present at
their General Yearly Meeting do not live within my own government.
I shall always delight in confirming and cultivating the orderly benevolent
disposition of the Friends among the several societies of that denomination,
and among all other Christian societies, as far as my influence may extend.`"

--

Very different now,
to what it was in the days when Governor Endicott presided over this province!
Then the sheep of Christ and lambs of the true Shepherd were beaten and bruised,
scoffed and denied, whipped and banished and martyred for the testimony of Jesus,
and for maintaining a conscience void of offence towards God and towards men.
Let thanksgiving and praise be given to the great and holy One,
who hath subdued our enemies and given us the victory!
May we not now, in a time of ease and liberty,
live carelessly and indifferently towards Him,
but in deep reverence and fear worship him, our great Deliverer,
who powerfully wrought in the king`'s heart to the setting at
liberty those sons and children of the morning!

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Boston, 8th of Eighth month, 1771.

[.salutation]
My dear wife and affectionate children,

I am thankful I am now making my return back again toward Philadelphia,
though many hundred miles from it, and not with less peace than in my journey southerly.
Here are many in profession with us,
who I am afraid are contenting themselves too much therewith only,
which makes it very trying to the true and faithful labourers;
yet good is the Lord to all those that are putting their trust and confidence in him;
he feedeth such at times in green pastures and leadeth them by the still waters,
and so we witness preservation from day to day, out of the reach of the archers.

The letters I receive from my dear wife are comfortable and edifying;
I long for more of them.
My heart is renewedly thankful at this time to Him,
who is the Father and Fountain from whence have proceeded all my blessings,
that raised thee up for me and my dear children; and for thy faithfulness,
I trust He will reward thee far beyond what is in my power to do.
Dear son and daughter, write to me again, I entreat you!
Your epistles to me have been as sweet and precious ointment,
and have had a tendency to tender many hearts both young and old.
I thank the Lord for his precious visitation to you,
desiring he may make your way prosperous,
that in his hand you may be made instrumental to turn many from darkness to light,
and from Satan`'s power to the power of God.
And may He preserve you through the various
dispensations of his providence to his praise,
and to the comfort and peace of your own souls.
I exhort you, therefore, to love one another as brethren,
and endeavour to be helpful one unto another, both in things that appertain to this life,
as also to that which is to come; and this I recommend with great earnestness,
if I am never to see you any more, and so remember it.

The weather is hot and sultry, and somewhat hard to bear;
I have sometimes been out of order, with feverish complaints, etc.,
but my trust is in Him who is the Physician of body and soul.
I will trust in Him still, who has hitherto preserved me,
and delivered my soul from trouble.
I am just now returned to Boston, and much overcome with heat;
many have within this week fallen down dead;
the heat of the weather causing great drought
and some imprudently drink largely of cold water,
and to divers it has proved almost immediate death.

The first opportunity I intend to write to my dear brother, who is often in my thoughts;
my love to him, and all our nearest and next kindred, relations and friends everywhere,
from, my dear, thy affectionate husband, and dear children, your affectionate father,

[.signed-section-signature]
Joseph Oxley.

--

We came from Boston to Lancaster, Leicester, Uxbridge and Brickhouse,
where we had a large meeting and silent,
but I hope profitable to such as waited not for words,
but on the Word Himself! +++[+++Passing on through New England]
came the 18th of eighth month to our dear, aged and honourable friend Peter Davis`'s,
of whom I have already made mention.
Third-day had a meeting at Westerly, which was long in gathering,
but after some time of solid waiting.
Truth favoured, and I believe it was a good meeting.
This night we lodged at Thomas Wilbur`'s: our friend Peter Davis was at this time with us,
also Amy Thurston and Mary Rodman, two valuable women Friends from Newport.

Fourth-day had a meeting at Hopkinton,
which was large both of our own and other societies, but long and tedious in gathering.
Suitable advice was given, and I hope with a proper degree of authority,
and the latter end was better than the beginning.
This seems to finish my visit to New England,
wherein I have laboured faithfully according to the ability and strength afforded me,
and much more to my own satisfaction than in the southern part of this continent.
This country, called New England, is more cleared, and thickly inhabited than Maryland,
Virginia, or the Carolinas; the chief produce is Indian corn, some oats and rye,
but very little wheat.
